packages/composer-ui/docker/Dockerfile

The Docker image fails to build as native modules cannot be loaded. This is due to a missing compatibility library in the Alpine Linux base image. Also, I am adding the pm2 process manager to keep the Composer UI server running (incase it crashes).

Get Docker image working on Alpine Linux base

---

.travis.yml
.travis/should-run.sh
packages/composer-systests/scripts/run-system-tests.sh

Adding an additional check to the run-system-tests.sh to only test with the IBM HLF images *when* the build is kicked off from a daily travis 'cron' build.
#140

Feature travis cron

---

packages/composer-ui/src/app/initialization.service.ts
packages/composer-ui/src/app/samplebusinessnetwork.service.ts

The Github integration for samples is very cool, but because we do not authenticate to Github, we run out of our 60 requests/hour per IP very quickly and this is no good for users trying it out for the first time. The Github integration is used to pull down the business network for the initial deploy, so if this fails we end up with an empty business network.
I am re-introducing the hardcoded samples for the initial deploy so that Composer UI will always start up OK. Importantly this will allow Paul to switch his instructions to use our new public Docker images for the final workshop sessions (and it is a great chance to get them tested).
The sample switcher will still use Github integration, and will fail when the rate limit is exceeded. 
Have raised issue #153 to cover that.

Stop using Github for initial deploy

---

packages/site/jekylldocs/tasks/prerequisites.md

The path was missing the packages directory in the pre-reqs section.
Added in.

fix(docs): correct path in pre-reqs

---

packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-playground/src/app/import/import.component.html
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/site/jekylldocs/tasks/github-oauth.md

Update to make client id in ui configurable from server
Updated docs to say what the callback url should be
close fabric-composer/fabric-composer#260

Fix github client id

---

packages/composer-playground/cli.js
packages/composer-playground/config/webpack.prod.js
packages/composer-ui/cli.js
packages/composer-ui/config/webpack.prod.js

As per this page, we need to map all routes to index.html to support HTML5 (no hash) mode:
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode
This should resolve #274

Handle HTML5 mode in Express server

---

packages/composer-admin/package.json
packages/composer-client/package.json
packages/composer-connector-server/package.json

Installation of the v1.0 connector is broken at the moment until the Hyperledger Fabric team start regularly pushing the fabric-client and fabric-ca-client packages up to npm. We need to remove the dependency on this connector from admin, client, and connector-server until it is safe to use again.

Remove dependencies on v1.0 connector

---

packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/loopback-connector-composer/integration-test/businessnetworkconnector-it.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Some json parsers are pedantic about flows that don’t match the defined schema exactly. Generated code from swagger for example fail oif the json document contains more properties than expected. As $class is always flowed on a get the swagger documentation needs to be updated to include it.

fix(loopback): add $class to the loopbackschema

---

packages/composer-connector-hlf/.istanbul.yml
packages/composer-connector-hlf/lib/hfcconnectionmanager.js
packages/composer-connector-hlf/test/hfcconnectionmanager.js

[ ]  A link to the issue/user story that the pull request relates to
[ ]  How to recreate the problem without the fix
[ ]  Design of the fix
[ ]  How to prove that the fix works
[ ]  Automated tests that prove the fix keeps on working
[ ]  Documentation - any JSDoc, website, or Stackoverflow answers?
#427 Composer fails to work reliably with IBM HSBN service
1.
2.
3.
4.

Stop trimming final newline in PEM certificates (#427)

---

.travis.yml
packages/composer-playground/config/webpack.common.js
packages/composer-ui/config/webpack.common.js

This increases build times even further, and now applies to all packages since we started using Lerna's "hoist" mode. Also, the docs build seems to be really slow - I think this is down to it using the Trusty container beta, rather than the Trusty VM - moving to the Trusty VM speeds things up.

Cache the node_modules directory as per Travis CI guidance

---

packages/composer-runtime/lib/resolver.js

I found a weird problem when trying to have array relation fields and many other relation fields in CTO model. During the execution of a transaction, some of the field would just be left as Relation instead of Resource in the transaction object. I found they will be converted into Resource later asynchronously after the execution of the transaction function. Please see the code diff for details.

Fix async problem when resolving array relations

---

packages/composer-playground/src/app/transaction/transaction.component.html
packages/composer-playground/src/app/transaction/transaction.component.ts

issue #404
1.
2..
4.
Used a map to hold parameters that are to be hidden from view. Considered pushing/pulling at areas, but decided that holding parameters in a map would be safer and more extensible.
No longer "stubbing out" a blank transaction, but using the generate instance method - #409 is editing this function to take additional parameters to generate a meaningful empty declaration. A single parameter change will be required here to enable that change once available.
manual testing against all demo cto files

Fix transaction submit to hide id/timestamp

---

packages/composer-common/lib/serializer/jsongenerator.js
packages/composer-common/test/serializer/jsongenerator.js

#469 Relationships to types in other namespaces get corrupted
1.
2.
3.
4.

Stop using fully qualified identifier for some relationships

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/package.json
packages/composer-connector-hlfv1/test/hlfconnection.js

Upgrade to the latest node sdk means the MSP id hack can now be removed.
1.
2.
3.
4.

fix(v1): Upgrade to latest Node SDK

---

packages/composer-playground/src/app/test/test.component.scss

Submit transaction button became shifted to bottom of screen through high level application of padding, need to apply local change in test side-bar to revert the submit button to the correct space
#420 (32)
Open browser, look at button location
move button location by using flex 1
open browser look at button

Move Vertical Location of Submit Transaction (#420 :32)

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

NodeSDK has changed the way errors are done on queryChainCode
1.
2.
3.
4.

fix(v1): queryChainCode Error Handling changed

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

add support for client identity creation
1.
2.
3.
4.

feat(v1): add support for client identity creation

---

packages/composer-runtime/lib/jstransactionexecutor.js

#565 Playground submitted transactions with errors are not always caught
1.
2.
3.
4.

Check to see if result is a thenable, don't use instanceof

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-systests/systest/testutil.js

This adds tls support and a new structure for the connection profile
The changes here do not break non tls support but pave the way for tls support and will be solidified when system tests in a tls mode is delivered
in another pull request.

tls support and new structure for connection profile

---

packages/composer-website/jekylldocs/business-network/deploybusinessnetwork.md
packages/composer-website/jekylldocs/introduction/participantsandidentities.md
packages/composer-website/jekylldocs/tutorials/getting-started-cmd-line.md

Broken links appear to have been introduced following some md file name changes 
#614
inspect links reported in listed issue above
fix links
followed links manually on jekyll serve

Fix broken links

---

packages/composer-common/lib/businessnetworkdefinition.js

Use of `businessNetworkDefinition.fromDirectory()` was not working when using linked node modules in development, as `*.cto` files from `node_modules` in the linked module (including the test models in `composer-common`) are picked up.
This fix ensures that files within `node_modules` *underneath* toplevel package dependencies are never processed.
I think this is a pretty simple fix but please let me know if any further info is required (:

fix node_modules being processed in businessNetworkDefinition when package dependencies are symlinked with npm-link

---

packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/resource/resource.component.html
packages/composer-playground/src/app/resource/resource.component.spec.ts
packages/composer-playground/src/app/resource/resource.component.ts
packages/composer-playground/src/app/transaction/transaction.component.html
packages/composer-playground/src/app/transaction/transaction.component.spec.ts
packages/composer-playground/src/app/transaction/transaction.component.ts

Extension of tests per #658 for Resource and Transaction components, inclusive of edits to Transaction component model file to remove redundant code
#658
Add tests to check UI DOM tree aspects
Refactor existing tests to account for code removal in Resource component model
Refactor existing tests to increase depth of coverage and ensure we are testing expected output
Manual testing

update resource and transaction tests

---

packages/composer-runtime-hlfv1/chaincode.go
packages/composer-runtime-hlfv1/composerpool.go
packages/composer-runtime-hlfv1/main.go

enable debug logging for composer in HLFV1 as it is completely off and not controllable at present making debug difficult.

fix(v1): turn on debug logging for composer runtime

---

packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/network/lib/download.js
packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/lib/cmds/network/lib/undeploy.js
packages/composer-cli/lib/cmds/transaction/lib/submit.js
packages/composer-common/lib/fsconnectionprofilestore.js

Address all places where the error
‘TypeError: Cannot read property 'fail' of undefined’
and ensure error message indicates the problem is in a connection profile and why.

fix(cli): address all issues with spinner and useful error messages

---

packages/composer-playground/src/app/editor-file/editor-file.component.html
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/services/client.service.ts

Fix required to enable package edit in #683 
Open an instance of composer (either on bluemix or local), open a file (LHS)
-> if no ACL present, errors will be shown inthe console
Do above, select edit, select "edit package". This will result in the inability to edit the package.
Condition use of acl file during project import
Edit html to enable package edit click action
Edit component file to change logic behind view/navigation operations
Manual testing and extended automated testing
Automated testing is included as part of fix

Fix package edit and add test coverage for fix

---

packages/composer-rest-server/test/transactions.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

#842 REST API for submitting a transaction does not return transaction ID
1.
2.
3.
4.

Return the transaction ID when submitting a transaction to the REST server

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

#877 Cannot connect to HLFv1 using playground connection profiles 
1. Create a HLFv1.0 connection profile
2. Attempt to use HLFv1.0 connection profile
3. Witness errors
The HLFv1 connector has an abstract list() method which means we cannot determine which business networks have been deployed to the specified Hyperledger Fabric instance. I have implemented it to use the queryInstantiatedChaincodes() function from `fabric-client`.  Handily we can use the `path` property for each instantiated chaincode to test for Composer business networks.
The admin connection code has been extended to ping() the business network on connection, if a business network was specified. Before, for HLFv0.6, we tested the presence of the business network in the connection profile, but since we aren't recording …

Add missing method for HLFv1 connector and ping in establishment of admin connection

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

ignore already installed on an install request and allow an instantiate to continue

fix(hlfv1): ignore already installed errors from fabric when trying to install

---

packages/composer-playground/src/app/identity/identity.component.spec.ts
packages/composer-playground/src/app/identity/identity.component.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/identity.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/switch-identity/switch-identity.component.spec.ts
packages/composer-playground/src/app/switch-identity/switch-identity.component.ts

Switch identities without requiring a browser refresh

---

packages/composer-common/lib/acl/aclrule.js
packages/composer-common/lib/acl/parser.pegjs
packages/composer-common/test/acl/aclfile.js
packages/composer-common/test/acl/aclrule.js
packages/composer-common/test/acl/model.cto
packages/composer-common/test/acl/test.acl
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/accessexception.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/test/accesscontroller.js
packages/composer-runtime/test/context.js

As a business network developer would like to restrict direct CRUD access to an asset, instead asset manipulations can only take place through transactions #575
1.
2.
3.
4.

Add optional transaction requirements to ACL rules

---

packages/composer-common/lib/modelmanager.js
packages/composer-common/test/modelmanager.js
packages/composer-playground/src/app/add-file/add-file.component.spec.ts
packages/composer-playground/src/app/add-file/add-file.component.ts
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/assets/svg/other/error_dot.svg

Code delivery for #389
Namespace change enabled:
- user may change namespace of file
- namespace collision detection will prevent overwriting of existing model files
- new Behaviour subject for file name changes
- invalidation of acl files will be indicated visually and user will not be able to deploy broken BND
- updated add model file and script file logic for new file additions
- added tests for all 
Initial manual testing, supported with automated tests

Enable namespace changes to model files via composer

---

packages/composer-playground/src/app/add-file/add-file.component.spec.ts
packages/composer-playground/src/app/add-file/add-file.component.ts
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Fix for #1093
Adds file extension to required function call.
Modifies existing tests to take into account need to call createScript function with correct parameters
Manual local validation on built product
Requirement to update existing tests

add fix and enhance tests to support required behaviour

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Within #1091 a page revisit to the Define section was not initialising correctly, this pull request fixes that by:
- calling set page if editor service returns a set file
- ensuring the business network changed callback always works from an updated file list 
The page needed to set the current file rather than accept a file retrieved from the editor service, this is because during the file setting, additional flags are applied that indicate if it may be deleted etc.
The business network changed callback needed to ensure that it was running with the most recent file list as it had the potential to use an out of date file list during validation.
Manual test on local build, extension of automated tests to prevent regression.
Pending memory leak tests, and that will be the subject of …

Condition editor define for page re-visit

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Part of #1091
Previous behaviour was to create a new subscription to the same event upon return to page - this was resulting in actioning all subscriber callbacks when an event was emitted. This was resulting in both a memory leak, and the code being executed on out of date information.
Detailed within #1091 
Cleanup within an ngOnDestroy, that switches a flag used by a "takeWhile" applied to the subscription
Application of best practise clean-up for angular subscribers. Manual testing completed against original scenario, in addition to exploratory testing.
Updated existing unit tests.

Tidy up subscriptions to event emitters on navigation away from page

---

contrib-notes/weekly-qa-validation.md

Playground requires testing from a user perspective. This should be performed via automated Protractor tests, and until those are established a manual process is required. This PR modifies the release process to include the required Playground testing aspects, and indirectly is related to #449

extend release validation to include playground testing

---

packages/composer-playground/protractor.conf.js

Mac driver required for users running Protractor tests on mac
Continuation of #863
- Added mac driver
- Renamed linux driver
- Added OS branch in protractor conf file to select relevant driver

add chrome driver for mac and driver selector branch in conf file

---

packages/composer-common/lib/businessnetworkdefinition.js

If importing from github, model files do not have filenames and this will result in import failures. It is necessary to condition for null filename values and conditionally use namespaces instead.
This was a defect found against #387 during manual test validation script running

Condition for no filename on model file

---

packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-systests/systest/accesscontrols.js
packages/composer-systests/systest/assets.js
packages/composer-systests/systest/events.js
packages/composer-systests/systest/identities.js
packages/composer-systests/systest/participants.js

If running sample installation via npm, model files do not have filenames and this will result in import failures. It is necessary to condition for undefined filename values and conditionally use namespaces instead.

Undef conditioning and test support

---

packages/composer-common/lib/acl/aclrule.js

This fixes #1392 by stopping the use of `thing.constructor.name` which when webpacked in production mode will not work because webpack/uglify changes the name of the classes. It's an evil way to check the type anyway, so just use `instanceof` instead.
Cannot create ACL file in playground #1392
1.
2.
3.
4.

Fix issue 1392

---

packages/composer-playground/package.json

Due to breaking changes in 0.9.0
This should eventually be fixed but needs to stay in for this
release

Need unstable playground to use unstable basic sample network

---

packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts

Excluded non .js files from being imported from GitHub. This is currently preventing the trade-network sample from being imported, because it contains an eslint yml file under scripts.

Prevent non JS files from being imported from GitHub

---

packages/composer-playground-api/package.json
packages/composer-playground-api/routes/npm.js
packages/composer-playground-api/test/npm.js

The npm import from Playground works locally, but fails on unstable Bluemix with this error:
Response with status: 502 Bad Gateway for URL: http://composer-playground-unstable.mybluemix.net/api/getSampleList
The error is occurring as the version is modified by the build to be just `0.9.1-2017...`, along with all the dependencies. There is a substring being used to remove a leading `^`, but that is not present when we bind all the package versions together using `pkgstamp`, and so we try to parse the invalid version `.9.1-2017...` which causes the process to crash.
Made a few changes:
- Run tests with two different Composer versions, one released (0.9.0) one prerelease (0.9.0-2017...)
- Add a network that depends on 0.9.1 to check its excluded correctly
- Remove pkginfo and just grab the …

Playground import from npm fails to work for unstable

---

packages/composer-connector-proxy/lib/proxyutil.js
packages/composer-connector-proxy/test/proxyutil.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/aclcompiler.js
packages/composer-runtime/lib/compiledaclbundle.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.businessnetworks.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/test/accesscontroller.js
packages/composer-runtime/test/aclcompiler.js
packages/composer-runtime/test/compiledaclbundle.js
packages/composer-runtime/test/context.js
packages/composer-runtime/test/engine.businessnetworks.js
packages/composer-runtime/test/engine.js
packages/composer-systests/systest/accesscontrols.js
packages/composer-systests/systest/data/accesscontrols.acl
packages/composer-systests/systest/data/accesscontrols.js
packages/composer-website/jekylldocs/reference/acl_language.md

Allow an ACL rule condition to call a utility function defined in a script file.
This allows users to define utility functions which perform complex tests on resources without having to cram it into the condition clause of a ACL rule, and also enables unit testing and code coverage of those utility functions.
Example:
```
rule R5 {
description: "A participant can delete themselves"
participant(p1): "systest.accesscontrols.SampleParticipant"
operation: DELETE
resource(p2): "systest.accesscontrols.SampleParticipant"
condition: (participantsAreEqual(p1, p2))
action: ALLOW
}
```
```
/**
* Test that the specified participants are the same.
* @param {Resource} participant1 The first participant.
* @param {Resource} participant2 The second participant.
* @return {boolean} True if yes, false if …
```

Allow ACL rule conditions to call utility functions

---

packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts

Related to #1446 
Turns out that we were trying to reuse the internal system models when creating the business network for replacement.... this was being rejected on the creation stage as they have reserved namespaces.
failure of this is detected in (pending) protractor tests that uncovered the issue.
Filter out system models before use. A nice enhancement could (should?) be the enablement of updating information of a bnd via compose-common changes (enabling metadata updates etc).

filter system models from results when updating playground BNDs

---

packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/api.js
packages/composer-runtime/lib/callbackrelationship.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/lib/invalidrelationship.js
packages/composer-runtime/lib/registry.js
packages/composer-runtime/lib/resolver.js
packages/composer-runtime/test/accesscontroller.js
packages/composer-runtime/test/api.js
packages/composer-runtime/test/callbackrelationship.js
packages/composer-runtime/test/context.js
packages/composer-runtime/test/engine.queries.js
packages/composer-runtime/test/engine.transactions.js
packages/composer-runtime/test/invalidrelationship.js
packages/composer-runtime/test/registry.js
packages/composer-runtime/test/resolver.js
packages/composer-systests/systest/accesscontrols.js
packages/composer-systests/systest/data/accesscontrols.acl
packages/composer-systests/systest/data/accesscontrols.cto
packages/composer-systests/systest/identities.js
packages/composer-systests/systest/testutil.js

Rework the runtime access controller to permit ACL rules that resolve and navigate relationships.
For example, when writing an ACL rule for an asset, you often want to look at the owner of the asset and make the decision based on some property of the owner.
Here is a daft example:
```
rule R7 {
description: "The owner of a vehicle can update the vehicle"
participant(p1): "systest.accesscontrols.SampleParticipant"
operation: UPDATE
resource(p2): "systest.accesscontrols.SampleParticipant"
condition: (p1.asset.owner.firstName === p2.asset.owner.firstName && p1.asset.owner.asset.owner.lastName === p2.asset.owner.asset.owner.lastName)
action: ALLOW
}
```
The changes require quite a bit of work:
- Repurposing a lot of code from `QueryExecutor` into `Resolver` so that resources can be prepared …

Allow ACL rules to resolve and navigate relationships

---

packages/composer-cli/lib/cmds/generator/createCodeCommand.js
packages/composer-cli/lib/cmds/identity/importCommand.js
packages/composer-cli/lib/cmds/identity/issueCommand.js
packages/composer-cli/lib/cmds/identity/lib/issue.js
packages/composer-cli/lib/cmds/identity/revokeCommand.js
packages/composer-cli/lib/cmds/participant/addCommand.js
packages/composer-cli/lib/cmds/transaction/submitCommand.js
packages/composer-cli/test/identity/issue.js
packages/composer-cli/test/identity/revoke.js
packages/composer-cli/test/participant/add.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

Also fixed problems with the command line where it could output
- Command Failed
Followed by
- Command Succeeded

feat(v1): Support connector specific options on identity issue

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/composer-common/lib/factory.js
packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/lib/introspect/property.js
packages/composer-common/lib/introspect/relationshipdeclaration.js
packages/composer-common/lib/model/typed.js
packages/composer-common/lib/modelutil.js
packages/composer-common/lib/serializer.js
packages/composer-common/lib/serializer/instancegenerator.js
packages/composer-common/lib/serializer/jsonpopulator.js
packages/composer-common/lib/serializer/valuegenerator.js
packages/composer-common/test/factory.js
packages/composer-common/test/serializer/instancegenerator.js
packages/composer-common/test/serializer/valuegenerator.js
packages/composer-playground/src/app/test/resource/resource.component.html
packages/composer-playground/src/app/test/resource/resource.component.ts
packages/composer-playground/src/app/test/transaction/transaction.component.html
packages/composer-playground/src/app/test/transaction/transaction.component.ts
packages/generator-hyperledger-composer/generators/angular/index.js

Change composer-common/Factory API so that:
- An _includeOptionalFields_ option controls whether optional fields are included in generated data.
- Array field values are generated with a single element (rather than three) for _sample_ data generation, and with no values for _empty_ data generation.
Add _Optional Properties_ checkbox to create new resource and submit transaction dialogs.

PR for #796

---

packages/composer-common/lib/connectionprofilemanager.js

Better error message and correct logging if connector module cannot be loaded.

More useful error message for connector not loaded problems

---

.travis/before-install.sh
.travis/install.sh

- Remove install of Docker and Docker Compose which takes AGES and they are already at the latest levels, possibly a result of recent upgrades to the Trusty build environment.
- Remove sudo for pip which spews warnings, and combine into a single pip command.
- Add lerna to npm install, and combine into a single npm command.
- Use lerna bootstrap instead of npm install which massively reduces install time.
It seems that npm install spends a long time doing something, where lerna bootstrap does not. It might be that npm is struggling to deal with the huge number of dependencies that lerna dumps into node_modules? 
I'm in favour of keeping npm install as is (automatically runs lerna bootstrap) as its easier for first time contributors to use, but we don't have to use it in the builds.

Improve build performance

---

packages/composer-playground/src/app/app.component.html
packages/composer-playground/src/app/app.component.spec.ts
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/assets/styles/elements/_header.scss

final component of #1571:
- Provides mouseOver select indicator (border-bottom) and persists the select indicator on router navigation.
- Restyle of the dropdown to provide "triangle" at top of drop container.

Enable styled dropdown for Id panel

---

packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.html
packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.scss
packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.ts
packages/composer-playground/src/app/connection-profile/connection-profile.module.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.html
packages/composer-playground/src/app/identity/add-identity/add-identity.component.scss
packages/composer-playground/src/app/identity/add-identity/add-identity.component.spec.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.ts
packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/identity/identity.component.spec.ts
packages/composer-playground/src/app/identity/identity.component.ts
packages/composer-playground/src/app/identity/identity.module.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.scss
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/login/login.module.ts
packages/composer-playground/src/assets/styles/base/_variables.scss
packages/composer-playground/src/assets/svg/action-based/role_24.svg

Addition of ID card to identities:
- Create ID card botton added to login page (removed from identities registry page)
- Flow enables creation of ID based on UserId and Secret only
- Flow enable targeting existing Connection Profile, or may take user through creation of new Connection Profile prior to binding ID card to that newly defined profile
#1423 
Tests refactored and added where appropriate
Followed the design from parent issue

Add new id card creation flow to identities 

---

packages/composer-playground/src/app/services/identity-card-storage.service.spec.ts
packages/composer-playground/src/app/services/identity-card-storage.service.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/app/services/services.module.ts

There is nothing unique about identity cards so they need to
be referenced by uuids
Contributes to #902

Add identity card service to playground

---

packages/composer-playground/package.json
packages/composer-playground/src/app/services/connectionprofile.service.spec.ts
packages/composer-playground/src/app/services/connectionprofile.service.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

with a web profile now share a fixed connection profile, and
other connection profile names are now prefixed with a hash of
the connection profile object.
Also adds a function to get an idcard with required role and
updates the connection profile service to avoid overwriting
existing connection profiles.
Contributes to #902

Change qualified names for connection profiles- identity cards

---

packages/composer-playground/src/app/directives/check-scroll/check-scroll.directive.spec.ts
packages/composer-playground/src/app/directives/check-scroll/check-scroll.directive.ts
packages/composer-playground/src/app/directives/directives.module.ts
packages/composer-playground/src/assets/styles/elements/_button.scss

- Use height instead of padding to match the height of the text that the spinner replaces
- Tried `padding: 5% 12%`, but inconsistent results
- insert missing `checkScroll` directive that had been accidentally removed in a recent `git merge`

1744 - Make spinner/text consistent size on action buttons

---

packages/generator-hyperledger-composer/generators/businessnetwork/templates/lib/logic.js
packages/generator-hyperledger-composer/generators/businessnetwork/templates/models/namespace.cto
packages/generator-hyperledger-composer/generators/businessnetwork/templates/test/logic.js

- Rename asset from `Asset` to `SampleAsset`, as Asset is a reserved word.
- Remove transactionId field from transaction as now defined in system model for transactions.

Fix Yeoman generator sample application .cto

---

packages/composer-rest-server/lib/loopbackwallet.js
packages/composer-rest-server/test/lib/loopbackwallet.js

Time Elapsing Breaks Wallet Identities #1731
Secure REST server error - The current identity has not been registered #1784
1.
2.
3.
4.
When REST server security is enabled, the LoopBack connector goes into "multi-user" mode. This means that each authenticated user has their own business network connection, that uses their own identities from their wallet. The LoopBack connector maintains a pool of these connections, and expires them after 5 minutes.
The REST server provides a `Wallet` implementation, `LoopBackWallet` that provides a view into the `WalletIdentity` data source. However, most of the methods in `LoopBackWallet` do not use the LoopBack APIs correctly - the where clause is not specified, and they end up selecting the first `WalletIdentity` the data source returns.
When the …

LoopBack wallet uses incorrect wallet identity query

---

packages/composer-playground/src/app/app.component.html
packages/composer-playground/src/app/login/identity-card/identity-card.component.html
packages/composer-playground/src/app/login/identity-card/identity-card.component.scss
packages/composer-playground/src/app/login/identity-card/identity-card.component.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/app/services/initialization.service.ts
packages/composer-playground/src/assets/styles/elements/_header.scss

Restrict use of identity cards when playground is not being used locally
Closes #1885

Restrict use of identity cards in web playground

---

packages/composer-playground/e2e/component/import.ts
packages/composer-playground/e2e/specs/editor-define.spec.ts
packages/composer-playground/e2e/utils/operations-helper.ts
packages/composer-playground/src/app/import/import.component.html

The switch to using npm to host BNAs would appear to be causing unreliability in the protractor test suite, as described/outlined in #1944, this PR:
- explicit 'scroll-to' prior to click operation
- provides an explicit check on base sample types
- provides an explicit check on npm hosted sample types
- provides an import select via named sample
- increases tests to include import of all known sample networks
Note: to reduce binding to possible changes in npm samples, the only action checked in the import is that it succeeds - we are not checking installed files at this time

Modify protractor tests to increase reliability

---

packages/composer-playground/protractor.conf.js

Protractor proving to be unstable when using npm #1944
1.
2.
3.
4.
E2E tests are much unreliable, such sad but they must be disabled as it's killing our PR throughput.

Disable E2E tests

---

packages/composer-playground/src/app/import/deploy.component.spec.ts
packages/composer-playground/src/app/import/update.component.spec.ts
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/app/services/identity.service.spec.ts
packages/composer-playground/src/app/services/identity.service.ts
packages/composer-website/jekylldocs/managing/id-cards-playground.md

Ensure exported identity cards include certificates and private
keys when they are available.
Also includes some refactoring to simplify how cards are activated
and minimise the time that credentials are kept in the browser.
Completes #1427

Ensure exported identity cards include certificates and private

---

packages/composer-playground/src/app/app.component.spec.ts
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/services/config.service.spec.ts
packages/composer-playground/src/app/services/config.service.ts
packages/composer-playground/src/app/services/connectionprofilestore.service.spec.ts
packages/composer-playground/src/app/services/connectionprofilestore.service.ts
packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.ts
packages/composer-playground/src/app/services/services.module.ts

Using the v0.12.0 playground on safari throws breaking error #1982
1.
2.
3.
4.
Web connection profiles contain a `networks` object that stores a mapping of business network names to UUIDs. Those UUIDs are the names of PouchDB databases that live in the web browser and store the actual business network data (the world state) for that business network.
Because the web connection profiles contain browser specific data, they are not suitable for sharing across different browsers or even different machines - so we really shouldn't be writing them to the disk via the connector server!
This fix stops the proxy connection profile store from being used at all in the cloud hosted Playground. We don't know why, but socket.io does not work at all when being served from the cloud hosted Playground on …

Use file system connection profile store in web only mode

---

packages/composer-rest-server/cli.js
packages/composer-rest-server/common/models/wallet.js
packages/composer-rest-server/lib/util.js
packages/composer-rest-server/package.json
packages/composer-rest-server/server/boot/authentication.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/server/boot/composer-runtime.js
packages/composer-rest-server/server/composer.json
packages/composer-rest-server/server/server.js
packages/composer-rest-server/test/authentication.js
packages/composer-rest-server/test/cli.js
packages/composer-rest-server/test/data/bond-network/permissions.acl
packages/composer-rest-server/test/ldapserver.js
packages/composer-rest-server/test/lib/util.js
packages/composer-rest-server/test/multiuser.js
packages/composer-rest-server/test/server/boot/authentication.js
packages/composer-rest-server/test/server/boot/composer-runtime.js
packages/composer-rest-server/test/server/server.js
packages/composer-website/jekylldocs/integrating/call-out.md
packages/composer-website/jekylldocs/integrating/deploying-the-rest-server.md
packages/composer-website/jekylldocs/integrating/enabling-multiuser.md
packages/composer-website/jekylldocs/integrating/enabling-rest-authentication.md
packages/composer-website/jekylldocs/integrating/node-red.md
packages/composer-website/jekylldocs/integrating/securing-the-rest-server.md
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/assets.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

As a user, I can authenticate users of the REST API without requiring multi-user mode #2016
1.
2.
3.
4.
These changes split the "security" or `-S` option into two separate options, "authentication" or `-a` and "multiuser" or `-m`. Use of the "multiuser" option automatically implies "authentication".

Split REST server security option into authentication and multiuser options

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Part of #1930 
The update (import business network when editing bus-net) was not closing the modal on close option.
add modalref.close() to else case
browser check and tests added
2 tests extended for cancel and error case

add drawer closure on cancel

---

packages/composer-playground/src/app/login/identity-card/identity-card.component.html
packages/composer-playground/src/app/login/identity-card/identity-card.component.scss
packages/composer-playground/src/app/login/identity-card/identity-card.component.spec.ts
packages/composer-playground/src/app/login/identity-card/identity-card.component.ts
packages/composer-playground/src/assets/styles/elements/_button.scss
packages/composer-playground/src/assets/svg/other/tool.svg

capabilities.
Instead of completely hiding portions of the identity card, this fix
disables any elements which are not applicable.
Contributes to #1930

Keep identity cards a uniform size irrespective of their different

---

MAINTAINERS.md

As requested by Hyperledger a while ago, formalize the list of maintainers by adding a file `MAINTAINERS.md` to the root of the project that lists all of the maintainers along with their GitHub IDs.

Formalize the list of maintainers

---

packages/composer-common/lib/idcard.js
packages/composer-common/test/idcard.js
packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

This mitigates the impact of version changes for code that uses
the constructor directly, provided the metadata supplied includes
a version property.
Contributes to #2115 

Move IdCard migration from fromArchive to constructor

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/connection.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/lib/util.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/connection.js
packages/composer-common/test/modelmanager.js
packages/composer-common/test/util.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js

The transaction id has been delegated to each connector - such that the hlfv1 connector use fabric client. The other connectors will return null so the common layer 'fall back option is used. This uses uuid to create a id as previously.

tx id as per fabrics

---

packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.spec.ts
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.ts

As stated in issue #2144, previously when trying to create an ID card using certificates, if those certificates contained \n they did not work correctly. This issue has been fixed and the creation can now deal with \n within the certificate string.

#2144 - Fixed new line character issue with certs

---

packages/composer-common/lib/introspect/parser.pegjs
packages/composer-common/test/model/typed.js

Asset attributes with a type of Double are unable to have a default value #2187
1.
2.
3.
4.
Grammar is incorrect and parses the default double value literal into an object that we then call `parseFloat` on - this causes a wild `NaN` to appear. Fix the grammar to parse the default double value literal as a string so we can parse it into the correct type later on.

Correctly handle default double values in grammar (resolves #2187)

---

packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js

Web profile lets you add new ids even if not issuer #1770
1.
2.
3.
4.
The fake CA used by the embedded and the web runtime stores all of the identities that are issued. We need to store the issuer flag (along with any other options) so we can simulate the ACL check performed by the Fabric CA during `createIdentity`.

Store issuer flag in identity in fake CA (resolves #1770)

---

packages/composer-common/lib/acl/modelbinding.js
packages/composer-common/lib/acl/parser.pegjs
packages/composer-common/lib/modelutil.js
packages/composer-common/test/acl/modelbinding.js
packages/composer-common/test/modelutil.js
packages/composer-runtime/test/accesscontroller.js

As a network starter, I can bind an initial set of identities to participants at deployment time #670
Permit an ACL rule to reference _all_ types in the business network without knowledge of the namespace. I'm introducing this so we can deliver sample ACL rules that work for all business networks without having to force us or users to provide the right namespace in those rules.
Should permit ACL rules such as:
```
rule EverybodyCanReadEverything {
description: "Allow all participants read access to all resources"
participant: "org.acme.sample.SampleParticipant"
operation: READ
resource: "**"
action: ALLOW
}
```
All instances of SampleParticipant have READ access to all instances of all types in the business network, including the system types.

Allow ACL wildcards at root level (contributes to #670)

---

packages/composer-common/lib/system/org.hyperledger.composer.system.cto
packages/composer-common/test/codegen/loopbackvisitorcircular.js
packages/composer-runtime/test/registrymanager.js

As a network starter, I can bind an initial set of identities to participants at deployment time #670
Add a NetworkAdmin participant that we can bind an identity to during deployment if no bootstrap participants are specified. Adding this in ASAP so we can get the ACLs prepared ahead of time.

Add network admin participant (contributes to #670)

---

packages/composer-playground/src/app/import/deploy.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/import/update.component.spec.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts

As a network starter, I can bind an initial set of identities to participants at deployment time #670 
Playground doesn't work - oops.
Need to bind the `admin` identity to a `NetworkAdmin` participant so the `admin` identity can be used to access the newly deployed business network. Whilst I'm in here, I'm adding a `permissions.acl` file for the empty network so it can be used.

Cannot use business networks deployed using playground

---

.travis/before-install.sh

Builds are failing all over the place as the GPG key for MongoDB has expired, meaning we can't run any `apt` commands.

Remove MongoDB repo as GPG key has expired

---

.gitignore
packages/composer-website/.gitignore
packages/composer-website/jekylldocs/jsdoc/index.html

Added a simple redirect.
Note that if a file has the --- then jekyll will run it's template engine over it. therefore the correct base url is usable.

add redirect for original jsdoc location

---

packages/composer-website/jekylldocs/index.html

Because the link checker is failing when I include a href to the release notes, for now we'll just get in a lame version where the user has to copy/paste the URL, and then when we figure out what's up with the link checker failing it, we can improve!
This is adding in the homepage banner stating that 0.14 may break existing projects, and offering the URL to the release notes.

Add a lamer version of the header with no link

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

This pull request addresses
https://github.com/hyperledger/composer/issues/2056
where rather than allowing an issued identity to be enrolled indefinitely it restricts it to a single enrollment and if you lose the crypto material then you cannot automatically re-enroll the user. Basically it will stop the confusion of identity not being registered when a user someone re-enrolls a user they had already bound to a participant and not understand why it doesn’t work as effectively it is a new certificate (admittedly for the same identity) and it would then output a different error message this time from the CA saying cannot enroll.

only allow a single enrollment per issued identity

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/factory.js
packages/composer-common/lib/introspect/validator.js
packages/composer-common/test/factory.js
packages/composer-common/test/introspect/stringvalidator.js
packages/composer-playground/src/app/test/resource/resource.component.spec.ts
packages/composer-playground/src/app/test/resource/resource.component.ts

issue1012
The original issue was that the user couldn't use a regex on an asset/participant identifier because the automatic generation of ids was highly unlikely to pass the regex test (e.g. email address).
This then moved into a discussion about what the behaviour of Playground should be when creating new instances. The design team have observed that in many cases, the users' first action is to change the generated ID to something they'd prefer and so the idea now is that the playground should not generate any sample data (even the ID) when a new instance is being created via the 'Add Asset\Participant' buttons. 
The effect of this is that a skeleton object can always be generated now but the user will have to add a valid ID before it can be committed to the blockchain.  Also, since …

Added new option to Factory API

---

.travis/before-install.sh

To address #2407 - re-enable mongoDB removal line in the travis before-install.sh 

remove mongo db in travis before-install.sh

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/cardstore/filesystemcardstore.js
packages/composer-common/lib/idcard.js
packages/composer-common/lib/util.js
packages/composer-common/test/cardstore/filesystemcardstore.js
packages/composer-common/test/idcard.js
packages/composer-common/test/util.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js

Contributes to #935 
Remove portability constraint for connection profiles due to keyValStore path.
Store Fabric client data in a defined path based on the name of the Business
Network Card being used, rather than the absolute path specified in the keyValStore
property of the connection profile.

Improve portability of Connection Profiles

---

packages/composer-cli/lib/cmds/network/deployCommand.js
packages/composer-cli/lib/cmds/network/downloadCommand.js
packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/network/lib/download.js
packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/lib/cmds/network/lib/loglevel.js
packages/composer-cli/lib/cmds/network/lib/ping.js
packages/composer-cli/lib/cmds/network/lib/reset.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/lib/cmds/network/lib/undeploy.js
packages/composer-cli/lib/cmds/network/lib/upgrade.js
packages/composer-cli/lib/cmds/network/listCommand.js
packages/composer-cli/lib/cmds/network/loglevelCommand.js
packages/composer-cli/lib/cmds/network/pingCommand.js
packages/composer-cli/lib/cmds/network/resetCommand.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/network/undeployCommand.js
packages/composer-cli/lib/cmds/network/updateCommand.js
packages/composer-cli/lib/cmds/network/upgradeCommand.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/network/list.js
packages/composer-cli/test/network/loglevel.js
packages/composer-cli/test/network/ping.js
packages/composer-cli/test/network/reset.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/network/undeploy.js
packages/composer-cli/test/network/upgrade.js

Within this PR for #2333 
- Updated all the network clis to take a card instead of the collection of the connection profile, network name, enrollid/secret
- Access the card store for these instead - relies on card store semantics for if it doesn't exist etc.
- Remove the old options from the yargs cli specs.
- As we had an update to yargs, was able to go back to using `choices()` for the log level
- Loglevel had some different spellings in the tests so harmonised all of those.

Story2333 network cli

---

packages/composer-runtime-hlfv1/chaincode.go
packages/composer-runtime-hlfv1/composer.go
packages/composer-runtime-hlfv1/datacollection.go
packages/composer-runtime-hlfv1/dataservice.go

closes #2514 
Adds duration timestamp information through the go code under runtime hlfv1, will be observed within debug trace only

add time duration logging to runtime go code

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/card/lib/import.js
packages/composer-cli/lib/cmds/utils/cmdutils.js
packages/composer-cli/test/card/import.js
packages/composer-cli/test/utils/cmdutils.js

Resolves #2587 
Also reverse the order of parameters to better match previous connection profile
API, card store API and Map APIs in general.
No longer returns the card name as this is always specified by the caller.

Make name parameter mandatory for AdminConnection.importCard

---

packages/composer-runtime/lib/registry.js
packages/composer-runtime/test/registry.js

Filter objects returned by getAll to remove model-invalid objects.

Issue2485 Filter returned objects to remove model-invalid instances

---

packages/composer-rest-server/common/models/card.js
packages/composer-rest-server/package.json

As a user, I can import existing identities into my REST server wallet #2072 
Upgrade to latest LoopBack explorer for latest Swagger UI:
- Needed to support configuration of Swagger tags, so we can change the API category "Card" to "Wallet" in the UI
- Needed to properly support formData parameters to allow file upload in the UI.
Fix the import of business network cards so that certificates/private keys are imported into the wallet, broke with the latest business network card changes.

Fix import of business network cards, upgrade Swagger UI

---

packages/composer-rest-server/package.json

As a user, I can import existing identities into my REST server wallet #2072 
🤦‍♂️ 🐧 👎

Add missing composer-admin dependency to REST server

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-rest-server/public/lib/loadSwaggerUI.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/test/system.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

As a user, I can import existing identities into my REST server wallet #2072
Update the LoopBack connector and REST server such that the issue identity API generates a new business network card. This is instead of an enrolment ID and secret pair, which is very difficult to use for a REST client as they would have to _somehow_ package it up into a business network card themselves.

Issue business network cards from the REST server

---

packages/composer-cli/lib/cmds/identity/lib/request.js
packages/composer-cli/lib/cmds/identity/requestCommand.js
packages/composer-cli/lib/cmds/network/deployCommand.js
packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/transaction/submitCommand.js
packages/composer-cli/test/identity/request.js
packages/composer-cli/test/network/deploy.js

- Composer request identity to take a --card
- Deploy and Start now take a string after the -S 
- transaction submit should not have the profile options

Composer CLI updates for cards

---

packages/composer-cli/lib/cmds/identity/bindCommand.js
packages/composer-cli/lib/cmds/identity/lib/bind.js
packages/composer-cli/test/identity/bind.js

Add in a --card option to replace the collection of the connection profile, enroll secret, ,enroll id.
left the code structure as is, but removed the enroll secret etc specific parts.

convert identity bind to use cards

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/card/lib/create.js
packages/composer-cli/test/card/create.js

Resolves #2630 
Also don't fail export if a card that exists in the system doesn't look valid. It's
already in the system. It's too late to complain now.

Correctly create card with no credentials in 'composer card create'

---

packages/composer-cli/lib/cmds/utils/cmdutils.js
packages/composer-cli/test/utils/cmdutils.js
packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/cardstore/businessnetworkcardstore.js
packages/composer-common/lib/idcard.js
packages/composer-common/test/cardstore/businessnetworkcardstore.js

Resolves #2621 
Common code for default naming of cards in a card store, for use by both the CLI
and Playground to ensure consistent default naming behaviour.

Add BusinessNetworkCardStore.getDefaultCardName static function

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js

Resolves #2645 
The certificates still need to be added to the exported card but don't
need to be included in the card store copy as they still live in the
client store.

Do not write updated card to card store on export

---

packages/composer-connector-hlfv1/package.json

we pinned to grpc 1.6.6 because 1.7.0 release was broken for our docker images.
They have fixed this in 1.7.1 so we should revert back as there could be a fix to the
TLS problem we currently have
closes #2572

remove restriction for grpc version

---

packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/identity/identity.component.spec.ts
packages/composer-playground/src/app/identity/identity.component.ts

#2417 
Fix follows solution outlined in the issue and prevents user cancelling the remove process when revoking by not showing the modal.
- Split remove function from its modal so that button press opens modal which then calls the remove whilst revoking just calls the remove once revoke is performed. 
- Updated tests to test modal and remove separately.

Fix for cancelling a remove when revoking an identity (Issue #2417)

---

packages/composer-common/lib/query/queryanalyzer.js
packages/composer-common/test/query/queryanalyzer.js

Fix the query analyser to return the correct structure for the CONTAINS operator.
1.
2.
3.
4.

change query analyser to return array of parameters for CONTAINS

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/test/identity/request.js

Admin connection already knows about the card that is use; therefore use this when starting the network.
Resolves #2700

Issue #2700 start install

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/idcard.js

Contributes to #2523 
Required so it can be used by end-user tests of their business networks.

Make IdCard.constructor public

---

packages/composer-connector-hlfv1/package.json

1.7.1 causes a sigsegv in the docker container

regress grpc to 1.6.6

---

packages/composer-tests-functional/package.json

closes #2756 
Update of package information name within composer-tests-functional, so that it is correctly skipped in the travis deploy.sh (line 91 in that file)

update fv-test package name to prevent publishing

---

packages/composer-common/lib/codegen/javascriptparser.js
packages/composer-common/test/codegen/javascriptparser.js
packages/composer-runtime-hlfv1/composer.go

High memory usage and leak from Composer runtime #2758
Stop collecting and storing tokens for any JavaScript files that are loaded as part of a business network definition in the HLFv1 runtime. This saves a significant amount of memory for a BNA that contains a lot of JavaScript code.

Do not collect JavaScript tokens in HLFv1 runtime

---

.gitmodules
.travis/before-install.sh

High memory usage and leak from Composer runtime #2758 
Use fixed `go-duktape` that fixes:
- Duktape stack leak caused by a bug in the setTimeout code in `go-duktape`.
- Duktape memory leak caused by context tracking code in `go-duktape`, that we are exacerbating by regularly binding new Go functions to JavaScript.
Ensure the build uses the right version of `go-duktape` by adding a check for the correct Git submodule remote URL - whenever we change this, it tends to result in people undoing the change due to merge failures.
Finally, remove broken git diff code that blows up my personal Travis builds - it does nothing useful anyway.

Use fixed version of go-duktape

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-runtime-hlfv1/composer.go
packages/composer-runtime-hlfv1/constants.go

High memory usage and leak from Composer runtime #2758
Force Duktape to perform garbage collections at regular intervals to keep memory utilisation low. Set the default garbage collection interval to 5 seconds, but allow users to override it by specifying `-o gcInterval=30` (an example for setting it to 30 seconds).
Possible/likely performance degradation owing to garbage collection pauses, but the memory saving for a reasonable BNA file this is well worthwhile. Anybody that objects to the performance degradation can override the garbage collection interval as per the instructions above.

Force garbage collection at regular intervals

---

.travis.yml
.travis/before-install.sh
.travis/deploy.sh
.travis/script.sh
packages/composer-tests-functional/scripts/run-system-tests.sh
packages/composer-tests-functional/systest/accesscontrols.js
packages/composer-tests-functional/systest/assets.js
packages/composer-tests-functional/systest/events.js
packages/composer-tests-functional/systest/historian.js
packages/composer-tests-functional/systest/identities.js
packages/composer-tests-functional/systest/participants.js
packages/composer-tests-functional/systest/post.js
packages/composer-tests-functional/systest/queries.js
packages/composer-tests-functional/systest/testutil.js
packages/composer-tests-functional/systest/transactions.assets.js
packages/composer-tests-functional/systest/transactions.js
packages/composer-tests-functional/systest/transactions.participants.js
packages/composer-tests-functional/systest/transactions.queries.js

closes #2760 
Adds a retry option to the fv tests that are proving unreliable
Changes the SYSTEST flag to FVTEST, because those items are FVTESTS

add retries option to fv-tests  and change travis systest flag to fvtest

---

packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/test/accesscontroller.js

closes #2768
- within matchPredicate, check if the condition passed in is true/false and return a Promise.resolve(true/false), otherwise continue with original code execution
- new tests to check that ACL rules are not executed for the true/false cases
- updating of old tests to retain ACL rule execution

ACL Rules: return immediately if simple boolean condition specified in operation

---

packages/composer-common/lib/factory.js
packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/lib/model/concept.js
packages/composer-common/lib/model/identifiable.js
packages/composer-common/lib/model/relationship.js
packages/composer-common/lib/model/resource.js
packages/composer-common/lib/model/typed.js
packages/composer-common/lib/model/validatedconcept.js
packages/composer-common/lib/model/validatedresource.js
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/modelfile.js
packages/composer-common/test/model/concept.js
packages/composer-common/test/model/identifiable.js
packages/composer-common/test/model/relationship.js
packages/composer-common/test/model/resource.js
packages/composer-common/test/model/typed.js
packages/composer-common/test/model/validatedconcept.js
packages/composer-common/test/modelutil.js
packages/composer-runtime/lib/callbackrelationship.js
packages/composer-runtime/lib/invalidrelationship.js
packages/composer-runtime/test/callbackrelationship.js
packages/composer-runtime/test/invalidrelationship.js

ACL rule execution is inefficient #2576 
Class declaration look up for a given `Typed` object is expensive and pointless; the class declaration is always held in memory by the model manager, and we have to look it up before we can create the `Typed` object anyway. Let's pass it in and store a reference to it!

Cache class declaration in resources

---

packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/lib/model/typed.js
packages/composer-common/test/codegen/loopbackvisitor.js
packages/composer-common/test/introspect/assetdeclaration.js
packages/composer-common/test/introspect/modelfile.js
packages/composer-common/test/introspect/participantdeclaration.js
packages/composer-runtime/lib/accesscontroller.js

ACL rule execution is inefficient #2576 
Super type declaration lookup is not cached, which means we look it up every time we execute an ACL rule. This also slows down the `instanceOf` check, so lets improve those things.

Improve super type declaration and instanceOf lookup

---

packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/identitymanager.js
packages/composer-runtime/test/identitymanager.js

Contributes to #2576
- engine.queries was serialising and deserialising the same thing, we can  pass the original instead
- identitymanager was also inefficient, we can speed it up by doing a get and dealing with an exception if it is thrown due to not being there
- no test fixes for engine.queries required, test fixes for identitymanager due to the change in `.get()`

reduce parsing and getters

---

packages/composer-admin/lib/adminconnection.js
packages/composer-cli/lib/cmds/archive/createCommand.js
packages/composer-cli/lib/cmds/card/createCommand.js
packages/composer-cli/lib/cmds/card/deleteCommand.js
packages/composer-cli/lib/cmds/identity/issueCommand.js
packages/composer-cli/lib/cmds/network/deployCommand.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/participant/addCommand.js
packages/composer-cli/lib/cmds/utils/cmdutils.js
packages/composer-cli/test/archive/archive.js
packages/composer-cli/test/card/card.js
packages/composer-cli/test/identity/identity.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/network/network.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/utils/cmdutils.js
packages/composer-tests-integration/features/cli.feature

Undo all of the CLI changes that have been introduced for network admins:
- New magic `networkAdmin.*` options are not documented ANYWHERE, even in the command line help available with `-h`, and the documented options do NOT work.
- Code for those options mixes up `cert` and `certificate` and I'm pretty sure it's broken with regards to the list of options that _should_ work as per #2753.
- Documentation, including the developer tutorial, has not been updated to reflect the renamed `--networkAdminSecret` flag.
- Random `yarg.groups` have snuck in for SOME of the commands, but not ALL.

Undo all of the CLI changes for network admins

---

packages/composer-website/jekylldocs/_data/links.yml
packages/composer-website/jekylldocs/index.html
packages/composer-website/jekylldocs/installing/getting-started-with-playground.md
packages/composer-website/jekylldocs/tutorials/playground-tutorial.md

Closes #2852 - allows us to swap the URL of the version of Playground we point at (e.g. for 0.16 and 0.17 streams) via a config file.
Signed-off-by: E. P. Moffatt <edmoffat@uk.ibm.com>

Replace playground link with a variable

---

packages/composer-playground/src/app/editor/editor-file/editor-file.component.ts
packages/composer-playground/src/app/services/file.service.spec.ts
packages/composer-playground/src/app/services/file.service.ts

Fix to add validation to update file after its removal setCurrentCode by PR #2831. This prevents updateBusinessNetwork being used as the validation.

Fix to move validation for non model files to updateFile

---

packages/composer-tests-functional/scripts/run-fv-tests.sh
packages/composer-tests-integration/scripts/run-integration-tests.sh

Looking up the host ip address using docker inspect is not working on Mac OSX which causes the integration and functional tests to fail locally.
This PR resolves this by extracting the IP from the output of ifconfig (for mac platform only)
1.
2.
3.
4.

find host ip using ifconfig on mac

---

packages/composer-playground/src/assets/styles/elements/_header.scss

Removed line height for header links to allow for the header to change height in future.
#2933

Removed unnecessary line height for header link CSS (Issue 2933)

---

.travis.yml
.travis/deploy.sh

v0.16.x wasn't deploying the modules
- Move to use two travis deploy providers and lock them to the v0.16.x and the master branches
- Remove branch check from the deploy.sh script.
resolves #2976

Move to use travis providers to control the branches

---

.travis/deploy.sh

Pushing a local copy of playground to me own cf space, showed that the web-cfg had extra ' that meant it was not valid JSON
Removed.
Part resolves #3003

Quotes still persisted around web-cfg

---

packages/composer-cli/cli.js
packages/composer-cli/lib/cmds/card/lib/list.js
packages/composer-cli/lib/cmds/card/listCommand.js
packages/composer-cli/test/card/list.js

Add quiet option for command `card list`. When this flag is passed the command will return all the card's names, one for each line.
It fixes #3026
Some thoughts:
- When `--quiet` is passed alongside `-n` then quiet is ignored, since the output would be the same as the input `-n`. So, `composer card list -n card@name -q` is the same as  `composer card list -n card@name`. I have not added any information about this since it seems obvious and it would just pollute the help instructions..
- "Command succeeded" now is not printed if the argument `--quiet` is provided.  "Command failed" is still printed in all situations in case of error.

Add quiet option to 'composer card list'

---

packages/composer-website/README.md

One important typo (jekyllserve), and other less important typos.
Signed-off-by: Nathan Hazout <nathanh@il.ibm.com>

Typos in readme

---

packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/composer-common/test/codegen/loopbackvisitor.js
packages/composer-common/test/codegen/loopbackvisitorcircular.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/test/data/bond-network/models/bond.cto
packages/composer-rest-server/test/server/boot/composer-discovery.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Type missing from Swagger leading to bad Java client gen #1055
We currently hide all abstract types from LoopBack, which means that the Swagger document produced by LoopBack is invalid.
Any reference to an abstract type from a concrete type results in Swagger document errors where the concrete type definition has a `$ref` to the abstract type definition which cannot be resolved. Any compliant Swagger parser will choke on this.

Give LoopBack all abstract types without exposing their remote methods (v0.16.x)

---

packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/composer-common/test/codegen/loopbackvisitor.js
packages/composer-common/test/codegen/loopbackvisitorcircular.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/test/data/bond-network/models/bond.cto
packages/composer-rest-server/test/server/boot/composer-discovery.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Type missing from Swagger leading to bad Java client gen #1055
We currently hide all abstract types from LoopBack, which means that the Swagger document produced by LoopBack is invalid.
Any reference to an abstract type from a concrete type results in Swagger document errors where the concrete type definition has a `$ref` to the abstract type definition which cannot be resolved. Any compliant Swagger parser will choke on this.

Give LoopBack all abstract types without exposing their remote methods (v0.17.x)

---

packages/composer-website/jekylldocs/reference/composer.card.list.md

Update the documentation to include the new option `--quiet` for `composer card list`.
Option added in #3075

Update reference documentation for 'card list'

---

packages/composer-runtime/lib/identitymanager.js
packages/composer-runtime/test/identitymanager.js
packages/composer-tests-functional/systest/identities.js

Error message for unrecognized identities needs more information #3095
1.
2.
3.
4.

Add identifier for identity into error messages (resolves #3095, v0.16.x)

---

packages/composer-runtime/lib/identitymanager.js
packages/composer-runtime/test/identitymanager.js
packages/composer-tests-functional/systest/identities.js
packages/composer-tests-integration/features/cli.feature

Error message for unrecognized identities needs more information #3095
1.
2.
3.
4.

Add identifier for identity into error messages (resolves #3095, v0.17.x)

---

packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/lib/hooks.js

This PR closes #3027 
Two methods are introduced and the existing feature file modified to use the new methods:
- enable the saving off of a regex group match into an alias map
- enable the substitution of an alias prior to running a CLI command

add alias map to cucumber tests

---

packages/composer-website/jekylldocs/tutorials/developer-tutorial.md

On line 29, "{{site.data.conrefs.composer}}" should get replaced with "Composer" when visiting the docs on github.io, but instead there's a blank space.
Changing to 'composer_full' should fix this by displaying "Hyperledger Composer" instead.
Signed-off-by: Kartik Shah <krtk.6160@gmail.com>

Changed 'composer' to 'composer_full'

---

packages/composer-website/jekylldocs/_data/links.yml

Contributes to #3159
Change 
0.17.x tutorials/playground-tutorial link 'Composer Playground' to point to:  http://composer-playground-next.mybluemix.net/login

Next doc links should point to playground for 0.17.x (#3159)

---

packages/composer-cli/lib/cmds/report.js
packages/composer-cli/lib/cmds/report/lib/report.js
packages/composer-cli/lib/cmds/report/reportCommand.js
packages/composer-cli/package.json
packages/composer-cli/test/report/report.js
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.report.md

Simple command to collect node report data and create a composer
report archive file. Provides basic implementation to add further
data collection to in the future
Contributes to #3051

Initial composer report command

---

packages/composer-cli/cli.js
packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/test/archive/create.js
packages/composer-cli/test/archive/list.js
packages/composer-cli/test/cli.js
packages/composer-cli/test/generator/createCode.js
packages/composer-cli/test/identity/issue.js
packages/composer-cli/test/index.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/network/download.js
packages/composer-cli/test/network/list.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/network/undeploy.js
packages/composer-cli/test/network/update.js
packages/composer-cli/test/network/upgrade.js
packages/composer-cli/test/report/report.js
packages/composer-cli/test/runtime/install.js

- Stubbed out the file system to prevent cards being written to disk
- Added some tests to increase the coverage
- Did alter the network use of spinner to simplify the code and make it testable.

Corrections to test code for the composer-cli

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-tests-functional/systest/assets.js
packages/composer-tests-functional/systest/participants.js

The generic `getRegistry` api can be useful. 
Esp if you are loading in assets say from a JSON file. 
resolves issue #2937

Correct the creation of the registries if accessed via ''getRegistry"

---

packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.network.deploy.md

Discourage users from using `composer network deploy`.
Encourage `composer network install` and `composer network start`

iss2952 change network deploy to network start

---

packages/composer-tests-integration/README.md
packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/scripts/run-integration-tests.sh

issue 3305 add report into integration tests
Added basic report capability into integration tests to make sure that it works. 
No checking of .tgz file contents since there's only node-report content in there at the moment which isn't in our control. Also no checking of messages from node-report (which seem to be issued to stderr for some reason).

issue 3305 add report into integration tests

---

packages/composer-tests-functional/systest/transactions.native.js

Added randomNumber to the asset id when doing the history of asset test to stop the test failing if retries are used
contributes to https://github.com/hyperledger/composer/issues/3333

Fix fabric shim systests

---

packages/composer-website/jekylldocs/tutorials/tutorials.md

ACL tutorial was missing a '{' on the con-refs, and a link to the tutorial under the description

fix con-ref link in docs

---

packages/composer-cli/.eslintrc.yml
packages/composer-cli/lib/cmds/network/lib/ping.js
packages/composer-cli/test/network/ping.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/test/system.js
packages/composer-runtime/.eslintrc.yml
packages/composer-runtime/lib/api.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/test/api.js
packages/composer-runtime/test/engine.js
packages/composer-tests-functional/systest/data/accesscontrols.js
packages/composer-tests-functional/systest/data/identities.cto
packages/composer-tests-functional/systest/data/identities.js
packages/composer-tests-functional/systest/identities.js
packages/composer-tests-functional/systest/testutil.js
packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/features/queries.feature
packages/composer-tests-integration/features/rest.feature
packages/composer-website/jekylldocs/business-network/programmatic-access-control.md

Need ability to get an Identity's public key #2850
Add the function `getCurrentIdentity` to the runtime API, which can be called by a transaction processor function to return the current identity. This function returns an instance of `org.hyperledger.composer.system.Identity`, which provides the `certificate` field.
Expose the current identity through the ping response as well, which means it will show up via the JavaScript API (`BusinessNetworkConnection.ping`), the REST API (`/api/system/ping`), and the CLI (`composer network ping`).

Add getCurrentIdentity to runtime API and ping response (resolves #2850)

---

packages/composer-playground/src/app/test/test.component.spec.ts
packages/composer-playground/src/app/test/test.component.ts

Fix for #3274 .
Added a catch block to handle a previously uncaught error that occurred when cancelling a transaction in Playground.
Included tests to cover this, and also added a test for an uncovered branch of code in the same class.
Signed-off-by: Erin Hughes <erinhughes@erins-mbp.hursley.uk.ibm.com>

Handling an uncaught Playground error when cancelling a transaction

---

packages/composer-tests-integration/README.md
packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/features/generator-busnet.feature
packages/composer-tests-integration/features/queries.feature
packages/composer-tests-integration/features/rest.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/package.json
packages/composer-tests-integration/scripts/npm_serve.js
packages/composer-tests-integration/scripts/run-integration-tests.sh
packages/generator-hyperledger-composer/generators/businessnetwork/index.js
packages/generator-hyperledger-composer/package.json
packages/generator-hyperledger-composer/test/business-network.js

contributes to #3385 and closes #3306
It was necessary to change the generator to enable passing of parameters through as command line options ... which itself pulled in a new dependancy
Following this change it was possible to add integration tests to drive the new generator, within which we programatically:
- generate bus net over cli
- install busnet
- run busnet tests
- deploy busnet to Fabric
- create assets in deployed bus net
- run sample transaction to update asset
- check the above have occurred correctly through inspection of console output

modify generator to enable options to be passed and add integration tests

---

packages/composer-common/package.json

Cannot find module sha.js when loading composer-common #3416
Add missing `sha.js` dependency to `package.json` for the `composer-common` module.

Add missing sha.js dependency (resolves #3416)

---

packages/composer-cli/lib/cmds/card/lib/delete.js
packages/composer-cli/package.json
packages/composer-cli/test/card/delete.js
packages/composer-cli/test/card/list.js
packages/composer-cli/test/identity/request.js
packages/composer-common/lib/cardstore/filesystemcardstore.js
packages/composer-common/lib/idcard.js
packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/reststeps.js

- address some test debt for HSM
- ensure we keep 100% on cli by setting the required values to 100
- address card save error messages which are lacking in info
- address not found in card delete reported as a success
closes #2983 
closes #2835 

Address and Set CLI unit tests to 100% coverage

---

packages/composer-playground/src/app/test/registry/registry.component.spec.ts
packages/composer-playground/src/app/test/registry/registry.component.ts

Fix for #3422.
Handles previously uncaught errors when cancelling add or edit operations on participants or assets. I also found some uncaught errors when cancelling the deletion of a participant or asset, and fixed those as well.
Signed-off-by: Erin Hughes <erinhughes@erins-mbp.hursley.uk.ibm.com>

Handling various uncaught errors when cancelling modals

---

packages/composer-connector-hlfv1/package.json

Update composer-connector-hlfv1 package.json to update fabric-client and fabric-ca-client from 1.0.3 to 1.0.4
Closes #3473 

update fabric-client and fabric-ca-client version

---

packages/composer-connector-server/lib/connectorserver.js

Connector Server didn't correctly use the 'local' wallet and instead tried to use the proxy one passed from Playground.

correct usage of wallet in connector remove identity

---

packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
packages/composer-playground/src/app/editor/editor-files.pipe.spec.ts
packages/composer-playground/src/app/editor/editor-files.pipe.ts
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/editor/editor.module.ts
packages/composer-playground/src/app/services/file.service.spec.ts
packages/composer-playground/src/app/services/file.service.ts
packages/composer-playground/tslint.json

Validation errors on the package.json file are now more obvious in
the playground, which is now edited via a 'settings' icon on the
About file
Note: json syntax errors are not currently picked up in the editor
validation so error markers are still not visible in that case
Required for #3241

Improve playground package.json editing

---

packages/composer-website/jekylldocs/reference/cto_language.md

There were a few "broken" code areas that made unable to clearly read the docs. Fixed that.

Update docs on CTO modeling language

---

packages/composer-tests-integration/features/generator-busnet.feature
packages/composer-tests-integration/package.json
packages/composer-tests-integration/scripts/npm_serve.js
packages/composer-tests-integration/scripts/run-integration-tests.sh

closes #3612 
- Use `| tee in` script
- modify busnet gen tests that should have failed build
- prevent running of report generator test that is currently failing

swap to tee and modify busnet gen tests

---

packages/composer-common/lib/system/org.hyperledger.composer.system.cto
packages/composer-runtime/lib/engine.js
packages/composer-runtime/package.json
packages/composer-runtime/test/engine.js
packages/composer-tests-functional/package.json

1. init should not be driven by a function name
2. semver checking needs to be done by upgrade
3. upgrade needed to drive transaction calls
4. unit tests for upgrade

Fix upgrade

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

node-sdk returns an error in the payload if connect fails and was not always been recognised as such

address node-sdk returning connect error

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/index.js
packages/composer-common/lib/indexcompiler.js
packages/composer-common/test/indexcompiler.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/package.json
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-runtime/lib/querycompiler.js
packages/composer-runtime/test/querycompiler.js

Move couchdb index generator to composer-common.
This allows composer-connector-hlfv1 to remove its dependency on composer-runtime
1.
2.
3.
4.

Move couchdb index generator to composer-common 

---

packages/composer-playground-api/.gitignore
packages/composer-playground-api/package.json
packages/composer-playground-api/scripts/config.yaml
packages/composer-playground-api/scripts/start.sh

Added scripts/start.sh to handle start/stop and configuration of Verdaccio.
This can be used instead of `npm start`.
Contributes to #3160

Stand up Verdaccio for local testing of composer-playground-api

---

packages/composer-cli/package.json
packages/composer-playground-api/package.json
packages/composer-report/package.json

Fix the version of tar that composer report cli command requires in the package.json for the composer-report module
Resolves #3614 

Fix version of tar that composer report cli command requires

---

packages/composer-common/.gitignore
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-runtime-hlfv1/.gitignore
packages/composer-runtime/.gitignore
packages/composer-tests-functional/systest/events.js

Can not listen to events if a transaction has not been submitted before #3669
1.
2.
3.
4.

Register for events on connection login, not first invoke

---

packages/composer-cli/cli.js

The command `composer` when invoked with no args returns help text with some examples.  One example is `composer network deploy`, which is no longer relevant.
This PR replaces this with `composer network install`
1.
2.
3.
4.

change composer cli example to one that works

---

packages/composer-website/jekylldocs/applications/web.md
packages/composer-website/jekylldocs/business-network/cloud-wallets.md
packages/composer-website/jekylldocs/managing/identity-list.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/js_scripts.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md
packages/composer-website/jekylldocs/tutorials/tutorials.md

- identity list excerpt was wrong it was a copy of identity issue
- the tutorial count was wrong
- ACL bypassing needs to be highlighted more as it is a very important consideration
- redis cloud wallet not pointing to the correct npm module
- single org step 7 description incorrect
- outh2 tutorlal formatting was a mismatch of formatted and non formatted examples
- multi-org step 11,12 titles and description incorrect

Further doc fixes

---

packages/composer-tests-integration/features/cli-network.feature

New integration tests to improve coverage of `composer network` sub-commands:
- `composer network download`
- `composer network reset`
1.
2.
3.
4.

added network download & network reset to cli integration tests

---

packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/lib/introspect/eventdeclaration.js
packages/composer-common/lib/introspect/transactiondeclaration.js
packages/composer-common/test/data/parser/classdeclaration.classoverridesidentifier.cto
packages/composer-common/test/data/parser/transactiondeclaration.definesidentifier.cto
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/introspectutils.js
packages/composer-common/test/introspect/transactiondeclaration.js

This improves the error message when you try to redeclare and identifier field
Also ensures that you get the transaction specific error rather than the generic class error
Provides a commented out block of code for more validation which is awaiting feedback and a major version bump.
closes #2973

Improve model validation

---

packages/composer-runtime/lib/querycompiler.js
packages/composer-runtime/test/querycompiler.js

The implementation of the combination operator in the query compiler has evolved in response to various past issues.  Now is a good time to revisit the underlying algorithm and re-implement the logic.  This also resolves #3771 
1.
2.
3.
4.

rewrite and fix query generator for combination operator

---

packages/generator-hyperledger-composer/generators/angular/index.js
packages/generator-hyperledger-composer/generators/angular/templates/proxy.conf.js
packages/generator-hyperledger-composer/test/angular-archive.js
packages/generator-hyperledger-composer/test/angular-network.js

https://github.com/hyperledger/composer/issues/3802
Allow proxy configuration to accept an override for the REST server URL in two environments:
This went in the first drop - a single URL override.
Example:
```
export REST_SERVER_URL=https://dogecorp.com:3000
```
This is new in this PR - a JSON string containing business network name to URL mappings for multiple business networks - useful for generic deployment scripts. The application knows which business network that it should look for.
Example: 
```
export REST_SERVER_URLS='{
"basic-sample-network": "https://basic-sample-network.dogecorp.com",
"vehicle-manufacture-network": "https://vehicle-manufacture-network.simoncorp.com"
}'
```

Enable generated app to accept REST server URLs for multiple business networks

---

.github/stale.yml

extends stale bot exemptions to include more tags.
Closes #3921

extend exemptions

---

packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

Fixes #3911 
Changes login component to select the peer admin card for the connection profile selected rather than using the last used card if that contains the capability.

Fix for issue 3911

---

packages/composer-website/jekylldocs/search/search.html

Fixes #2863 
Removed extra slash in links from search results to ensure that navbar is updated when using them to navigate

Removing extra slash in search result links (Issue 2863)

---

packages/composer-tests-integration/features/cli-cards.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/composer.js

closes #3029 
Adds the ability to:
- Check a block of text (strict check)
Refactors existing check text to be a soft check (strips multiple white space) and adds new method for a strict console line check. This was because of issues relating to version changes adding/removing whitespace.

add ability to check blocks of text and strict line checking

---

packages/composer-tests-integration/features/cli-report.feature
packages/composer-tests-integration/package.json

Also adds a 'bad' command test
Contributes to 3787

Reinstate composer report tests

---

packages/composer-tests-integration/features/cli-cards.feature
packages/composer-tests-integration/features/cli-cards.redis.feature
packages/composer-tests-integration/lib/composer.js

Testing exact output of `composer card list` is too brittle. Also
updates redis card test to check if the card really did end up in
redis
Fixed while working on #3787

Improve card integration tests

---

packages/composer-runtime-embedded/package.json
packages/composer-wallet-filesystem/package.json
packages/composer-wallet-inmemory/package.json
scripts/depcheck.js
scripts/pkgcheck.js
scripts/pkgstamp.js

Adding peer dependencies to the package check scripts.
Behaviour is exactly the same as for the other dependencies.

update the package version scripts to include the peerDependencies

---

packages/composer-website/jekylldocs/installing/development-tools.md

Signed-off-by: rthatcher <robert.thatcher@uk.ibm.com>
Added 1 line warning not to use sudo
Too many users still using sudo or su when installing composer, so a reminder added nearer to the npm commands

Added 1 line warning not to use sudo

---

packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/test/connectionprofilemanager.js
packages/composer-connector-embedded/lib/embeddedconnectionmanager.js
packages/composer-connector-embedded/test/embeddedconnectionmanager.js
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-tests-integration/features/cli-cards.feature
packages/composer-tests-integration/scripts/run-integration-tests.sh

Also fix issue with embedded connector where re-imported identity loses issuer authority.

Playground support for connection delegation

---

packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/test/nodedataservice.js
packages/composer-runtime-pouchdb/lib/pouchdbdataservice.js
packages/composer-runtime-pouchdb/test/pouchdbdataservice.js
packages/composer-runtime/lib/dataservice.js
packages/composer-runtime/lib/registrymanager.js
packages/composer-runtime/test/registrymanager.js

Closes #4026 
RegistryManager
- add method to determine if a Composer generated type
- if a Composer generated type and not being called by an 'ensure' method, then use a factory to generate the Asset in order to perform an ACL check, retrieve dataCollection using a 'bypass' flag. Cache the resulting Asset (registry)
- if either non-composer, or being called by an `ensure` method, follow the previous route and perform explicit `get` operations on the sysregistry and dataCollection.
DataService
- add flag to `getCollection` to enable optional bypass of explicit `get` for known types
PR comes complete with enhanced unit tests 👍

prevent calling get() and cache resources (#4003)

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js

closes #4040
Moved the inspection of the peer responses to within a catch block. Also renamed the internal method `_sendTransactionForProposal` to `_sendTransaction` to better represent the code action.

move response compare to within catch block

---

.travis/deploy.sh

Closes #3986 
- Check for any existing npm modules before publishing, and during publish phase use an augmented list of 'ignore items'
- Check for any existing docker images that already exist, and only publish those that do not already exist. Completely skip publish phase if all docker images exist.
Intentionally left the Playground conditionality out- we can spin the script to the point where playground is published, and a version bump is a trivial manual process that can be performed by anyone.

enable smart publishing of npm and docker items during release build

---

.travis/deploy.sh

closes #4102 
It seems that the test config didn't match the actual build config and the Docker images are no longer being published. 
This change swaps to:
- using 2 arrays for the docker images
- Traversing one array to check for existence and modifying the second based on a return result
Did someone say 🐧 ?

swap to arrays for Docker publish in build script

---

packages/composer-common/lib/cardstore/walletbackedcardstore.js

Signed-off-by: Matt Roberts <matt@clause.io>
Changed cardstore/walletbackedcardstore.js to use more specific lodash.clonedeep package which does exist as a dependency of the composer-common package.
https://github.com/hyperledger/composer/issues/4108
Changed the clonedeep calls to use the narrower package `lodash.clonedeep` rather than adding `lodash` back as a package dependency.

Change lodash dependency to lodash.clonedeep

---

.travis/deploy.sh

There was a recent build failure due to an npm module not being able to find a composer dependancy.
This PR extends the DOCKER_NPM_MODULES list that is checked before proceeding to include the first layer of module dependancies for each main package required

extend docker npm deps to include module composer deps

---

packages/composer-common/lib/introspect/loaders/jobqueue.js

When a ModelFileLoader downloads multiple files, processing the JobQueue introduces a pause of roughly 10 seconds. When using the composer-common dependency in a short-lived node app, such as Cicero CLI, this behaviour is exposed as a 'hang' before the process exits. See: accordproject/cicero#119
Fixes https://github.com/hyperledger/composer/issues/4116
See https://github.com/hyperledger/composer/issues/4116
The value of the timeout can be debated. Also, ideally we would avoid polling altogether but not clear how to do this.

Reduce jobQueue polling to 500ms

---

packages/composer-common/lib/idcard.js
packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/lib/proxyconnectionmanager.js
packages/composer-connector-proxy/package.json
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnectionmanager.js
packages/composer-connector-server/package.json
packages/composer-playground-api/scripts/devStart.sh
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-wallet-filesystem/package.json
packages/composer-wallet-inmemory/package.json
packages/generator-hyperledger-composer/generators/angular/index.js

The proxy connector creates a single socket to the proxy server shared by all connections. However it never closed that socket which was ok for playground but not much good for anything else.
closes #4097

Support socket closure

---

packages/composer-runtime/lib/registry.js
packages/composer-runtime/test/registry.js

closes #4076 by introduction of a registry cache within the transaction. Basic rules of the cache:
1) Nobody talks about the cache
2) If required item is not in the cache, a lookup is performed to retrieve, and it is put into the cache
3) If an item is in the cache, that item is used
4) If an item is removed from the data collection, it is removed from the cache
5) If an item is updated in the data collection, it is removed from the cache

introduce registry cache to prevent unnecessary lookups

---

packages/composer-tests-integration/features/cli-network.feature
packages/composer-tests-integration/resources/sample-networks/marbles-network-update/lib/logic.js

When looking into the busnet integration tests, it was observed that the tests never actually run a defined business network transaction. We should do this.
This PR:
- Runs a transaction that is defined in busnet-version1
- Performs the upgrade to v2
- Adds assets, participants and runs a transaction that is defined in busnet-v2

add transaction run into bus-net tests

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/utils/cmdutils.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/utils/cmdutils.js
packages/composer-website/jekylldocs/reference/composer.network.start.md

Resolves #4044 
Ensures that, when the network is started using network admin
certificates instead of enrollment secrets, the network admin
card(s) produced can actually be imported and used.
The `networkAdminPrivateKeyFile` option is optional, so the CLI
can still be used in an identical manner to before this change.

Add networkAdminPrivateKeyFile option to `composer network start`

---

packages/composer-runtime/lib/registry.js
packages/composer-runtime/test/registry.js

closes #4183 
- store the object in the cache
- perform a serialisation on the object when returning
- update tests

prevent passing cache contents by reference

---

packages/composer-tests-integration/features/generator-angular.feature
packages/generator-hyperledger-composer/generators/angular/index.js
packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.html
packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.spec.ts
packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.ts
packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.html
packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.spec.ts
packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.ts

Signed-off-by: Erin Hughes <Erin.Hughes@ibm.com>
Removed the manual refresh and added a call for the list of assets/participants whenever something is updated, so that the table refreshes automatically.
Also added tests to cover this change.

Fix for manual refresh when assets/participants are edited

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/lib/introspect/decorated.js
packages/composer-common/lib/introspect/decorator.js
packages/composer-common/lib/introspect/decoratorfactory.js
packages/composer-common/lib/introspect/parser.pegjs
packages/composer-common/lib/introspect/property.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/test/composer/i18n.js
packages/composer-common/test/data/decorators/model.cto
packages/composer-common/test/introspect/assetdeclaration.js
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/decorated.js
packages/composer-common/test/introspect/decoratorfactory.js
packages/composer-common/test/introspect/decorators.js
packages/composer-common/test/introspect/eventdeclaration.js
packages/composer-common/test/introspect/field.js
packages/composer-common/test/introspect/participantdeclaration.js
packages/composer-common/test/introspect/property.js
packages/composer-common/test/modelmanager.js
packages/composer-playground/src/app/test/resource/resource.component.ts

https://github.com/hyperledger/composer/issues/4165
Allow a decorator to accept a type (identifier), so that you can do nice things like:
```
@returns(org.acme.Foo[])
transaction MyTransaction { }
```
Allow a model manager to be given a set of decorator factories, which can be optionally added to create a specialised decorator (a subclass of Decorator) to add additional functionality or validation.
For example, we can add a decorator processor for `@returns` to the Composer runtime, that ensures only one argument is passed and that one argument is a reference to a valid type - without adding that constraint for all users of the Composer modelling language.

Allow decorators to accept types, add decorator factory

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/introspect/modelfile.js
packages/composer-common/lib/returnsdecorator.js
packages/composer-common/lib/returnsdecoratorfactory.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/returnsdecorator.js
packages/composer-common/test/returnsdecoratorfactory.js

#4165 
Add a decorator implementation and decorator factory for handling `@returns` decorators.
Allows the following decorators to be validated by Composer:
```
concept MyConcept { }
@returns(MyConcept)
transaction MyTransaction { }
```
```
enum MyEnum {
o VALUE_1
o VALUE_2
o VALUE_3
o VALUE_4
}
@returns(MyEnum)
transaction MyTransaction { }
```
```
@returns(String)
transaction MyTransaction { }
```

Add decorator factory and implementation for @returns

---

packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js

#4165 
All connectors (embedded, web, proxy, hlfv1) and the connector server need to be extended to support returning data from a chaincode invoke as well as a chaincode query.

Extend connectors to return values from chaincode invoke

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/index.js
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/commitdecorator.js
packages/composer-common/lib/commitdecoratorfactory.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/commitdecorator.js
packages/composer-common/test/commitdecoratorfactory.js

#4224
Add a decorator implementation and decorator factory for handling @commit decorators.
Allows the following decorators to be validated by Composer:
```
@commit(true)
transaction TransactionWithCommitTrue {
o String stringValue
}
@commit(false)
transaction TransactionWithCommitFalse {
o String stringValue
}
```

Add decorator factory and implementation for @commit

---

packages/composer-common/lib/introspect/modelfile.js
packages/composer-common/lib/model/resourceid.js
packages/composer-common/package.json
packages/composer-common/test/model/relationship.js

Changing to a different standard npm module (npmjs instead of npm-js) gives us a 6% throughput boost for free 👍  (Well, according to 100k hits on the `fromJSON()` method it does )
try catch required as this module likes to throw instead of 'do it's best' ... which might be why it's faster 🤷‍♂️ 
Now includes a map in the model file to hold local types, which helps yield a 13% perf boost

speed up `fromJSON()` serialisation process

---

packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js
packages/composer-runtime-embedded/lib/embeddedcontext.js
packages/composer-runtime-embedded/lib/embeddeddataservice.js
packages/composer-runtime-embedded/test/embeddeddataservice.js
packages/composer-runtime-pouchdb/lib/pouchdbdataservice.js
packages/composer-runtime-pouchdb/test/pouchdbdataservice.js
packages/composer-runtime-web/lib/webcontext.js
packages/composer-runtime-web/lib/webdataservice.js
packages/composer-runtime-web/test/webdataservice.js

#4224 
All connectors (embedded, web, hlfv1) need to be extended not to commit when the commit option is specified and the value is false. In addition to this, the PouchDB runtime (used by the embedded and web runtimes) needs to be updated to handle this, because commit is done there rather than on the client side as it is with hlfv1.

Extend connectors and embedded/web runtime to support commit flag

---

packages/composer-client/api.txt
packages/composer-client/changelog.txt
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/util.js
packages/composer-common/test/util.js
packages/composer-tests-functional/systest/data/transactions.cto
packages/composer-tests-functional/systest/data/transactions.js
packages/composer-tests-functional/systest/transactions.js

#4224 
Provide client implementation for commit flag - either picking up on the `@commit` decorator for a transaction, or via extended API for `submitTransaction`, and add functional tests to ensure that it works as designed.

Client implementation for commit flag, add functional tests

---

packages/composer-runtime/lib/api.js

Due to the variable naming in the first example, the code could not actually be executed (an error saying that `query is not a function` would occur).
The second example could also be clarified by including an actual query that takes a variable to make the rest of the code in the example make more sense.
Thank you!

Fix query examples in documentation

---

packages/composer-cli/lib/cmds/transaction/lib/submit.js
packages/composer-cli/test/transaction/submit.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/test/engine.transactions.js
packages/composer-tests-integration/features/cli-network.feature
packages/composer-tests-integration/features/cli-other-networks.feature
packages/composer-tests-integration/resources/sample-networks/marbles-network-update/lib/logic.js
packages/composer-tests-integration/resources/sample-networks/marbles-network-update/models/marbles.cto
packages/composer-tests-integration/resources/sample-networks/marbles-network/lib/logic.js
packages/composer-tests-integration/resources/sample-networks/marbles-network/models/marbles.cto
packages/composer-tests-integration/scripts/run-integration-tests.sh

#4165, #4224 
- Extend the CLI command `composer transaction submit` so that it prints any return values (#4165)
- HLFv1 connector should defer to `queryChainCode` when `invokeChainCode` called with commit set to false, to avoid sending endorsements to multiple peers (#4224)
- Runtime should serialize resources as relationships where appropriate, to avoid sending back invalid data (#4165)
- Add integration tests that demonstrate return values working by returning a trade receipt from a marble trade, and checking the output of the CLI command above (#4165)
- Add integration tests that demonstrate read-only transaction processor functions by calling a transaction processor function that reads marbles from multiple business networks, and returns them in a single call (#4224)

Add integration tests for transaction return types and commit flag

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js

cardStore.has returns a promise which wasn't being awaited on
The setup for the wallet needs to be done in case removeIdentity is called.
closes #4248

Fix issue with admin importCard API

---

packages/composer-cli/lib/cmds/card/lib/schema/ccpschema.json
packages/composer-playground/e2e/fabric/hlfv1/profiles/basic-connection-org1.json
packages/composer-tests-functional/systest/testutil.js
packages/composer-tests-integration/profiles/basic-connection-org1-hsm.json
packages/composer-tests-integration/profiles/basic-connection-org1.json
packages/composer-tests-integration/profiles/basic-connection-org1.yaml
packages/composer-tests-integration/profiles/basic-connection-org2.json
packages/composer-tests-integration/profiles/tls-connection-org1.json
packages/composer-tests-integration/profiles/tls-connection-org2.json
packages/composer-website/jekylldocs/reference/connectionprofile.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md

It's not used now we have moved to channel event hubs. And the support is disappearing in 1.2 and 1.3 of fabric.

remove eventUrl from connection profile

---

packages/composer-common/lib/factory.js
packages/composer-common/lib/log/logger.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-rest-server/test/system.js
packages/composer-runtime/test/networkmanager.js

This adds some more logging to the connector and also
a better disconnect implementation.
Also includes setting logging to warning by default for client apps

[0.19.x] Improvements to connector logging and disconnection

---

packages/composer-website/jekylldocs/applications/subscribing-to-events.md

Fixed a typo `transactionId` -> `eventId`.

[Master] Fix typo in event docs

---

packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md

I noticed that some paths were pointing to `.../hlfv11/...` even though `{{ site.data.conrefs.export_fabric_version_command }}` is giving `hlfv12`.

[Master] Update tutorial paths to use Hyperledger Fabric v1.2

---

packages/composer-website/jekylldocs/business-network/publishing-events.md

The docs in their current state are vague when it comes to when events are emitted. After digging around, I found [the events entry in the Composer Knowledge Wiki](https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#information_source--events-consumedsubscribed-to-by-applications-emitted-by-tps) and paired with [this diagram explaining the flow of transactions](https://hyperledger-fabric.readthedocs.io/en/release-1.2/arch-deep-dive.html#swimlane), which explain this in more detail.
I've added a couple of sentences to the docs to clarify this to future users.

[Master] Clarify when events are emitted in the docs

---

packages/composer-playground/src/app/editor/upgrade/upgrade.component.html

Fixes issue: https://github.com/hyperledger/composer/issues/4422

[0.19.x] Changed 'betwork' to 'network' in Playground version 0.19.x

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js

Missing checks in startListening and waitForEvents to ensure we
can still get a commit notification

[Master] Add checks for eventhub failure

---

packages/composer-website/jekylldocs/installing/installing-prereqs.md

Clarifying that the versions of Node must be between 8.9 and 9. Anything equal to 9 or higher will cause the composer libraries to fail to install.

[Master] Clarifying Node versions

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

Fix for issue described in 
https://github.com/hyperledger/composer/issues/4528
It doesn't have optimization (does not remember which peer worked last name) but it resolves the issue.

fix - use next peer for channel init

---

packages/composer-rest-server/server/server.js
packages/composer-rest-server/test/server/server.js

A client listening on a web socket can terminate the rest server
if it is badly behaved and doesn’t cleanly disconnect

[Master] Rest server can be terminated by client

---

packages/composer-common/lib/log/logger.js
packages/composer-common/test/log/logger.js
packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodecontext.js
packages/composer-runtime-hlfv1/lib/nodedatacollection.js
packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime-hlfv1/test/nodecontext.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js
packages/composer-runtime-hlfv1/test/nodeutils.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.registries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/package.json
packages/composer-runtime/test/context.js

This doesn’t fix it for any other logging as all trace points
in composer-runtime will need to be changed, also somehow
the context would have to be passed to apis in composer-common
as well.

[0.19.x] Fix TxId logging for performance logging

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js

This is an experimental feature and meant for advanced and knowledgable composer
users who have multiple channels running the same bna and are looking to provide
scaling through multiple chaincode instances due to lack of capability currently in
hyperledger fabric.

[0.19.x] Experimental override chaincode version

---

packages/composer-rest-server/server/server.js
packages/composer-rest-server/test/server/server.js

A client listening on a web socket can terminate the rest server
if it is badly behaved and doesn’t cleanly disconnect

[0.19.x] Rest server can be terminated by client

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/index.js
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/introspect/property.js
packages/composer-common/lib/readonlydecorator.js
packages/composer-common/lib/readonlydecoratorfactory.js
packages/composer-common/lib/serializer.js
packages/composer-common/lib/serializer/instancegenerator.js
packages/composer-common/lib/serializer/jsonpopulator.js
packages/composer-common/lib/util.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/introspect/property_ex.js
packages/composer-common/test/readonlydecorator.js
packages/composer-common/test/readonlydecoratorfactory.js
packages/composer-common/test/serializer.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/lib/registry.js
packages/composer-runtime/lib/registrymanager.js
packages/composer-runtime/lib/transactionlogger.js
packages/composer-runtime/test/api.js
packages/composer-runtime/test/engine.transactions.js
packages/composer-tests-functional/systest/accesscontrols.js

Performance fixes within runtime to enable skipping JSON generation within serializer if a flag is passed, and enabling the use of this flag in TPFs
-Shortcut serialisation process if objects already exist in serializer and flag is passed
-Add new Decorator to model file for transactions to pass flag to serializer
-Remove unrequired validation steps
-Update tests to account for changes
-Update API text and digest
Signed-off-by: nkl199@yahoo.co.uk <nkl199@yahoo.co.uk>

[0.19.x] Experimental Performance option within runtime

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/readonlydecorator.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/readonlydecorator.js
packages/composer-common/test/readonlydecoratorfactory.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/test/engine.transactions.js

Modify the @readonly decorator to be parameterless
The decorator now exists as `@readonly` on the model file
Tests and API updated with change

make readonly flag parameterless
