packages/composer-common/index.js

Fixes #80 by widening the check

Expand check of node runtime version.

---

site/jekylldocs/tasks/deploybusinessnetwork.md

fix links on the deployment business network task

---

.travis/deploy_docs.sh

.. some of the shell commands need the * expansion

Remove " around some of the doc deploy commands

---

site/jekylldocs/tasks/prerequisites.md

Addresses #179 
1) Added list of pre-reqs to top of doc and linked these to the relevant manual installation descriptions lower down
2) Outlined what the automatic installation script will perform
3) Outlined what the automatic installation script will not perform
4) Removed reference to eGit and certificates
5) Fixed all internal doc links

Fix prereqs

---

site/jekylldocs/index.html

Navigation Fix

---

packages/composer-connector-server/.istanbul.yml
packages/composer-connector-server/cli.js
packages/composer-connector-server/config/.env.sample
packages/composer-connector-server/config/environment/index.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/package.json
packages/composer-connector-server/test/connectorserver.js
packages/composer-ui/cli.js
packages/composer-ui/src/app/app.component.ts
packages/composer-ui/src/app/app.module.ts
packages/composer-ui/src/app/app.routes.ts
packages/composer-ui/src/app/error/error.component.html
packages/composer-ui/src/app/github/github.component.ts
packages/composer-ui/src/app/github/index.ts
packages/composer-ui/src/app/sample/sample.component.html
packages/composer-ui/src/app/sample/sample.component.ts
packages/composer-ui/src/app/samplebusinessnetwork.service.ts
site/README.md
site/jekylldocs/_includes/sidebars/tasks.md
site/jekylldocs/tasks/github-oauth.md
site/jekylldocs/tasks/runtime-start.md

Added ability to do oauth with github to fix rate limit problem

Enable OAuth with Github

---

packages/composer-cli/lib/cmds/archive/createCommand.js

Revert the command line options for the composer archive create command

Revert command line options

---

site/jekylldocs/reference/connectionprofile.md
site/jekylldocs/tasks/prerequisites.md

Clarify prerequisites

---

packages/composer-playground/package.json
packages/composer-runtime/package.json
packages/composer-ui/package.json

Make jsonata version more specific

Fix travis build

---

packages/composer-playground/package.json
packages/composer-ui/package.json

Put more exact version of awesome-typescript-loader

Fix build problem

---

packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/index.html

Removed base tag and adding it to the provider
closes fabric-composer/fabric-composer#221

Fix icons in firefox

---

packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/app/error/error.component.html
packages/composer-playground/src/app/error/error.component.scss
packages/composer-playground/src/app/error/error.component.ts
packages/composer-playground/src/assets/styles/base/_typography.scss
packages/composer-playground/src/assets/styles/components/_model.scss

Updated to show when an error has occurred

Show error messages

---

packages/composer-playground/src/app/add-file/add-file.component.html
packages/composer-playground/src/app/add-file/add-file.component.scss
packages/composer-playground/src/app/add-file/add-file.component.ts
packages/composer-playground/src/app/add-file/index.ts
packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/import/import.component.ts

Add file component exists to allows adding .cto and .js files from the file system to the business network

Add file component

---

packages/composer-playground/src/app/about/about.component.spec.ts
packages/composer-playground/src/app/about/about.component.ts

Add Unit Test for the About Component

---

packages/composer-playground/src/app/connectionprofile.service.spec.ts

test for connectionprofile.service

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/package.json
packages/composer-connector-hlfv1/scripts/copysdk.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js

feat(v1): allow network deploy to work with latest V1 code

---

packages/composer-common/lib/codegen/codegen.js
packages/composer-playground/.istanbul.yml
packages/composer-playground/package.json
packages/composer-playground/src/app/about/about.component.spec.ts
packages/composer-playground/src/app/app.component.scss
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/app/import/import.component.scss
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/welcome/index.ts
packages/composer-playground/src/app/welcome/welcome.component.html
packages/composer-playground/src/app/welcome/welcome.component.scss
packages/composer-playground/src/app/welcome/welcome.component.spec.ts
packages/composer-playground/src/app/welcome/welcome.component.ts
packages/composer-playground/src/assets/styles/base/_variables.scss
packages/composer-playground/src/assets/styles/components/_model.scss

Welcome Modal

---

packages/composer-playground/package.json
packages/composer-playground/src/app/about/about.component.scss
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/import/import.component.html
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/reset/reset.component.html
packages/composer-playground/src/app/reset/reset.component.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/composer-playground/src/assets/styles/components/_side-bar-nav.scss

Updated to show the readme in the editor

View Read me

---

packages/composer-admin/package.json
packages/composer-client/package.json
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/package.json
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-runtime-hlf/datacollection.go
packages/composer-runtime-hlf/dataservice.go
packages/composer-runtime-hlfv1/datacollection.go
packages/composer-runtime-hlfv1/dataservice.go
packages/composer-runtime/lib/datacollection.js
packages/composer-runtime/lib/dataservice.js
packages/composer-runtime/lib/engine.businessnetworks.js
packages/composer-runtime/lib/registrymanager.js
packages/composer-runtime/test/datacollection.js
packages/composer-runtime/test/dataservice.js
packages/composer-runtime/test/registrymanager.js

- Address RYOW issue with reset business network
- Support for multiple peer events
- Changes to address changing in error reporting
1.
2.
3.
4.

feat(v1): More V1 Support changes

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/config/webpack.test.js
packages/composer-playground/src/app/services/about.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts

Added tests for sampleBusinessNetworkService
contributes to fabric-composer/fabric-composer#435

Add sampleBusinessNetworkService tests

---

packages/composer-playground/src/app/registry/registry.component.html
packages/composer-playground/src/app/test/test.component.html
packages/composer-playground/src/app/test/test.component.scss

#416 
Move the button
Observed location of button

Fix transaction button location (#416)

---

contrib-notes/QA-CHECKLIST-TEMPLATE.md
contrib-notes/weekly-qa-validation.md

Not a defect as such -but push in details of the new code. 
https://github.com/fabric-composer/fabric-composer/issues/296
1.
2.
3.
4.

Weekly QA Notes and checklist

---

packages/composer-rest-server/server/boot/composer.js

Cannot start REST server using Lerna hoist

---

packages/composer-playground/src/app/app.component.html
packages/composer-playground/src/app/app.component.scss
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/test/test.component.scss
packages/composer-playground/src/assets/styles/base/_core.scss
packages/composer-playground/src/assets/styles/components/_side-bar-nav.scss

Updated to make the right pane scroll independently
contributes to fabric-composer/fabric-composer#442

Scroll right pane independently

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js

Some code was regressed due to attempts to rebase
this addresses that and ensures the code is back to the correct
level with appropriate tests.
1.
2.
3.
4.

fix(v1): address code regression

---

packages/composer-common/lib/codegen/jsonwriter.js
packages/composer-common/lib/serializer/jsongenerator.js
packages/composer-common/test/codegen/jsonwriter.js
packages/composer-common/test/serializer/jsongenerator.js
packages/composer-systests/systest/participants.js

#468 Double quotes not escaped when serialising assets to JSON
1.
2.
3.
4.

Properly escape strings in JSON serialization

---

packages/composer-website/jekylldocs/_layouts/support.html
packages/composer-website/jekylldocs/assets/css/bootstrap.css
packages/composer-website/jekylldocs/assets/css/main.css

Adding in a GitHub link to our Support page, a few little wording tweaks, and some minor styling tweaks too, all in the interest of neatening up that page a little ;)

Add community info to current Support page

---

packages/composer-playground/src/app/add-file/add-file.component.html
packages/composer-playground/src/app/add-file/add-file.component.ts
packages/composer-playground/src/app/app.component.scss
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/assets/styles/base/_codemirror.scss

Fixed adding new model files and script files
Fixed scrolling and button placement
contributes to fabric-composer/fabric-composer#483 and fabric-composer/fabric-composer#447

Fix adding files and scrolling

---

packages/composer-playground/src/app/transaction/transaction.component.html

Fixed html on submit transaction component

Fix build break

---

.travis.yml

Need to deploy on all branches (including tags)

---

.travis/deploy.sh
packages/composer-playground/src/index.html
packages/composer-ui/src/app/app.e2e.ts
packages/composer-website/jekylldocs/tutorials/defining-a-business-network.md

Playground links are incorrect

---

packages/composer-runtime-hlfv1/identityservice.go

Extract the identity from the signer certificate.
At the moment we don’t have a way to track who deploys and make them the superuser so for now assume the admin id is the super user
1.
2.
3.
4.

feat(v1): Extract Identity from signer certificate

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/config/webpack.test.js
packages/composer-playground/src/app/add-file/add-file.component.spec.ts
packages/composer-playground/src/app/import/import.component.html
packages/composer-playground/src/app/import/import.component.scss
packages/composer-playground/src/app/import/import.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts

added tests for import component

add import component tests

---

packages/composer-connector-hlfv1/lib/hlfconnection.js

fix(v1): remove console.log entries

---

packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/lib/websecuritycontext.js
packages/composer-connector-web/package.json
packages/composer-connector-web/test/webconnection.js
packages/composer-connector-web/test/websecuritycontext.js
packages/composer-runtime-web/lib/webcontext.js
packages/composer-runtime-web/lib/webdataservice.js
packages/composer-runtime-web/lib/webidentityservice.js
packages/composer-runtime-web/test/webcontext.js
packages/composer-runtime-web/test/webdataservice.js
packages/composer-runtime-web/test/webidentityservice.js
packages/composer-systests/systest/accesscontrols.js
packages/composer-systests/systest/identities.js
packages/composer-ui/src/app/app.component.html
packages/composer-ui/src/app/participantregistry/participantregistry.component.html

#57 As a user I can easily test my ACL logic
1.
2.
3.
4.

Add simulated certificate authority for web runtime

---

packages/composer-client/composer-client

Remove bad symlink

---

packages/composer-runtime/lib/api/assetregistry.js
packages/composer-runtime/lib/api/participantregistry.js
packages/composer-runtime/test/api/assetregistry.js
packages/composer-runtime/test/api/participantregistry.js
packages/composer-systests/systest/data/transactions.assets.cto
packages/composer-systests/systest/data/transactions.assets.js
packages/composer-systests/systest/data/transactions.participants.cto
packages/composer-systests/systest/data/transactions.participants.js
packages/composer-systests/systest/transactions.assets.js
packages/composer-systests/systest/transactions.participants.js

#268 Runtime AssetRegistry and ParticipantRegisty exists method
1.
2.
3.
4.

Add runtime API version of the exists() call

---

packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/test/data/model/dependencies/base/base.cto
packages/composer-common/test/data/model/dependencies/business/business.cto
packages/composer-common/test/data/model/dependencies/contract/contract.cto
packages/composer-common/test/data/model/dependencies/contract/proforma.cto
packages/composer-common/test/data/model/dependencies/finance/bond.cto
packages/composer-common/test/models/test.js

#572 
1. ModelManager.addModelFile(...) on a model that imports types which themselves import types
Validate a field in the context of the correct model file, to ensure imports are resolved correctly.
Creates complex model files and added to unit tests.
Added a unit test to packages/composer-common/test/models/test.js
None

Fix for issue 572 - Importing a type doesn't resolve dependent imports

---

packages/composer-client/api.txt
packages/composer-client/changelog.txt
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/test/connectionprofilemanager.js
packages/composer-connector-hlf/lib/hfcconnection.js
packages/composer-connector-hlf/lib/hfcconnectionmanager.js
packages/composer-connector-hlf/lib/hfcwalletproxy.js
packages/composer-connector-hlf/test/hfcconnection.js
packages/composer-connector-hlf/test/hfcconnectionmanager.js
packages/composer-connector-hlf/test/hfcwalletproxy.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/lib/hlfwalletproxy.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfwalletproxy.js

Allow wallets to be supplied via API calls

---

packages/composer-playground/.istanbul.yml

Updated coverage checks to reflect higher test coverage

Update coverage checks

---

.travis/deploy.sh
packages/composer-rest-server/docker/Dockerfile

Build Composer REST server Docker image

---

packages/composer-rest-server/docker/Dockerfile

Revert accidental change to composer-rest-server Dockerfile

---

packages/composer-rest-server/cli.js
packages/composer-rest-server/test/cli.js

Environment variables cannot start REST server

---

packages/composer-connector-server/package.json
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-ui/src/app/admin.service.ts

Enable use of hlfv1 connector in UI and playground

---

packages/composer-website/jekylldocs/installing/createconnectionprofile.md

update the create connection profile to support hlv1 for #611

---

packages/composer-rest-server/common/models/wallet.json
packages/composer-rest-server/package.json
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/server/providers.json
packages/composer-rest-server/test/server/boot/composer-discovery.js

Use data source to persist discovery certificates

---

packages/composer-playground/src/app/resource/resource.component.scss
packages/composer-playground/src/app/transaction/transaction.component.html
packages/composer-playground/src/app/transaction/transaction.component.spec.ts
packages/composer-playground/src/app/transaction/transaction.component.ts

#538 
Code removal and change of variable name in html file to match ts file
Manual FVT
existing unit tests

remove unrequired code and edit angular bound variable to match ts file

---

packages/composer-playground/docker/README.md
packages/composer-ui/docker/README.md

Add README.md files for Playground & UI Docker images

---

.travis/script.sh
packages/composer-playground/src/index.html
packages/composer-website/jekylldocs/_includes/head.html

different Google Analytics IDs

The fabric composer website and playground should be tracked with

---

packages/composer-playground/src/app/editor/editor.component.ts

Fix export error

---

packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/tools/modelcollector.js
packages/composer-common/package.json
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/data/zip/test-npm-archive/package.json

Hopefully fixed revert problem

---

packages/composer-systests/hlfv1/setup-utils.js

fix(v1): address minor issue in setup-utils

---

packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/lib/proxyconnectionmanager.js
packages/composer-connector-proxy/lib/proxysecuritycontext.js
packages/composer-connector-proxy/package.json
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnectionmanager.js
packages/composer-connector-proxy/test/proxysecuritycontext.js
packages/composer-connector-proxy/test/proxyutil.js

1.
2.
3.
4.
#267 Connector server and proxy connector test coverage is not good enough

Add unit tests for proxy connector

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/index.js
packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/lib/log/consolelogger.js
packages/composer-common/test/log/consolelogger.js
packages/composer-connector-server/cli.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/package.json
packages/composer-connector-server/test/cli.js
packages/composer-connector-server/test/connectorserver.js

#267 Connector server and proxy connector test coverage is not good enough
1.
2.
3.
4.

Add unit tests for connector server

---

packages/composer-rest-server/cli.js
packages/composer-rest-server/index.js
packages/composer-rest-server/package.json
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/server/server.js
packages/composer-rest-server/server/servercmd.js
packages/composer-rest-server/test/server/servercmd.js
packages/composer-rest-server/test/system.js
packages/loopback-connector-composer/lib/businessnetworkconnectionwrapper.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnectionwrapper.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Add issueIdentity and revokeIdentity to REST server

---

packages/composer-connector-hlf/lib/hfcutil.js
packages/composer-connector-hlf/test/hfcutil.js
packages/composer-systests/scripts/run-system-tests.sh

REST server attempts to persist issued identities

---

.travis/deploy.sh

Testing for wrong repository slug

---

packages/composer-website/jekylldocs/installing/quickstart.md

correct getting started

---

packages/composer-website/jekylldocs/installing/quickstart.md

- [ x]  A link to the issue/user story that the pull request relates to
#667 
1.
2.
3.
4.

Update quickstart guide for v0.6 / v1.0 options

---

packages/composer-website/README.md
packages/composer-website/jekylldocs/installing/manual_prerequisites.md
packages/composer-website/jekylldocs/installing/prerequisites.md

Edits to address final issues for #179 
- Ensured consistency between versions of installed products
- Removed Ubuntu versioning (we only care about condename)
- Extended requirements for Ubuntu Kernel packages
- Added existence of VSCode plugin
- Updated Readme for doc

Documentation Edits

---

packages/composer-playground/package.json

Fix version of @ng-bootstrap/ng-bootstrap to 1.0.0-alpha.24 due to

---

packages/composer-connector-hlfv1/package.json
packages/composer-systests/package.json

Use fixed fabric-client and fabric-ca-client packages

---

.travis.yml

Update Travis notifications on build outcome.

---

packages/composer-client/lib/businessnetworkconnection.js

Fixed BusinessNetworkConnection.ping() example

---

.travis.yml
contrib-notes/getting-started.md
lerna.json
package.json
packages/composer-playground/README.md
packages/composer-ui/README.md

Also modified travis build to show npm debug logs after failures.

Update version of lerna.

---

packages/composer-playground/README.md
packages/composer-playground/config/webpack.common.js
packages/composer-playground/docker/README.md

Additional rebranding required within:
- Hyperledger Composer title
- Readme(s)

rebranding in readme and title page of Composer UI

---

packages/composer-playground/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile
packages/composer-ui/docker/Dockerfile

Reset npm log level during Docker build

---

packages/composer-playground/src/app/add-certificate/add-certificate.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.spec.ts

Addresses test items in #658 
- save action downloading files
- undesired logging

stub saveAs and tidy logging in composer tests

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/resource/resource.component.spec.ts
packages/composer-playground/src/app/services/identity.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/generator-fabric-composer/generators/angular/templates/.angular-cli.json
packages/generator-fabric-composer/generators/angular/templates/.editorconfig
packages/generator-fabric-composer/generators/angular/templates/README.md
packages/generator-fabric-composer/generators/angular/templates/e2e/tsconfig.e2e.json
packages/generator-fabric-composer/generators/angular/templates/karma.conf.js
packages/generator-fabric-composer/generators/angular/templates/package.json
packages/generator-fabric-composer/generators/angular/templates/protractor.conf.js
packages/generator-fabric-composer/generators/angular/templates/src/app/asset/asset.component.ts
packages/generator-fabric-composer/generators/angular/templates/src/main.ts
packages/generator-fabric-composer/generators/angular/templates/src/test.ts
packages/generator-fabric-composer/generators/angular/templates/src/tsconfig.app.json
packages/generator-fabric-composer/generators/angular/templates/src/tsconfig.spec.json
packages/generator-fabric-composer/generators/angular/templates/src/typings.d.ts
packages/generator-fabric-composer/generators/angular/templates/tsconfig.json
packages/generator-fabric-composer/generators/angular/templates/tslint.json

Generator fixes and initialization testing added

---

packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.spec.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.ts
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/issue-identity/issue-identity.component.spec.ts
packages/composer-playground/src/app/issue-identity/issue-identity.component.ts

stub saveAs and tidy logging

---

packages/composer-playground/src/app/services/initialization.service.ts

#853 Fix Local version
1.
2.
3.
4.

Wait for config to load, cope with webonly COMPOSER_CONFIG

---

packages/composer-playground/src/app/identity-issued/identity-issued.component.html
packages/composer-playground/src/app/identity-issued/identity-issued.component.scss
packages/composer-playground/src/assets/styles/base/_typography.scss

Modify identity issued dialog to more closely reflect designs

---

packages/composer-common/lib/introspect/modelfile.js
packages/composer-common/lib/introspect/parser.pegjs
packages/composer-common/lib/modelutil.js
packages/composer-common/test/data/model/wildcards.cto
packages/composer-common/test/introspect/modelfile.js
packages/composer-common/test/models/wildcards.js
packages/composer-common/test/modelutil.js

#612 As a user, I want to be able to import all types from another namespace in one line of code
1.
2.
3.
4.

Add support for wildcard imports

---

packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.spec.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.ts

Issue 879 - Fix playground default v1 profile

---

packages/composer-playground/src/app/issue-identity/issue-identity.component.html
packages/composer-playground/src/app/issue-identity/issue-identity.component.scss
packages/composer-playground/src/app/issue-identity/issue-identity.component.spec.ts
packages/composer-playground/src/app/issue-identity/issue-identity.component.ts

Fixes item 15 in #839. Also now closer to design in #533

Improve participant typeahead

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/busy/busy.component.html
packages/composer-playground/src/app/busy/busy.component.scss
packages/composer-playground/src/app/busy/busy.component.spec.ts
packages/composer-playground/src/app/services/alert.service.ts
packages/composer-playground/src/app/services/initialization.service.ts

Updated to remove ok button and it will close when finished
contributes to hyperledger/composer#839

Update busy component

---

.travis/deploy.sh

Move Docker Hub publishing from the `fabriccomposer` to the `hyperledger` org.
As a contributor I manage code using Hyperledger infrastructure #620

Move from fabriccomposer org to hyperledger org

---

packages/composer-playground/docker/README.md
packages/composer-website/jekylldocs/tutorials/docker-compose.yml
packages/composer-website/jekylldocs/tutorials/getting-started-playground.md

Update all docs to point to `hyperledger` Docker Hub org instead of `fabriccomposer` org.
As a contributor I manage code using Hyperledger infrastructure #620

Update all docs to point to hyperledger org

---

packages/composer-playground/src/app/add-certificate/add-certificate.component.spec.ts
packages/composer-playground/src/app/add-certificate/add-certificate.component.ts

Fix playground certificate error
1.
2.
3.
4.

Fixed certificate parsing error

---

packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/busy/busy.component.scss
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/composer-playground/src/assets/styles/elements/_button.scss

Updated styling
Update busy status's
Fix button spinner

Fix busy component

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

feat(undeploy): add undeploy in same manner as v0.6

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

In preparation for alpha 2, some code refectoring has been done
plus fix the attributes to allow for the creation of identities that can issue more identities

refactoring of code in prep for alpha 2

---

packages/composer-playground/src/app/app.component.html
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.spec.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/services/alert.service.ts
packages/composer-playground/src/app/success/success.component.html
packages/composer-playground/src/app/success/success.component.scss
packages/composer-playground/src/app/success/success.component.spec.ts
packages/composer-playground/src/app/success/success.component.ts
packages/composer-playground/src/app/switch-identity/switch-identity.component.spec.ts
packages/composer-playground/src/app/test/test.component.ts
packages/composer-playground/src/assets/svg/other/transaction.svg

Updated success component
contributes to hyperledger/composer#894

Success Component

---

packages/composer-website/installers/hlfv1/docker-compose.yml

Fix Docker Hub org for installer

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/test/test.component.html
packages/composer-playground/src/app/test/test.component.spec.ts
packages/composer-playground/src/app/test/test.component.ts

Added tests for the test component
contributes to hyperledger/composer#953

Test Component Tests

---

packages/composer-runtime-hlfv1/chaincode.go
packages/composer-runtime-hlfv1/identityservice.go
packages/composer-runtime-hlfv1/main.go

chaincode updates in prep for alpha2

---

.travis/deploy.sh
packages/composer-cli/docker/Dockerfile

As a user, I can download and use a Docker image for the CLI #978
1.
2.
3.
4.

Publish a Docker image for the CLI

---

packages/composer-cli/docker/Dockerfile
packages/composer-playground/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile

Reduce size of Docker images by removing temporary apk packages

---

packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/test/system.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

As a user, I can access transactions from the REST API #981
1.
2.
3.
4.

Expose processed transactions through the REST API (#981)

---

packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts

Updated to fix problem when a expected file is not found

Fix importing sample networks

---

packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.ts

Fixed Playground Orderers Import Bug

---

packages/composer-playground/src/app/app.component.html
packages/composer-playground/src/app/services/identity.service.spec.ts
packages/composer-playground/src/app/services/identity.service.ts
packages/composer-playground/src/assets/styles/elements/_header.scss

Show current identity in top nav bar

---

packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/test/network/list.js
packages/composer-cli/test/transaction/submit.js
packages/composer-client/api.txt
packages/composer-client/changelog.txt
packages/composer-client/lib/assetregistry.js
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/lib/participantregistry.js
packages/composer-client/test/assetregistry.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-client/test/participantregistry.js

Will now display participant registry in composer network list

---

packages/composer-playground/src/app/services/identity.service.ts

Fix missing identity in top navigation

---

packages/composer-playground/package.json
packages/composer-runtime-hlf/package.json
packages/composer-runtime-hlfv1/package.json
packages/composer-runtime/package.json

Use exact versions for jsonata and uglify-js dependencies

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Composer rest server returns unexpected data in results on a Post to create Participant/Asset #1048
1.
2.
3.
4.

invokeChainCode() returns array for HLFv1 connector

---

packages/composer-admin/package.json
packages/composer-cli/package.json
packages/composer-client/package.json
packages/composer-common/package.json
packages/composer-connector-embedded/package.json
packages/composer-connector-hlf/package.json
packages/composer-connector-hlfv1/package.json
packages/composer-connector-proxy/package.json
packages/composer-connector-server/package.json
packages/composer-rest-server/package.json
packages/composer-runtime-embedded/package.json
packages/composer-runtime/package.json
packages/loopback-connector-composer/package.json

Increase all test timeouts to 5000ms

---

packages/composer-runtime/lib/api.js
packages/composer-runtime/test/api.js

Use convertResourcesToRelationships option when serializing events

---

packages/composer-common/lib/serializer/jsongenerator.js
packages/composer-common/test/serializer/jsongenerator.js

Regarding issue #1085 
1.
2.
3.
4.

Concept Subclasses retrieved correctly

---

.travis.yml
.travis/script.sh

Add back missing Travis job

---

packages/composer-website/package.json

Fix docs build process

---

.travis/script.sh

Actually fix docs build process

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/import/import.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts

Updated to make sure to clear the busy status

Fix Playground Hang

---

packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/composer-common/test/codegen/loopbackvisitor.js

Render enumerations in LoopBack models

---

packages/composer-website/jekylldocs/assets/img/tutorials/developer/Tutorial2.md
packages/composer-website/jekylldocs/getting-started/getting-started-with-playground.md
packages/composer-website/jekylldocs/getting-started/using-playground-locally.md
packages/composer-website/jekylldocs/index.html
packages/composer-website/jekylldocs/tutorials/developer-guide.md

Fixing some of the issues raised in #912

Docs fixes

---

packages/composer-website/jekylldocs/getting-started/development-tools.md
packages/composer-website/jekylldocs/tutorials/developer-guide.md

fix docs due to cla issues

---

packages/composer-website/jekylldocs/tutorials/developer-guide.md

Liccheck failure

---

packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.ts

Updated to look for a connection profile to connect to as default
contributes to hyperledger/composer#962
DCO 1.1 signed-off-by Caroline Church<cazfletch@gmail.com>

Automatically change profile when using docker container

---

packages/composer-playground/src/app/switch-identity/switch-identity.component.html
packages/composer-playground/src/app/transaction/transaction.component.html
packages/composer-playground/src/assets/styles/components/_dropdown.scss

Disabled connect if empty wallet
Fixed submit transaction dropdown text overflow

UI Nitpicks

---

packages/composer-playground/src/app/app.component.html

Updated to correct url
contributes to hyperledger/composer#1151

Fix local install url

---

packages/composer-runtime-embedded/index.js
packages/composer-runtime-embedded/lib/embeddedcontext.js
packages/composer-runtime-embedded/lib/embeddedscriptcompiler.js
packages/composer-runtime-embedded/package.json
packages/composer-runtime-embedded/test/embeddedcontext.js
packages/composer-runtime-embedded/test/embeddedscriptcompiler.js
packages/composer-runtime/index.js
packages/composer-runtime/lib/scriptcompiler.js
packages/composer-runtime/test/index.js
packages/composer-runtime/test/scriptcompiler.js

Allow the embedded runtime to instrument code

---

packages/composer-website/installers/hlfv0.6/docker-compose.yml
packages/composer-website/installers/hlfv1/docker-compose-playground.yml

As a user, I should not have to manually switch connection profiles to try out HLFv1 #962
1.
2.
3.
4.

Use the HLF connection profile by default for single line installer

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.js

BNAs are different during unit tests due to timestamps

---

packages/composer-playground/src/app/app.component.html

Update to point to what will be there once unstable docs become stable

change URL to match desired local build page

---

packages/composer-playground/e2e/scripts/test.js
packages/composer-playground/e2e/tests/welcome.spec.ts
packages/composer-playground/protractor.conf.js
packages/composer-playground/src/app/welcome/welcome.component.html

Protractor test base extensions for #863.
- Remove requirement for hosting drivers
- Complete first test suite (Welcome component)

Protractor Test Extensions

---

packages/composer-playground/src/app/directives/check-overflow/check-overflow.directive.spec.ts
packages/composer-playground/src/app/directives/check-overflow/check-overflow.directive.ts
packages/composer-playground/src/app/registry/registry.component.html
packages/composer-playground/src/app/registry/registry.component.scss
packages/composer-playground/src/app/registry/registry.component.spec.ts

Fixed animation
Fixed problem with only showing first 1000px of height

Fix expand resources

---

packages/composer-systests/hlfv1/.gitignore

Crypto material shows up in pending Git changes

---

packages/composer-rest-server/common/models/wallet-identity.json
packages/composer-rest-server/lib/loopbackwallet.js
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/server/boot/composer-runtime.js
packages/composer-rest-server/test/lib/loopbackwallet.js

LoopBack wallets do not work properly with HLFv1 #1268
1.
2.
3.
4.

Get LoopBack wallets working properly with HLFv1

---

packages/composer-playground/src/app/registry/registry.component.html
packages/composer-playground/src/app/registry/registry.component.spec.ts
packages/composer-playground/src/app/registry/registry.component.ts

Fixed as if the last resource in the list didn't need expanding the button wouldn't appear on any

Fix expanding resource

---

packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/identity/identity.component.scss
packages/composer-playground/src/app/identity/identity.component.spec.ts
packages/composer-playground/src/app/identity/identity.component.ts
packages/composer-playground/src/app/issue-identity/issue-identity.component.html
packages/composer-playground/src/app/issue-identity/issue-identity.component.spec.ts
packages/composer-playground/src/app/issue-identity/issue-identity.component.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/wallet.service.spec.ts
packages/composer-playground/src/app/services/wallet.service.ts
packages/composer-playground/src/assets/styles/elements/_button.scss

Identities can now be removed from the wallet in the playground

Add remove identity to playground

---

packages/composer-playground/src/app/add-certificate/add-certificate.component.spec.ts
packages/composer-playground/src/app/add-certificate/add-certificate.component.ts

Fix cert issues in playground

---

packages/composer-runtime-hlfv1/chaincode.go

fix logging in runtime

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.ts
packages/composer-playground/src/app/directives/file-drag-drop/file-drag-and-drop.directive.spec.ts
packages/composer-playground/src/app/services/client.service.spec.ts

Added tests for FileDragDropDirective
Removed random console.logs
Updated coverage requirements

Add Drag and Drop Tests

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/basic-modals/confirm/confirm.component.spec.ts
packages/composer-playground/src/app/basic-modals/error/error.component.spec.ts
packages/composer-playground/src/app/basic-modals/replace-confirm/replace-confirm.component.spec.ts
packages/composer-playground/src/app/basic-modals/success/success.component.spec.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.spec.ts
packages/composer-playground/src/app/connection-profile/connection-profile.component.spec.ts

Added tests to add-connection-profile
Updated tests for connection-profile
Updated tests for connection-profile-data
Updated tests for basic models

Add Various Tests

---

.travis/before-install.sh

Fix expected in master but reverting for now so builds work in release-0.9.0

Revert "drop in the detection script for live testing (#1286)"

---

packages/composer-playground/src/app/add-certificate/add-certificate.component.html
packages/composer-playground/src/app/add-certificate/add-certificate.component.spec.ts
packages/composer-playground/src/app/add-certificate/add-certificate.component.ts
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.html
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.spec.ts
packages/composer-playground/src/app/connection-profile-data/connection-profile-data.component.ts
packages/composer-playground/src/app/services/connectionprofile.service.spec.ts
packages/composer-playground/src/app/services/connectionprofile.service.ts
packages/composer-playground/src/app/view-certificate/view-certificate.component.html
packages/composer-playground/src/app/view-certificate/view-certificate.component.spec.ts
packages/composer-playground/src/app/view-certificate/view-certificate.component.ts

remove hostnameOverride, but keep if specified in imported profile

---

packages/composer-playground/src/app/directives/check-overflow/check-overflow.directive.spec.ts
packages/composer-playground/src/app/directives/check-overflow/check-overflow.directive.ts
packages/composer-playground/src/app/resource/resource.component.scss

Fixed expanding buttons on safari
fixed duplicate scroll bars

Fix expanding buttons and scroll bars

---

.travis/before-install.sh

Correct beforeinstall.sh;

---

.travis/before-install.sh
.travis/script.sh
packages/composer-website/package.json
packages/composer-website/scripts/linkcheck.sh

linkchecker scripts

---

.travis/script.sh
packages/composer-website/jekylldocs/_config.yml
packages/composer-website/jekylldocs/applications/applications-index.md
packages/composer-website/jekylldocs/installing/installing-index.md
packages/composer-website/jekylldocs/integrating/integrating-index.md
packages/composer-website/jekylldocs/managing/managingindex.md
packages/composer-website/jekylldocs/reference/reference-index.md
packages/composer-website/package.json
packages/composer-website/scripts/linkcheck.sh

Defect unstable docs css

---

.travis/before-install.sh
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/test/modelmanager.js

Have added code to the toArchive to prevent the system model file being included
Also added code comments to the private APIs re their usage

Defect sysmodel exported

---

packages/composer-playground/e2e/scripts/test.js
packages/composer-playground/package.json
packages/composer-playground/src/app/issue-identity/issue-identity.component.spec.ts

Pin typescript version to 2.4.0 for rxjs issue #2539

---

packages/composer-website/jekylldocs/business-network/query.md
packages/composer-website/jekylldocs/reference/query-language.md
packages/composer-website/jekylldocs/tutorials/developer-guide.md
packages/composer-website/jekylldocs/tutorials/playground-guide.md

remove incorrect model elements

---

.travis/before-install.sh

Defect changed files

---

packages/composer-website/jekylldocs/tutorials/playground-guide.md

Fix playground tutorial ACL

---

.travis/before-install.sh

protect release builds

---

packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.html
packages/composer-playground/src/app/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/add-file/add-file.component.html
packages/composer-playground/src/app/file-importer/file-importer.component.html
packages/composer-playground/src/app/file-importer/file-importer.component.spec.ts
packages/composer-playground/src/app/file-importer/file-importer.component.ts
packages/composer-playground/src/app/import/import.component.html
packages/composer-playground/src/app/import/import.component.spec.ts

Updated to give an error if you try an import an invalid file type via the browse button

Fix importing files via browse

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Updated to give an error if you try adding an invalid model file

Fix adding invalid model files

---

.travis.yml
packages/composer-systests/scripts/run-system-tests.sh

Combine the embedded, proxy, and web system tests into a single build

---

packages/composer-website/jekylldocs/reference/acl_language.md

Add missing ACL language docs (resolves #1039, resolves #575)

---

packages/composer-common/lib/introspect/classdeclaration.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/codegen/jsonschemavisitor.js
packages/composer-common/test/codegen/loopbackvisitor.js
packages/composer-common/test/introspect/introspector.js
packages/composer-common/test/models/test.js

Phase #1 of updating the unit tests to be happier about the system model. 
In this phase it's been about unit tests that assume that the only types that will back are the network being tested.

Updated unit tests

---

packages/composer-cli/lib/cmds/network/deployCommand.js
packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/utils/cmdutils.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/utils/cmdutils.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

Feat(v1): Support Endorsement Policies in the Command Line

---

packages/composer-playground/package.json

Use released version of basic-sample-network

---

packages/composer-runtime-pouchdb/lib/pouchdbdataservice.js
packages/composer-runtime-pouchdb/package.json
packages/composer-runtime-pouchdb/test/pouchdbdatacollection.js
packages/composer-runtime-pouchdb/test/pouchdbdataservice.js
packages/composer-runtime-pouchdb/test/pouchdbutils.js
packages/composer-runtime-web/lib/webdataservice.js

PouchDB brings in LevelDB, which requires binary modules #1481
1.
2.
3.
4.

Use minimal PouchDB bundle

---

packages/composer-runtime-pouchdb/lib/pouchdbdataservice.js
packages/composer-runtime-pouchdb/package.json
packages/composer-runtime-web/lib/webdataservice.js

Add WebSQL adapter to handle Safari

---

packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/assets.js
packages/loopback-connector-composer/test/businessnetworkconnector.js
packages/loopback-connector-composer/test/index.js
packages/loopback-connector-composer/test/participants.js

Complete PersistentModel API tests (resolves #930)

---

packages/composer-common/lib/introspect/relationshipdeclaration.js
packages/composer-common/test/data/parser/assetdeclaration.systypename.cto
packages/composer-common/test/data/parser/classdeclaration.isrelationshiptarget.cto
packages/composer-common/test/data/parser/classdeclaration.noidentifier.cto
packages/composer-common/test/data/parser/classdeclaration.participantwithparents.child.cto
packages/composer-common/test/data/parser/eventdeclaration.systypename.cto
packages/composer-common/test/data/parser/participantdeclaration.systypename.cto
packages/composer-common/test/data/parser/participantdeclaration.valid.cto
packages/composer-common/test/data/parser/relationshipdeclaration.missingtype.cto
packages/composer-common/test/introspect/assetdeclaration.js
packages/composer-common/test/introspect/basemodelexception.js
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/eventdeclaration.js
packages/composer-common/test/introspect/modelfile.js
packages/composer-common/test/introspect/numbervalidator.js
packages/composer-common/test/introspect/participantdeclaration.js
packages/composer-common/test/introspect/relationshipdeclaration.js
packages/composer-common/test/introspect/transactiondeclaration.js

composer-common/lib/introspect unit tests

---

packages/composer-common/lib/serializer.js
packages/composer-common/lib/serializer/resourcevalidator.js
packages/composer-cucumber-steps/features/basic-sample-network/models/sample.cto
packages/composer-cucumber-steps/lib/composer.js

Issue where events aren't validated before being emitted #1501

Event validation

---

packages/composer-playground/src/app/test/view-transaction/view-transaction.component.html
packages/composer-playground/src/app/test/view-transaction/view-transaction.component.scss

Added svg transformation when showing event (#1499)

---

.travis/deploy.sh

Only deploy for tagged/release builds and the master branch

---

packages/composer-runtime/lib/querycompiler.js
packages/composer-runtime/test/querycompiler.js
packages/composer-systests/systest/data/queries.qry
packages/composer-systests/systest/data/transactions.queries.qry
packages/composer-systests/systest/queries.js
packages/composer-systests/systest/transactions.queries.js

Enable complex queries against nested properties

---

contrib-notes/release-process/playground-validation.md

Updated validation notes to account for the addition and working of a query file in playground, as per issue #1332.

Update validation notes for query

---

packages/composer-playground/src/app/editor/editor-file/editor-file.component.scss
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/assets/styles/base/_codemirror.scss
packages/composer-playground/src/assets/styles/base/_typography.scss
packages/composer-playground/src/assets/styles/composer.scss

Styling changes to README & typography fixes

---

packages/composer-connector-hlfv1/package.json
packages/composer-systests/hlfv1/docker-compose.tls.yml
packages/composer-systests/hlfv1/docker-compose.yml
packages/composer-systests/scripts/run-system-tests.sh

Move to Hyperledger Fabric v1.0.0 (npm dependencies, system tests)

---

packages/composer-client/api.txt
packages/composer-client/changelog.txt
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/modelmanager.js
packages/composer-runtime-hlfv1/identityservice.go
packages/composer-runtime/lib/compiledscriptbundle.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.identities.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/lib/engine.logging.js
packages/composer-runtime/lib/httpservice.js
packages/composer-runtime/lib/identitymanager.js
packages/composer-runtime/lib/identityservice.js
packages/composer-runtime/lib/queryexecutor.js
packages/composer-runtime/lib/transactionlogger.js
packages/composer-runtime/test/context.js
packages/composer-runtime/test/engine.identities.js
packages/composer-runtime/test/engine.js
packages/composer-runtime/test/identitymanager.js
packages/composer-runtime/test/identityservice.js
packages/composer-systests/systest/identities.js

Initial drop of identity registry

---

packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/lib/embeddedsecuritycontext.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedsecuritycontext.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/lib/websecuritycontext.js
packages/composer-connector-web/test/webconnection.js
packages/composer-connector-web/test/websecuritycontext.js
packages/composer-runtime-embedded/lib/embeddedcontext.js
packages/composer-runtime-embedded/lib/embeddedidentityservice.js
packages/composer-runtime-embedded/test/embeddedcontext.js
packages/composer-runtime-embedded/test/embeddedidentityservice.js
packages/composer-runtime-web/lib/webcontext.js
packages/composer-runtime-web/lib/webidentityservice.js
packages/composer-runtime-web/test/webcontext.js
packages/composer-runtime-web/test/webidentityservice.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/test/context.js

Get identities working again on embedded and web runtimes

---

packages/composer-cli/lib/cmds/identity/bindCommand.js
packages/composer-cli/lib/cmds/identity/issueCommand.js
packages/composer-cli/lib/cmds/identity/lib/bind.js
packages/composer-cli/package.json
packages/composer-cli/test/identity/bind.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/test/context.js

Add composer identity bind command to CLI

---

packages/composer-website/scripts/setup-jekyll.sh

Use workaround for jekyll issue #6221

---

packages/composer-runtime-embedded/package.json
packages/composer-runtime-pouchdb/package.json
packages/composer-runtime-web/package.json

Fix PouchDB version to v6.2.0

---

packages/composer-website/jekylldocs/index.html

Add outbound link tracking back to online playground button

---

packages/composer-playground/src/app/app.module.ts
packages/composer-playground/src/app/common/drawer/drawer-backdrop.component.scss
packages/composer-playground/src/app/common/drawer/drawer-backdrop.component.spec.ts
packages/composer-playground/src/app/common/drawer/drawer-backdrop.component.ts
packages/composer-playground/src/app/common/drawer/index.ts
packages/composer-playground/src/assets/styles/components/_drawer.scss
packages/composer-playground/src/assets/styles/composer.scss

Also add initial common styles for drawer content and include drawer
module in app

Fix backdrop animation

---

packages/composer-website/jekylldocs/installing/development-tools.md
packages/composer-website/jekylldocs/prereqs-ubuntu.sh

Ubuntu pre reqs

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/runtime.js
packages/composer-cli/lib/cmds/runtime/installCommand.js
packages/composer-cli/lib/cmds/runtime/lib/install.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/runtime/install.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-hlf/lib/hfcconnection.js
packages/composer-connector-hlf/test/hfcconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js
packages/composer-systests/systest/assets.js
packages/composer-systests/systest/identities.js
packages/composer-systests/systest/transactions.assets.js

Runtime code for install and start

---

packages/composer-runtime/lib/querycompiler.js
packages/composer-runtime/test/querycompiler.js
packages/composer-systests/systest/data/queries.qry
packages/composer-systests/systest/data/transactions.queries.qry
packages/composer-systests/systest/queries.js
packages/composer-systests/systest/transactions.queries.js

Query compiler fails to generate queries with dynamic limit/skip clauses #1596
1.
2.
3.
4.

Fix incorrectly compiled queries with dynamic limit/skip clauses

---

packages/composer-common/test/data/model/enum.cto
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/enumdeclaration.js
packages/composer-playground/src/app/editor/import/import.component.html
packages/composer-playground/src/app/editor/import/import.component.spec.ts
packages/composer-playground/src/app/editor/import/import.component.ts
packages/composer-rest-server/cli.js

Remove system and abstract types from Playground summary when importing a business network

Remove system and abstract types from bna preview

---

packages/composer-playground/src/app/editor/editor.component.ts

Corrected spelling mistake as per issue #1614.

Fixed typo in query modal

---

packages/composer-playground/src/app/login/identity-card/identity-card.component.html
packages/composer-playground/src/app/login/identity-card/identity-card.component.scss
packages/composer-playground/src/app/login/identity-card/identity-card.component.spec.ts
packages/composer-playground/src/app/login/identity-card/identity-card.component.ts
packages/composer-playground/src/app/login/identity-card/index.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.scss
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.module.ts

during identity card import
Contributes to #902

Extract identity card component for use on login screen and

---

packages/composer-website/jekylldocs/installing/development-tools.md

minor doc fix

---

packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/lib/log/logger.js
packages/composer-common/lib/log/winstonInjector.js
packages/composer-connector-hlfv1/lib/hlfconnection.js

Corrected the trace default log levels
Changed name and directory to be more meaningful
Removed the error logs from the connection profile as it was unrequired and caused too much noise

change logging & correct log statement level

---

packages/composer-common/lib/factory.js

JSDoc fixes for newConcept, fix for 1610

---

packages/composer-playground/src/app/test/transaction/transaction.component.spec.ts
packages/composer-playground/src/app/test/transaction/transaction.component.ts

Filter out system transaction types in playground

---

packages/composer-cli/lib/cmds/identity/lib/list.js
packages/composer-cli/lib/cmds/identity/listCommand.js
packages/composer-cli/test/identity/list.js
packages/composer-client/index.js

Add composer identity list CLI command

---

packages/composer-website/jekylldocs/tutorials/developer-guide.md

Minor fix in the developer guide document - network deploy output was incorrect, which caused confusion

fixed network deploy output

---

packages/composer-playground/src/app/login/identity-card/identity-card.component.scss
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.scss
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/login/login.module.ts
packages/composer-playground/src/assets/styles/components/_drawer.scss

Also makes action buttons circular and adds import button

Add footer to login page

---

packages/composer-rest-server/cli.js
packages/composer-rest-server/lib/util.js
packages/composer-rest-server/package.json
packages/composer-rest-server/server/boot/composer-discovery.js
packages/composer-rest-server/server/server.js
packages/composer-rest-server/test/assets.js
packages/composer-rest-server/test/cli.js
packages/composer-rest-server/test/data/bond-network/lib/logic.js
packages/composer-rest-server/test/data/bond-network/models/bond.cto
packages/composer-rest-server/test/events.js
packages/composer-rest-server/test/lib/util.js
packages/composer-rest-server/test/participants.js
packages/composer-rest-server/test/queries.js
packages/composer-rest-server/test/server/boot/composer-discovery.js
packages/composer-rest-server/test/server/server.js
packages/composer-rest-server/test/system.js
packages/composer-rest-server/test/transactions.js
packages/loopback-connector-composer/lib/businessnetworkconnectionwrapper.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnectionwrapper.js
packages/loopback-connector-composer/test/businessnetworkconnector.js
packages/loopback-connector-composer/test/data/bond-network/lib/logic.js
packages/loopback-connector-composer/test/data/bond-network/models/bond.cto
packages/loopback-connector-composer/test/events.js
packages/loopback-connector-composer/test/transactions.js

Enable event subscription using WebSockets in the REST server

---

packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/test/engine.js

Avoid recompiling the same scripts/queries/ACLs if already cached

---

packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.network.start.md
packages/composer-website/jekylldocs/reference/composer.runtime.install.md

remove term ‘endorsing’

---

packages/composer-playground/src/app/app.component.html

Edits to satisfy #1689
Changes wording
Remove ngFor iterator across profiles
Left align all items, including logout

change text and only show single registry option

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/idcard.js
packages/composer-common/test/idcard.js

Add IdCard.toArchive function (#1427)

---

packages/composer-runtime/lib/context.js

Such that on the update of the business network, they are reset.

Reset some of the Register Managers

---

packages/composer-cli/lib/cmds/identity/importCommand.js
packages/composer-cli/test/identity/import.js

fix import that was broken

---

packages/composer-playground/e2e/component/editor.ts
packages/composer-playground/e2e/specs/editor-define.spec.ts
packages/composer-playground/e2e/utils/operations-helper.ts
packages/composer-playground/src/app/connection-profile/connection-profile.component.html
packages/composer-playground/src/app/editor/editor.component.html
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/footer/footer.component.scss
packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/test/registry/registry.component.html
packages/composer-playground/src/app/test/registry/registry.component.scss
packages/composer-playground/src/app/test/test.component.html
packages/composer-playground/src/app/test/test.component.scss
packages/composer-playground/src/assets/styles/components/_side-bar-nav.scss

Assimilation of existing PR with fixes for protractor test (slow page loading) and absence of historian in Safari browser.
Addresses:
- #1696 
- #1748

1696 footer white space

---

packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.html
packages/composer-playground/src/app/identity/add-identity/add-identity.component.spec.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Change in components to use id card service - aspect of #1423

swap to using id card service

---

packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.spec.ts
packages/composer-playground/src/app/connection-profile/add-connection-profile/add-connection-profile.component.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.html
packages/composer-playground/src/app/identity/add-identity/add-identity.component.spec.ts
packages/composer-playground/src/app/identity/add-identity/add-identity.component.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Revert "swap to using id card service (#1773)"

---

packages/composer-common/package.json
packages/composer-common/test/codegen/javascriptparser.js

Bump version of Acorn parser to ^5.1.1 (#1611)

---

packages/composer-cli/lib/cmds/identity/lib/list.js
packages/composer-cli/lib/cmds/network/lib/list.js

fix apparent hang on 2 cli commands

---

packages/composer-common/lib/codegen/javascriptparser.js
packages/composer-common/test/codegen/javascriptparser.js
packages/composer-common/test/data/commentparsing/BasicExample.js.txt
packages/composer-common/test/data/commentparsing/ClassExample.js.txt
packages/composer-common/test/data/commentparsing/ComplexExample.js.txt
packages/composer-common/test/data/commentparsing/UncommentedFollowingCommented.js.txt

fix comment parsing

---

packages/composer-cli/docker/Dockerfile
packages/composer-playground/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile

Remove yarn from docker images

---

packages/composer-common/package.json

Temporarily revert to minimise risk to this week's release.
**Please check with me before merging.**

Revert version bump for Acorn JavaScript parser

---

.travis/deploy.sh
.travis/install.sh
.travis/script.sh

remove tee

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/basic-modals/delete-confirm/delete-confirm.component.html
packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.spec.ts
packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.ts
packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/identity/identity.component.spec.ts
packages/composer-playground/src/app/identity/identity.component.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/assets/styles/base/_typography.scss

Issue Identity uses id card
IdentityComponent uses id card

Use id cards with identity registry

---

packages/composer-runtime/lib/engine.businessnetworks.js
packages/composer-runtime/lib/engine.js

Updated name of historian to just be historian
contributes to hyperledger/composer#1851

Update the name of historian

---

packages/composer-playground-api/routes/npm.js
packages/composer-playground-api/test/npm.js
packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/app.component.spec.ts
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/editor/editor.component.scss
packages/composer-playground/src/app/import/import.component.html
packages/composer-playground/src/app/import/import.component.scss
packages/composer-playground/src/app/import/import.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.scss
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/composer-playground/src/assets/styles/elements/_tooltip.scss

Update deploy business network to use id card service
contributes to hyperledger/composer#1414

Update Deploy Business Network

---

contrib-notes/getting-started.md

Updated getting-started.md by mentioning the steps needed to verify changes made to composer-playground package.

---

packages/composer-common/lib/introspect/script.js
packages/composer-common/test/introspect/script.js

Additional information and logging on JavaScript parse errors

---

packages/composer-playground/src/app/login/identity-card/identity-card.component.html
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

Import certificate on first use of a card
Updated role html
contributes to hyperledger/composer#1412

Use Certificate From Import

---

packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Allow identity cards to be exported from playground

---

packages/composer-playground/src/app/common/file-importer/file-importer.component.scss
packages/composer-playground/src/app/import/import.component.scss
packages/composer-playground/src/app/login/import-identity/import-identity.component.html
packages/composer-playground/src/app/login/import-identity/import-identity.component.scss
packages/composer-playground/src/app/services/admin.service.spec.ts
packages/composer-playground/src/app/services/admin.service.ts

Updated to add height property to stop bouncy buttons
Fixed initial deploy
contributes to hyperledger/composer#1412

Fix Animation on File Importer

---

packages/composer-playground/src/app/footer/footer.component.html

Fix 'Community' link in Playground UI

---

packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

Fix id card delete

---

packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.ts

Updated to ignore 404 from loading config
contributes to hyperledger/composer#902

Fix config when using locally

---

packages/composer-playground/src/app/basic-modals/delete-confirm/delete-confirm.component.html
packages/composer-playground/src/app/basic-modals/delete-confirm/delete-confirm.component.ts
packages/composer-playground/src/app/identity/identity.component.ts
packages/composer-playground/src/app/import/deploy.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/import/update.component.spec.ts
packages/composer-playground/src/app/login/create-identity-card/create-identity-card.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/version-check/version-check.component.spec.ts
packages/composer-playground/src/app/version-check/version-check.component.ts

Refresh login after clear local storage
Sort connection profile names
Updated revoke identity message
stop being able to create an id card with web profile
Fix empty business network name
contributes to hyperledger/composer#1930

Fix identities nitpicks

---

packages/composer-playground/src/app/services/initialization.service.spec.ts
packages/composer-playground/src/app/services/initialization.service.ts

Fix problem with non local playground on initialization
contributes to hyperledger/composer#902

Fix non local playground

---

packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.spec.ts
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.ts
packages/composer-playground/src/app/login/identity-card/identity-card.component.html
packages/composer-playground/src/app/login/identity-card/identity-card.component.scss
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Fixed ordering of identities
Made business network name required
Made height of id cards the same
Fix long business network names
contributes to hyperledger/composer#1930

Fix more nitpicks

---

packages/composer-website/jekylldocs/integrating/call-out.md
packages/composer-website/jekylldocs/integrating/deploying-the-rest-server.md
packages/composer-website/jekylldocs/integrating/enabling-rest-authentication.md
packages/composer-website/jekylldocs/integrating/node-red.md
packages/composer-website/jekylldocs/integrating/publishing-events.md
packages/composer-website/jekylldocs/integrating/securing-the-rest-server.md

https://github.com/hyperledger/composer/issues/1788
1.
2.
3.
4.
Add documentation that describes how to publish events from the REST server by enabling WebSockets.

Add docs for publishing events from the REST server

---

packages/composer-playground/src/app/app.component.spec.ts
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/app/basic-modals/success/success.component.ts
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Updated busy status to stop the continuely spinner
contributes to hyperledger/composer#1930

Update Busy Status

---

packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/import/update.component.spec.ts
packages/composer-playground/src/app/import/update.component.ts

Pass in reference to the active draw and close it during the deploy action
Eyeballed on browsers, new test added
test++

hide tray on deploy confirm

---

packages/composer-cli/lib/cmds/archive/listCommand.js

- [ x]  A link to the issue/user story that the pull request relates to
- [ x]  How to recreate the problem without the fix
- [ x]  Design of the fix
- [ x]  How to prove that the fix works
- [ x]  Documentation - any JSDoc, website, or Stackoverflow answers?
<we need more tests for the whole of cli packages>
Issue:1800

Make option required.

---

packages/composer-rest-server/public/css/composer.css
packages/composer-rest-server/public/index.html
packages/composer-rest-server/server/boot/root.js
packages/composer-rest-server/test/authentication.js
packages/composer-rest-server/test/root.js
packages/composer-website/jekylldocs/integrating/enabling-rest-authentication.md

As a user I can protect my REST APIs using authentication and authorization #142
Is it possible to call secured composer APIs from server side(node) #1996
1.
2.
3.
4.
The final part of epic #142! This pull request adds the access token into the REST explorer for authenticated users. This means that a user can:
1. Authenticate to the REST server in a web browser
2. Use the REST explorer to determine their access token
3. Use their access token with any standard HTTP or REST client
The most important part about 3) is that it allows any program to make authenticated calls to the REST API, which was previously only possible by manually extracting the access token from a cookie in the browser.

Show access token in REST explorer

---

packages/composer-website/jekylldocs/tutorials/developer-guide.md

Tidy up unit test example code in developer guide

---

README.md

Fix how to raise issues link in readme

---

.travis/before-install.sh

Use --user flag when installing linkchecker

---

packages/composer-playground/src/app/test/registry/registry.component.spec.ts
packages/composer-playground/src/app/test/registry/registry.component.ts

Updated to stop showing error if escape is pressed
contributes to hyperledger/composer#1896

Fix View Transaction Dialog

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.spec.ts
packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.ts
packages/composer-playground/src/app/login/create-identity-card/create-identity-card.component.scss
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.html
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.scss
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.spec.ts
packages/composer-playground/src/app/login/edit-card-credentials/edit-card-credentials.component.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/composer-playground/src/app/test/resource/resource.component.html
packages/composer-playground/src/app/test/resource/resource.component.scss
packages/composer-playground/src/app/test/transaction/transaction.component.html
packages/composer-playground/src/assets/styles/composer.scss
packages/composer-playground/src/assets/styles/elements/_checkbox-button.scss

Added the ability to add roles when creating an identity card
Added styles for checkbox
contributes to hyperledger/composer#2032

Add roles when creating identities

---

packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.scss

Fix layout issues on safari

---

packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts
packages/composer-playground/src/app/test/test.component.spec.ts

Increased test coverage in clent service to 100% - needed to alter the main code to include switch/case in a few placed to ensure branch coverage.
Test component is reaching a limit as we're testing callbacks placed in there now!
Component of #2019

increase test coverage client service and test component

---

packages/composer-playground/src/app/test/resource/resource.component.html

Show registry ID in resource modal

---

packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js

Remove the connector.update unrequired methods in the Web and Proxy connectors

remove connector.update

---

packages/composer-cli/test/archive/archive.js
packages/composer-cli/test/archive/create.js
packages/composer-cli/test/archive/list.js
packages/composer-cli/test/cli.js
packages/composer-cli/test/generator/generator.js
packages/composer-cli/test/identity/identity.js
packages/composer-cli/test/network/network.js
packages/composer-cli/test/network/update.js
packages/composer-cli/test/participant/participant.js
packages/composer-cli/test/runtime/runtime.js
packages/composer-cli/test/shell/shelljs.js
packages/composer-cli/test/transaction/transaction.js

Test Debt for CLI

---

packages/composer-common/lib/_template/systemmodel.njk
packages/composer-common/lib/businessnetworkdefinition.js
packages/composer-common/lib/introspect/modelfile.js
packages/composer-common/lib/introspect/parseexception.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/package.json
packages/composer-common/scripts/systemmodelgen.js
packages/composer-common/test/acl/aclrule.js
packages/composer-common/test/acl/modelbinding.js
packages/composer-common/test/businessnetworkdefinition.js
packages/composer-common/test/connection.js
packages/composer-common/test/data/parser/classdeclaration.good.nested.cto
packages/composer-common/test/data/parser/validation.cto
packages/composer-common/test/data/zip/empty-archive/package.json
packages/composer-common/test/introspect/classdeclaration.js
packages/composer-common/test/introspect/eventdeclaration.js
packages/composer-common/test/introspect/field.js
packages/composer-common/test/introspect/numbervalidator.js
packages/composer-common/test/introspect/parseexception.js
packages/composer-common/test/introspect/transactiondeclaration.js
packages/composer-common/test/log/logger.js
packages/composer-common/test/modelmanager.js
packages/composer-common/test/query/limit.js
packages/composer-common/test/query/skip.js
packages/composer-common/test/query/where.js
packages/composer-common/test/query/whereastvalidator.js
packages/composer-common/test/querymanager.js

This has updated the composer-common to 100% codecoverage, and set the values now to that level.
This has NOT removed any of the  exclusions however. 
It has also fixed a couple of code issues along the way that where highlighted when adding tests.
Note these updates are purely coverage tests, not functional.

Codecoverage

---

packages/composer-playground/.istanbul.yml
packages/composer-playground/src/app/version-check/version-check.component.spec.ts
packages/composer-playground/src/app/version-check/version-check.component.ts

Make sure idcard data is cleared along with other local storage

---

packages/composer-cli/lib/cmds/identity/lib/bind.js
packages/composer-cli/lib/cmds/identity/lib/issue.js
packages/composer-cli/lib/cmds/identity/lib/list.js
packages/composer-cli/lib/cmds/identity/lib/revoke.js
packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/network/lib/download.js
packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/lib/cmds/network/lib/loglevel.js
packages/composer-cli/lib/cmds/network/lib/ping.js
packages/composer-cli/lib/cmds/network/lib/undeploy.js
packages/composer-cli/lib/cmds/participant/lib/add.js
packages/composer-cli/lib/cmds/transaction/lib/submit.js
packages/composer-cli/test/network/deploy.js

Return values of prompt module are an object rather than the actual field. 
Hence they need to be properly dereferecned.

correct use of return values of prompt

---

packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/lib/serializer.js
packages/composer-common/lib/serializer/resourcevalidator.js
packages/composer-common/test/serializer.js
packages/composer-runtime/test/registrymanager.js

Parser does not validate JSON data against model #2257
1.
2.
3.
4.

Validate resources during parsing in fromJSON (resolves #2257)

---

.travis/before-install.sh
packages/composer-website/jekylldocs/business-network/query.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/js_scripts.md

Documentation on filters 

---

packages/composer-common/lib/codegen/fromcto/typescript/typescriptvisitor.js
packages/composer-common/lib/codegen/fromjs/plantumlgenerator.js
packages/composer-common/lib/codegen/jsonwriter.js
packages/composer-common/package.json
packages/composer-common/test/codegen/_template.js
packages/composer-common/test/codegen/filewriter.js
packages/composer-common/test/codegen/fromjs/apisignaturegenerator.js
packages/composer-common/test/codegen/fromjs/jsonsignaturegenerator.js
packages/composer-common/test/codegen/fromjs/platumlgenerator.js
packages/composer-common/test/codegen/golangvisitor.js
packages/composer-common/test/codegen/javascriptparser.js
packages/composer-common/test/codegen/jsonwriter.js
packages/composer-common/test/codegen/parsejs.js
packages/composer-common/test/codegen/plantumlvisitor.js
packages/composer-common/test/codegen/typescriptvisitor.js
packages/composer-common/test/codegen/writer.js

Provides additional coverage for #1495 
Exclusions are still in place to permit the coverage to remain at 100% - but removing those it's at around 98%

Code coverage - partly fixes #1495

---

packages/composer-playground/src/app/editor/editor-file/editor-file.component.spec.ts
packages/composer-playground/src/app/editor/editor-file/editor-file.component.ts
packages/composer-playground/src/app/services/client.service.spec.ts
packages/composer-playground/src/app/services/client.service.ts

#2247 
Pull request to fix issue of pakage.json not being editable.
Code Changes:
- Added listener in switch for package type
- Updated editor component to pass package type 
- Updated tests to reflect changes
- Manually verified fix worked on playground local build

Bug fix for pakage.json editor (Issue 2247)

---

packages/composer-website/jekylldocs/_includes/footerbar.html
packages/composer-website/jekylldocs/applications/node.md
packages/composer-website/jekylldocs/business-network/bnd-deploy.md
packages/composer-website/jekylldocs/business-network/historian.md
packages/composer-website/jekylldocs/business-network/query.md
packages/composer-website/jekylldocs/playground/id-cards-playground.md
packages/composer-website/jekylldocs/playground/playground-index.md
packages/composer-website/jekylldocs/problems/deployment-local-playground.md
packages/composer-website/jekylldocs/reference/JSDOC-README.md
packages/composer-website/jekylldocs/reference/historian.md
packages/composer-website/jekylldocs/reference/query-language.md
packages/composer-website/jekylldocs/tutorials/developer-guide.md
packages/composer-website/jekylldocs/tutorials/playground-guide.md
packages/composer-website/jekylldocs/tutorials/queries.md

This addresses the following documentation issues
https://github.com/hyperledger/composer/issues/2326  broken api link
https://github.com/hyperledger/composer/issues/1801 quote mismatch
https://github.com/hyperledger/composer/issues/2147 queries tutorial
https://github.com/hyperledger/composer/issues/2319 0.14.0 release work

Various documentation updates

---

packages/composer-playground/src/app/import/deploy.component.spec.ts
packages/composer-playground/src/app/import/import.component.ts
packages/composer-playground/src/app/import/update.component.spec.ts

#2149 
Fix for being unable to import own bna file

fix for file import problem

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/card/deleteCommand.js
packages/composer-cli/lib/cmds/card/lib/delete.js
packages/composer-cli/test/card/delete.js

Add 'composer card delete' command

---

packages/composer-connector-hlfv1/package.json
scripts/depcheck.js

Also relaxes the exact version checks for this dependency only
Closes #2361

Update grpc work around dependency to match fabric

---

packages/composer-cli/lib/cmds/network/deployCommand.js
packages/composer-cli/lib/cmds/network/lib/list.js
packages/composer-cli/lib/cmds/network/listCommand.js
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/package.json
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/lib/idcard.js
packages/composer-common/test/connectionprofilemanager.js

added in a connectWithCard API to support the clis

---

packages/composer-systests/hlfv1/docker-compose.tls.yml
packages/composer-systests/hlfv1/docker-compose.yml
packages/composer-systests/scripts/run-system-tests.sh

As per issue
https://github.com/hyperledger/composer/issues/2489

Upgrade system tests to Fabric 1.0.3

---

packages/composer-admin/lib/adminconnection.js
packages/composer-cli/cli.js
packages/composer-cli/lib/cmds/participant/addCommand.js
packages/composer-cli/lib/cmds/participant/lib/add.js
packages/composer-cli/test/participant/add.js
packages/composer-cli/test/participant/participant.js
packages/composer-rest-server/test/filter.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Story2335 participant cli

---

packages/composer-common/lib/connectionmanager.js
packages/composer-connector-embedded/lib/embeddedconnectionmanager.js
packages/composer-connector-embedded/test/embeddedconnectionmanager.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-connector-web/lib/webconnectionmanager.js
packages/composer-connector-web/test/webconnectionmanager.js

Handle null when obtaining credentials from Fabric Client

---

packages/composer-common/lib/cardstore/businessnetworkcardstore.js
packages/composer-common/lib/cardstore/filesystemcardstore.js
packages/composer-common/test/cardstore/filesystemcardstore.js

Make 'composer card import' fail if card previously imported

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-systests/systest/testutil.js

Update to new node sdk apis

---

packages/composer-cli/lib/cmds/card/createCommand.js
packages/composer-cli/lib/cmds/card/lib/create.js
packages/composer-cli/test/card/card.js
packages/composer-cli/test/card/create.js
packages/composer-common/lib/idcard.js

1) Options as per the story added
2) Using the fn form of the yargs handler to allow for using the check fn to give better control over the roles property

Story2487 card create

---

packages/composer-connector-hlfv1/package.json

Fix grpc level to 1.6.6

---

packages/composer-website/jekylldocs/installing/development-tools.md

update docs to be more specific about node 8

---

packages/composer-cli/lib/cmds/card/createCommand.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/runtime/installCommand.js

Issue2579 composer runtime cli

---

packages/composer-website/jekylldocs/installing/development-tools.md

Update development environment install doc for cards

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/network/lib/deploy.js
packages/composer-cli/lib/cmds/network/lib/start.js

Remove 'update' parameter from AdminConnection.connect

---

packages/composer-cli/lib/cmds/card/lib/list.js
packages/composer-cli/lib/cmds/card/listCommand.js
packages/composer-cli/test/card/list.js

As per discussion with @EdMoffatt Update to the card list output 
and a single option to list a given card.

Card list improvements

---

packages/composer-cli/docker/Dockerfile
packages/composer-cli/docker/Dockerfile.ppc64le
packages/composer-playground/docker/Dockerfile
packages/composer-playground/docker/Dockerfile.ppc64le
packages/composer-rest-server/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile.ppc64le

fix builds due to docker failure

---

packages/composer-cli/lib/cmds/card/exportCommand.js
packages/composer-cli/lib/cmds/card/lib/export.js
packages/composer-cli/test/card/export.js

The default file name is based on the card name.

Make 'file' parameter to 'composer card export' optional

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js

If no secret is provided then assuming a default; limitation of the current APIs.

Update to fix the no secret bug

---

packages/composer-playground/src/app/identity/identity-issued/identity-issued.component.html

Removed option 3 as it no longer makes sense
closes hyperledger/composer#2644

Update identity issued

---

packages/composer-cli/lib/cmds/card/lib/create.js
packages/composer-cli/test/card/create.js

convert single role argument to array for card create command

---

packages/composer-common/lib/cardstore/filesystemcardstore.js
packages/composer-common/test/data/card-store/invalid/i-am-not-a-card

Ignore spurious content in file system card store directory

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js

This addresses a small timing window where we could miss a transaction event in the hlfv1 connector.
closes issue https://github.com/hyperledger/composer/issues/2399

Address small timing window opportunity in hlfv1

---

packages/composer-common/lib/cardstore/businessnetworkcardstore.js
packages/composer-common/lib/cardstore/memorycardstore.js
packages/composer-common/test/cardstore/memorycardstore.js

Resolves #2698 
Clarify the contract for BusinessNetworkCardStore.get() in JSDoc.

MemoryCardStore.get() throws for non-existent card

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

This adds the capability to better decide what to do about bad responses rather than just blanket throw error if any problem is encountered. We filter out the good responses and send those to the orderer.
This addresses the issue https://github.com/hyperledger/composer/issues/2668

Intelligent handling of responses from Peer

---

packages/composer-cli/lib/cmds/network/lib/reset.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/lib/cmds/network/lib/undeploy.js
packages/composer-cli/test/network/reset.js
packages/composer-cli/test/network/start.js
packages/composer-cli/test/network/undeploy.js

fix lost error message because spinner not defined.

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/card/lib/import.js
packages/composer-cli/lib/cmds/identity/lib/request.js
packages/composer-cli/lib/cmds/identity/requestCommand.js
packages/composer-cli/test/card/import.js
packages/composer-cli/test/identity/request.js

Updated the identity request command fixes #2701

---

packages/composer-common/lib/codegen/fromcto/loopback/loopbackvisitor.js
packages/composer-rest-server/test/filter.js
packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

code changes for #2479
Signed-off-by: xufengli <xufengli@uk.ibm.com>

update code and tests

---

packages/composer-website/jekylldocs/applications/web.md
packages/composer-website/jekylldocs/business-network/historian.md
packages/composer-website/jekylldocs/installing/development-tools.md
packages/composer-website/jekylldocs/installing/getting-started-with-playground.md
packages/composer-website/jekylldocs/installing/using-playground-locally.md
packages/composer-website/jekylldocs/playground/id-cards-playground.md
packages/composer-website/jekylldocs/playground/playground-index.md
packages/composer-website/jekylldocs/reference/historian.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/developer-tutorial.md
packages/composer-website/jekylldocs/tutorials/playground-tutorial.md
packages/composer-website/jekylldocs/tutorials/queries.md
packages/composer-website/jekylldocs/tutorials/tutorials.md

Signed-off-by: EdProsser <edward.prosser@uk.ibm.com>

2679, 2200, 2530, 1821, 2477, 2563

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/docker/Dockerfile
packages/composer-playground/docker/Dockerfile
packages/composer-playground/src/app/footer/footer.component.html
packages/composer-rest-server/docker/Dockerfile
packages/composer-website/jekylldocs/reference/connectionprofile.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/developer-tutorial.md
packages/composer-website/jekylldocs/tutorials/queries.md

Fixes required for release:
- docker images did not have correct versions in
- broken tutorial link in playground
- doc updates
- idcard fix

Release fixes

---

contrib-notes/release-process/guide-validation.md
packages/composer-playground/src/app/common/identity-card/identity-card.component.html
packages/composer-playground/src/app/common/tutorial-link/tutorial-link.component.html

Resolve #2754 
Solve broken links to tutorials.

Fix broken link to tutorials

---

packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts

Changed so that when you have an error in one file and that is fixed by changing another file. The unchanged file will also be pushed to the business network
closes hyperledger/composer#2648

Updated Editor Validation

---

packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md

Resolves #2773 
How the page is now:
After this PR:

Fix formatting in tutorial

---

packages/composer-playground-api/routes/npm.js

Adding config to the npm client to reduce retry count and reduce max timeout
contributes to hyperledger/composer#2742

Fix sample loading when no internet connection

---

.travis/deploy.sh
packages/composer-playground/src/app/app.component.spec.ts
packages/composer-playground/src/app/app.component.ts
packages/composer-playground/src/index.html

Fixed so that we now record each page you visit
Made the analytics id be configurable
closes hyperledger/composer#2779

Fix Google Analytics

---

packages/composer-playground/src/app/login/create-identity-card/create-identity-card.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts

Put hlfv1 profiles before the web one
closes hyperledger/composer#2797

Reorder connection profiles

---

packages/composer-playground/src/app/connection-profile/connection-profile.component.html
packages/composer-playground/src/app/connection-profile/connection-profile.component.spec.ts
packages/composer-playground/src/app/connection-profile/connection-profile.component.ts

Remove keyValStore from connection profile page as per issue #2675 
Signed-off-by: K. L. Usher <kai.usher@ibm.com>

#2675 - remove keyValStore from connection profile page

---

packages/generator-hyperledger-composer/generators/businessnetwork/index.js
packages/generator-hyperledger-composer/generators/businessnetwork/templates/package.json
packages/generator-hyperledger-composer/generators/businessnetwork/templates/test/logic.js

Update Yo generated basic sample network for new install/start API

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-cli/lib/cmds/network/lib/start.js
packages/composer-cli/test/network/deploy.js
packages/composer-cli/test/network/start.js
packages/composer-connector-server/package.json
packages/composer-cucumber-steps/lib/composer.js
packages/composer-playground/src/app/services/samplebusinessnetwork.service.spec.ts
packages/composer-playground/src/app/services/samplebusinessnetwork.service.ts
packages/composer-rest-server/package.json
packages/composer-rest-server/test/assets.js
packages/composer-rest-server/test/authentication.js
packages/composer-rest-server/test/events.js
packages/composer-rest-server/test/filter.js
packages/composer-rest-server/test/multiuser.js
packages/composer-rest-server/test/participants.js
packages/composer-rest-server/test/queries.js
packages/composer-rest-server/test/root.js
packages/composer-rest-server/test/server/boot/composer-discovery.js
packages/composer-rest-server/test/server/server.js
packages/composer-rest-server/test/system.js
packages/composer-rest-server/test/transactions.js
packages/generator-hyperledger-composer/generators/cli/templates/package.json
packages/generator-hyperledger-composer/test/angular-network.js
packages/loopback-connector-composer/test/assets.js
packages/loopback-connector-composer/test/events.js
packages/loopback-connector-composer/test/participants.js
packages/loopback-connector-composer/test/transactions.js

Change to secret to enrollmentSecret for the network admins
Also change the yargs dependancy in some package.json so they are all the same.
resolves #2809

Change secret enrollment secret

---

packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-playground/src/app/common/identity-card/identity-card.component.html
packages/composer-playground/src/app/common/identity-card/identity-card.component.spec.ts
packages/composer-playground/src/app/common/identity-card/identity-card.component.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/services/identity-card.service.spec.ts
packages/composer-playground/src/app/services/identity-card.service.ts

Fixed deleting of cards
Fixed deploy sample
Fixed undeploy to only do it from login card delete
contributes to hyperledger/composer#2813

Playground Fixes

---

packages/composer-website/jekylldocs/applications/node.md
packages/composer-website/jekylldocs/business-network/bnd-deploy.md
packages/composer-website/jekylldocs/index.html
packages/composer-website/jekylldocs/integrating/call-out.md
packages/composer-website/jekylldocs/integrating/enabling-multiuser.md
packages/composer-website/jekylldocs/integrating/enabling-rest-authentication.md
packages/composer-website/jekylldocs/integrating/getting-started-rest-api.md
packages/composer-website/jekylldocs/integrating/node-red.md
packages/composer-website/jekylldocs/integrating/publishing-events.md
packages/composer-website/jekylldocs/managing/id-cards-playground.md
packages/composer-website/jekylldocs/managing/identity-bind.md
packages/composer-website/jekylldocs/managing/identity-issue.md
packages/composer-website/jekylldocs/managing/identity-list.md
packages/composer-website/jekylldocs/managing/identity-revoke.md
packages/composer-website/jekylldocs/managing/participant-add.md
packages/composer-website/jekylldocs/playground/id-cards-playground.md
packages/composer-website/jekylldocs/problems/diagnostics.md
packages/composer-website/jekylldocs/reference/composer.identity.bind.md
packages/composer-website/jekylldocs/reference/connectionprofile.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/tutorials.md

Signed-off-by: EdProsser <edward.prosser@uk.ibm.com>
#2737 #2686 #2077

Multi-org tutorial, last id cards removal, code sample corrections, last two p2 docs bugs.

---

packages/composer-cli/lib/cmds/archive.js
packages/composer-cli/lib/cmds/card.js
packages/composer-cli/lib/cmds/generator.js
packages/composer-cli/lib/cmds/identity.js
packages/composer-cli/lib/cmds/network.js
packages/composer-cli/lib/cmds/participant.js
packages/composer-cli/lib/cmds/runtime.js
packages/composer-cli/lib/cmds/transaction.js
packages/composer-cli/test/archive/archive.js
packages/composer-cli/test/card/card.js
packages/composer-cli/test/generator/generator.js
packages/composer-cli/test/identity/identity.js
packages/composer-cli/test/network/network.js
packages/composer-cli/test/participant/participant.js
packages/composer-cli/test/runtime/runtime.js
packages/composer-cli/test/transaction/transaction.js

Signed-off-by: Ellis Henderson <ellis.henderson@ibm.com>
1.
2.
3.
4.

Removed .fail and put message to be thrown within demandCommand.

---

packages/composer-website/jekylldocs/integrating/deploying-the-rest-server.md
packages/composer-website/jekylldocs/integrating/enabling-multiuser.md
packages/composer-website/jekylldocs/reference/glossary.md
packages/composer-website/jekylldocs/reference/rest-server.md

Docs for Deploying the REST server for a business network need updating for cards #2654
Also split out the reference style stuff into an actual reference topic as discussed with @EdProsser.

Update documentation for deploying the REST server

---

packages/composer-playground/src/app/login/login.component.spec.ts
packages/composer-playground/src/app/login/login.component.ts
packages/composer-playground/src/app/version-check/version-check.component.spec.ts
packages/composer-playground/src/app/version-check/version-check.component.ts
packages/composer-website/jekylldocs/index.html

Updated version check to remove indexDb's
Updated login to not deploy if more than one identity exists for a web business network

Fix playground problems

---

packages/composer-playground/src/app/footer/footer.component.html
packages/composer-playground/src/app/footer/footer.component.spec.ts
packages/composer-playground/src/app/services/config.service.spec.ts
packages/composer-playground/src/app/services/config/configStructure.service.spec.ts
packages/composer-playground/src/app/services/config/configStructure.service.ts
packages/composer-website/jekylldocs/_includes/sidebars/accordion-toc0.md

Also includes improvement to doc website navigation
Contributes to #2882

Add legal link to configuration data

---

.gitignore
packages/composer-playground/.gitignore
packages/composer-playground/package.json
packages/composer-playground/src/app/services/about.service.spec.ts
packages/composer-playground/src/app/services/about.service.ts

Simplify code to get playground version in about service

---

.travis/deploy.sh
.travis/deploy_docs.sh
.travis/script.sh
packages/composer-website/jekylldocs/_config.yml
packages/composer-website/jekylldocs/_latest.yml
packages/composer-website/jekylldocs/_stable.yml
packages/composer-website/jekylldocs/_unstable.yml
packages/composer-website/package.json
packages/composer-website/scripts/linkcheck.sh

Move the code to support the stable/unstable/latest docs.
Ideally this should have gone first!
Part resolves #2886

Support stable, unstable, and latest docs

---

packages/composer-tests-integration/.eslintrc.yml
packages/composer-tests-integration/features/rest.feature
packages/composer-tests-integration/lib/reststeps.js

Condense all the CLI steps required to setup and start a REST API server for a given BNA file into a single 'Given' step in cucumber.
fixes #2964 
1.
2.
3.
4.

Create new "Given" step for setting up REST server"

---

.travis.yml
.travis/deploy.sh

The travis.yml file doesn't appear to be able to cope with branches of the syntax v0.16.x

Deploy v0.16.x branch

---

packages/generator-hyperledger-composer/generators/angular/templates/package.json

Change from `-N -P` to `-n -p`

resolves #2986 - fix options on the rest server cmd line

---

.travis/deploy.sh
.travis/script.sh

Use regexp in the comparison of the branch name.
```
elif [[ "${TRAVIS_BRANCH}" =~ v0\.16\.[0-9]{1,2} ]]; then
```

resolves #2990 - regexp for the travis branch matching

---

.travis/before-install.sh
.travis/deploy.sh
.travis/deploy_docs.sh
.travis/install.sh
.travis/script.sh
packages/composer-website/jekylldocs/_latest.yml
packages/composer-website/jekylldocs/_next-unstable.yml
packages/composer-website/jekylldocs/_next.yml
packages/composer-website/jekylldocs/_stable.yml
packages/composer-website/package.json
packages/composer-website/scripts/linkcheck.sh

first drop of new os build scripts

---

contrib-notes/coding-guidelines.md

fix minor mistake in contrib notes

---

.travis/before-install.sh

Remove the workaround for a travis problem - not required now Travis has updated their docker images.

Fix build breaks

---

packages/loopback-connector-composer/lib/businessnetworkconnector.js
packages/loopback-connector-composer/test/businessnetworkconnector.js

Update both test code and source code for #2145
Signed-off-by: xufengli <xufengli@uk.ibm.com>

update test code and add a validation in source code

---

.travis/base.sh
.travis/before-install.sh
.travis/deploy.sh

Master build updates

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-website/jekylldocs/business-network/bnd-deploy.md
packages/composer-website/jekylldocs/integrating/deploying-the-rest-server.md
packages/composer-website/jekylldocs/integrating/integrating-index.md
packages/composer-website/jekylldocs/introduction/key-concepts.md
packages/composer-website/jekylldocs/introduction/solution-architecture.md
packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/managing/participantsandidentities.md
packages/composer-website/jekylldocs/problems/diagnostics.md
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md
packages/composer-website/jekylldocs/reference/connectionprofile.md

fixAndDocs

---

packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js

fix request identity

---

packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md

Updated tutorials for CCP

---

.gitignore
packages/composer-playground/.gitignore
packages/composer-playground/package.json
packages/composer-playground/src/app/footer/footer.component.spec.ts
packages/composer-playground/src/app/services/about.service.spec.ts
packages/composer-playground/src/app/services/about.service.ts

Simplify code to get playground version in about service (#2941)

---

packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js

Add transaction id logging to node.js chaincode logging

---

packages/composer-client/index.js
packages/composer-playground/src/app/identity/issue-identity/issue-identity.component.spec.ts

Signed-off-by: Sai Chaitanya <saichaitanya88@gmail.com>
Please update ParticipantRegisty to ParticipantRegistry.
Hoping to pass DCO requirements this time.

ParticipantRegisty typo fix

---

packages/composer-common/lib/log/logger.js
packages/composer-common/test/log/logger.js

contributes to https://github.com/hyperledger/composer/issues/3073

fix unable to set logging dynamically

---

contrib-notes/getting-started.md

typo: missing space

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js

Business network hash in runtime changes for every deployment #3105
1.
2.
3.
4.

Force BNA timestamps on start/deploy/update (resolves #3105, v0.16.x)

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js

Business network hash in runtime changes for every deployment #3105
1.
2.
3.
4.

Force BNA timestamps on start/deploy/update (resolves #3105, v0.17.x)

---

packages/composer-runtime-hlfv1/loggingservice.go

Contributes to https://github.com/hyperledger/composer/issues/3073

Add Short Tx id to logging

---

packages/composer-rest-server/test/data/bond-network/queries.qry
packages/composer-rest-server/test/filter.js
packages/composer-rest-server/test/queries.js
packages/composer-runtime/lib/querycompiler.js
packages/composer-runtime/test/querycompiler.js

both code and test for fixing issue #2978 
Signed-off-by: xufengli <xufengli@uk.ibm.com>

fixes to support complex and/or operators for both couch and pouch db

---

.travis/before-install.sh

Re-applying the fix as in https://github.com/hyperledger/composer/pull/2318/files
For the latest mongo versions

fixes:3138 by removing mongo regisitry entry

---

packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md

Couple of quick fixes for docs errors from @samjsmith and @bestbeforetoday

fixes for 0.17 release

---

packages/composer-rest-server/public/lib/loadSwaggerUI.js

This backs out the change in PR https://github.com/hyperledger/composer/pull/2834 to resolve issue #3116 
1.
2.
3.
4.

backout fix for 2647 to restore ability to issue id from explorer

---

.travis/deploy.sh

deploy composer-playground
Contributes to #3153

Remove node_modules directory before attempting to

---

.travis/deploy.sh

Closes #3128
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>

Change version bump to go to stream 0.16.x

---

packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md

fixes and improvements to byfn tutorial

---

.travis/deploy.sh

Remove node_modules directory before attempting to deploy composer-playground

---

packages/composer-cli/lib/cmds/report/lib/report.js
packages/composer-cli/test/report/report.js
packages/composer-common/package.json
packages/composer-report/.editorconfig
packages/composer-report/.eslintignore
packages/composer-report/.eslintrc.yml
packages/composer-report/LICENSE.txt
packages/composer-report/bin/cmd.js
packages/composer-report/header.txt
packages/composer-report/lib/report.js
packages/composer-report/package.json
packages/composer-report/test/cmd.js
packages/composer-report/test/report.js

Initial report module

---

packages/composer-report/README.md
packages/composer-website/jekylldocs/reference/MeetTheModules.md
packages/composer-website/jekylldocs/reference/composer.report.md

Also includes updated documentation to explain the new module

Add readme for new composer-report module

---

packages/composer-playground/src/app/login/create-identity-card/create-identity-card.component.html

#3247 
Updated login card create to reference HLFV1.1

Changed HLV1.0 reference in card create to HLV1.1

---

packages/composer-playground/src/app/services/config/configStructure.service.spec.ts
packages/composer-playground/src/app/services/config/configStructure.service.ts
packages/composer-website/jekylldocs/applications/node.md
packages/composer-website/jekylldocs/business-network/historian.md
packages/composer-website/jekylldocs/index.html
packages/composer-website/jekylldocs/tutorials/playground-tutorial.md

Doc fixes and playground links

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js

Add card to store on import only if identity import is successful

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-cli/lib/cmds/network/lib/upgrade.js
packages/composer-cli/lib/cmds/network/upgradeCommand.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-website/jekylldocs/managing/updating-composer.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md

The fixes the fact that `composer network upgrade` just doesn't work.
contributes to #2891

Upgrade fix

---

packages/composer-website/jekylldocs/index.html

Update Banner to point to next

---

packages/composer-playground/.gitignore
packages/composer-playground/cli.js
packages/composer-playground/package.json

Add Composer config option to specify a Usabilla code template to include at the end of the playground index page
Contributes to #3334

Add Usabilla feedback/tracking option

---

CONTRIBUTING.md
contrib-notes/coding-guidelines.md
contrib-notes/ide-setup.md
contrib-notes/submitting-pull-request.md

Fixed all occurrences of 'developement' to 'development'. Continued the job of #3256

Fixed typos

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-cli/lib/cmds/network/lib/upgrade.js
packages/composer-cli/lib/cmds/network/upgradeCommand.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-website/jekylldocs/managing/updating-composer.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md

Fix upgrade and add endorsement policy support

---

CONTRIBUTING.md
contrib-notes/getting-started.md
contrib-notes/prerequisites-ubuntu.md
contrib-notes/prerequisites.md
contrib-notes/submitting-pull-request.md
packages/composer-website/jekylldocs/reference/acl_language.md
packages/composer-website/jekylldocs/reference/connectionprofile.md

- minor update requested for the connection profile doc
- added in information about softhsm for contributors guide (and brought it upto date on pre-reqs)
- changed acl information about CLI commands replaced deploy with start.

Documentation updates for HSM

---

.travis.yml
.travis/before-install.sh
CONTRIBUTING.md
contrib-notes/getting-started.md
contrib-notes/submitting-pull-request.md
packages/composer-admin/lib/adminconnection.js
packages/composer-cli/lib/cmds/card/createCommand.js
packages/composer-cli/lib/cmds/card/lib/list.js
packages/composer-cli/lib/cmds/identity/lib/request.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/package.json
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-tests-functional/package.json
packages/composer-tests-functional/systest/identities.js
packages/composer-tests-functional/systest/testutil.js
packages/composer-tests-integration/features/cli.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/package.json
packages/composer-tests-integration/profiles/basic-connection-org1-hsm.json
packages/composer-tests-integration/scripts/run-integration-tests.sh
packages/composer-website/jekylldocs/reference/composer.card.create.md
packages/composer-website/jekylldocs/reference/composer.identity.issue.md
packages/composer-website/jekylldocs/reference/composer.network.deploy.md
packages/composer-website/jekylldocs/reference/composer.network.start.md
packages/composer-website/jekylldocs/reference/connectionprofile.md

Hsm reloaded

---

packages/composer-cli/lib/cmds/network/lib/loglevel.js

Fix the output of setLoglevel Cmd

---

packages/composer-website/jekylldocs/index.html
packages/composer-website/jekylldocs/reference/connectionprofile.md

Website Fixes

---

packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/reference/composer.network.start.md
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md

add info about endorsement policies for upgrade

---

packages/composer-cli/lib/cmds/report/lib/report.js
packages/composer-cli/test/report/report.js
packages/composer-report/.gitignore
packages/composer-report/bin/cmd.js
packages/composer-report/lib/report.js
packages/composer-report/package.json
packages/composer-report/test/cmd.js
packages/composer-report/test/report.js
packages/composer-tests-integration/features/cli.feature

Include composer-report version in reports

---

packages/composer-common/lib/modelmanager.js
packages/composer-common/test/modelmanager.js

better modelmanager error messages

---

packages/composer-website/jekylldocs/applications/web.md
packages/generator-hyperledger-composer/generators/angular/templates/README.md
packages/generator-hyperledger-composer/generators/angular/templates/e2e/app.e2e-spec.ts
packages/generator-hyperledger-composer/generators/angular/templates/src/app/app.component.css
packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.html

Fixes for the issues raised when testing the Angular generator.
- Lorem ipsum text (#3448) 
- ReadMe
- e2e

Nitpicks for the angular generator changes

---

.travis/deploy.sh

check for all published npm modules prior to docker build

---

packages/generator-hyperledger-composer/generators/angular/templates/e2e/app.e2e-spec.ts

Update angular e2e test

---

packages/composer-tests-integration/lib/composer.js

Improve error capture checking stderr/stdout

---

.travis/deploy_docs.sh

add in the correct tag

---

.travis/deploy.sh

update travis build to wait for all npm modules to be published

---

packages/composer-cli/test/card/list.js
packages/composer-common/api.txt
packages/composer-common/changelog.txt
packages/composer-common/index.js
packages/composer-common/lib/certificate.js
packages/composer-common/lib/certificateutil.js
packages/composer-common/test/certificate.js
packages/composer-common/test/certificateutil.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/lib/embeddedconnectionmanager.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnectionmanager.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/lib/webconnectionmanager.js
packages/composer-connector-web/test/webconnection.js
packages/composer-connector-web/test/webconnectionmanager.js
packages/composer-playground/config/karma.conf.js
packages/composer-rest-server/test/system.js
packages/composer-runtime-hlfv1/lib/nodeidentityservice.js
packages/composer-runtime-hlfv1/test/nodeidentityservice.js
packages/composer-runtime/lib/identitymanager.js
packages/composer-runtime/test/identitymanager.js
packages/composer-tests-functional/systest/identities.js
packages/generator-hyperledger-composer/generators/angular/index.js
packages/generator-hyperledger-composer/test/angular-network.js

Business network cards; operationally, what is the process when an identity's certificate expires? #3036
This is an enablement change for #3036.
When using re-enroll in Hyperledger Fabric, the existing public key of the user is sent to the CA and a new certificate is issued. The new certificate does not match the old certificate (due to the new validity period, amongst other things), and so the new certificate no longer matches the identifier of the identity in the identity registry.
This change uses the public key (embedded in the certificate) as the identifier of the identity in the identity registry, which will not change across re-enroll operations, solving the problem above. The new certificate will have the existing private key, which will still match the identifier of the identity …

Use public key instead of certificate as identifier for identities

---

.travis/deploy.sh

Contributes to #3128
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>

Fix automatic version bump for v0.16.x branch (#3128)

---

packages/composer-cli/lib/cmds/card/lib/schema/ccpschema.json
packages/composer-common/lib/cardstore/businessnetworkcardstore.js
packages/composer-common/test/cardstore/businessnetworkcardstore.js

Added pem to signedCert property
Updated invalid connection profile names
contributes to hyperledger/composer#3506

Fixes for start plan

---

packages/composer-website/jekylldocs/business-network/cloud-wallets.md

I don’t like sand. It’s coarse and rough and irritating and it gets everywhere.
Also docs.

Cloud Wallet Doc, Episode II: Attack of the Git Clones

---

packages/composer-connector-hlfv1/package.json

Upgrade to Hyperledger Fabric v1.1.0-snapshot.83/85 (client)

---

.travis/before-install.sh
packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-common/lib/cardstore/businessnetworkcardstore.js
packages/composer-common/lib/cardstore/walletbackedcardstore.js
packages/composer-common/lib/codegen/parsejs.js
packages/composer-common/lib/wallet.js
packages/composer-common/test/wallet.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/test/connectorserver.js
packages/composer-playground/e2e/fabric/scripts/cleanupFabric.sh
packages/composer-rest-server/lib/loopbackcardstore.js
packages/composer-rest-server/lib/loopbackwallet.js
packages/composer-rest-server/test/lib/loopbackcardstore.js
packages/composer-rest-server/test/lib/loopbackwallet.js
packages/composer-runtime-hlfv1/.npmignore
packages/composer-tests-functional/package.json
packages/composer-tests-integration/.gitignore
packages/composer-tests-integration/features/rest-multiuser.feature
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/lib/reststeps.js
packages/composer-tests-integration/package.json
packages/composer-tests-integration/scripts/npm_serve.js
packages/composer-tests-integration/scripts/run-integration-tests.sh

Cards with certificates imported into the Multi-User Rest Server do not get their certificates or state persisted #3413
1.
2.
3.
4.

Add integration tests for multi user REST server, fix multi user REST server

---

packages/composer-rest-server/lib/loopbackcardstore.js
packages/composer-rest-server/test/lib/loopbackcardstore.js
packages/composer-tests-integration/features/rest-multiuser.feature
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/scripts/ldap.js
packages/composer-tests-integration/scripts/run-integration-tests.sh

Cards with certificates imported into the Multi-User Rest Server do not get their certificates or state persisted #3413
1.
2.
3.
4.

Fix upload of cards with certs in multiuser REST server (resolves #3413)

---

packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js

fix rest server by backing out importCard change

---

packages/composer-connector-hlfv1/package.json

upgrade to node-sdk 1.0.5

---

packages/composer-playground/e2e/fabric/scripts/config.yaml
packages/composer-playground/e2e/fabric/scripts/setupFabric.sh
packages/composer-playground/package.json
packages/composer-tests-functional/scripts/run-fv-tests.sh
packages/composer-tests-functional/verdaccio.cfg
packages/composer-tests-integration/scripts/config.yaml
packages/composer-tests-integration/scripts/run-integration-tests.sh

Try adjusting the maximum fail/retry count for verdaccio/npm

---

packages/composer-playground/package.json

fix the @tappable/types to 0.2.4

---

packages/composer-playground/e2e/test.js
packages/composer-playground/package.json

Contributes to #3574 
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>

Fix tapable and prevent gecko update in 0.16.x (#3574)

---

packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
packages/composer-playground/e2e/specs/round-trip.spec.ts

override default jasmine timeout on e2e test

---

packages/composer-cucumber-steps/package.json

Increase Cucumber test timeouts to avoid build failures

---

packages/composer-connector-hlfv1/package.json
packages/composer-playground/e2e/fabric/hlfv1/docker-compose.yml
packages/composer-playground/e2e/scripts/setupFabric.sh
packages/composer-runtime-hlfv1/package.json
packages/composer-tests-functional/hlfv1/docker-compose.tls.yml
packages/composer-tests-functional/hlfv1/docker-compose.yml
packages/composer-tests-functional/scripts/run-fv-tests.sh
packages/composer-tests-integration/hlfv1/docker-compose.tls.yml
packages/composer-tests-integration/hlfv1/docker-compose.yml
packages/composer-tests-integration/scripts/run-integration-tests.sh
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md

fabric 1.1 ga

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js
packages/composer-playground/e2e/scripts/setupFabric.sh

This implements an initial solution to query reliability
contributes to #2799

Query reliability

---

packages/composer-cli/lib/cmds/card/lib/list.js
packages/composer-cli/test/card/list.js
packages/composer-tests-integration/features/cli-cards.feature
packages/composer-tests-integration/features/cli-hsm.feature

Composer card list improvements around credential information

---

packages/composer-playground/e2e/component/editor.ts
packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
packages/composer-tests-functional/scripts/run-fv-tests.sh

fix e2e tests

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

Added unit test to get coverage of composer-connector-hlfv1 to 100%
1.
2.
3.
4.

add test coverage for index gen

---

packages/composer-common/lib/log/logger.js

Two many underscores

---

packages/composer-cli/lib/cmds/network/lib/upgrade.js
packages/composer-cli/lib/cmds/network/upgradeCommand.js
packages/composer-cli/test/network/upgrade.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/package.json
packages/composer-runtime/test/engine.js
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md

NFD: upgrade improvements

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

NFD: Query fix

---

packages/composer-cli/lib/cmds/card/deleteCommand.js
packages/composer-cli/lib/cmds/card/exportCommand.js
packages/composer-cli/lib/cmds/card/importCommand.js
packages/composer-cli/lib/cmds/card/lib/delete.js
packages/composer-cli/lib/cmds/card/lib/export.js
packages/composer-cli/lib/cmds/card/lib/import.js
packages/composer-cli/lib/cmds/card/lib/list.js
packages/composer-cli/lib/cmds/card/listCommand.js
packages/composer-cli/test/card/delete.js
packages/composer-cli/test/card/export.js
packages/composer-cli/test/card/import.js
packages/composer-cli/test/card/list.js
packages/composer-playground/e2e/utils/cli-helper.ts
packages/composer-tests-integration/features/cli-cards.feature
packages/composer-tests-integration/features/cli-hsm.feature
packages/composer-tests-integration/features/rest-multiuser.feature
packages/composer-tests-integration/lib/composer.js
packages/composer-website/jekylldocs/business-network/bnd-deploy.md
packages/composer-website/jekylldocs/reference/composer.card.delete.md
packages/composer-website/jekylldocs/reference/composer.card.export.md
packages/composer-website/jekylldocs/reference/composer.card.import.md
packages/composer-website/jekylldocs/reference/composer.card.list.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md
packages/composer-website/jekylldocs/tutorials/invoke-composer-network.md

Must go out in 0.19.0 or not at all
closes #2892

Change Composer card CLI options from -n to -c to be consistent

---

packages/composer-tests-integration/features/cli-cards.redis.feature
packages/composer-tests-integration/lib/clisteps.js
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/package.json
packages/composer-tests-integration/resources/cardstore-redis.json
packages/composer-tests-integration/scripts/run-integration-tests.sh

Added additional integration testing; local test run completed. 
Resolves #3678 
/cc @nklincoln @caroline-church

Additional integration tests - using redis

---

packages/composer-common/lib/idcard.js
packages/composer-common/test/idcard.js
packages/composer-tests-integration/features/rest-multiuser.feature
packages/composer-tests-integration/lib/composer.js
packages/composer-tests-integration/lib/reststeps.js
packages/composer-tests-integration/package.json
packages/composer-tests-integration/scripts/ldap.js

- Added in new integration tests for getting REST to issue an identity
- ID card is removing the offending wallet from the connection profile

correction to handling of wallet in cards, and integration tests

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js

Allow a wallet to be configured through the api
contributes to hyperledger/composer#3618

Update Business Network Connection

---

packages/composer-playground/e2e/component/upgrade.ts
packages/composer-playground/e2e/specs/playground-tutorial.spec.ts
packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.html
packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.spec.ts
packages/composer-playground/src/app/editor/editor.component.ts
packages/composer-playground/src/app/editor/editor.module.ts
packages/composer-playground/src/app/editor/upgrade/index.ts
packages/composer-playground/src/app/editor/upgrade/upgrade.component.html
packages/composer-playground/src/app/editor/upgrade/upgrade.component.scss
packages/composer-playground/src/app/editor/upgrade/upgrade.component.spec.ts
packages/composer-playground/src/app/editor/upgrade/upgrade.component.ts
packages/composer-playground/src/assets/styles/components/_dropdown.scss

Allow the PeerAdmin/ChannelAdmin card to be selected when
upgrading business networks on fabric connection
Closes #3241

Add upgrade dialog to playground

---

packages/composer-website/jekylldocs/_data/links.yml
packages/composer-website/jekylldocs/installing/development-tools.md
packages/composer-website/jekylldocs/integrating/deploying-the-rest-server.md
packages/composer-website/jekylldocs/managing/updating-composer.md
packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md

Remove all @next and :next references from docs

---

packages/composer-website/jekylldocs/installing/development-tools.md
packages/composer-website/jekylldocs/installing/installing-prereqs.md
packages/composer-website/jekylldocs/introduction/solution-architecture.md
packages/composer-website/jekylldocs/managing/connector-information.md
packages/composer-website/jekylldocs/reference/composer.card.create.md
packages/composer-website/jekylldocs/reference/composer.transaction.submit.md
packages/composer-website/jekylldocs/reference/connectionprofile.md
packages/composer-website/jekylldocs/reference/cto_language.md
packages/composer-website/scripts/api-doc-index.md.tpl

closes #3683
closes #3615
closes #2861
closes #2798
closes #2006
closes #3222
closes #3156

Minor doc improvements and fixes

---

packages/composer-cli/lib/cmds/card/lib/schema/ccpschema.json
packages/composer-website/jekylldocs/managing/identity-bind.md
packages/composer-website/jekylldocs/reference/composer.archive.create.md

removed the hlfv11 option for x-type as it is not a valid option
also removed x-loggingLevel as it has no relevance to either composer or the node-sdk
corrected the grpc options entry and added receive which is the more likely option to be used.
Doc fixes are
closes #2849
closes #2828
1.
2.
3.
4.

Fix connection profile schema + doc fixes

---

packages/generator-hyperledger-composer/.eslintignore
packages/generator-hyperledger-composer/generators/angular/index.js

fix eslint on generator-hyperledger-composer

---

packages/composer-common/package.json
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-website/jekylldocs/_layouts/default.html

- fixes the docs missing the copy button
closes #3744
- fixes a problem in composer-common missing a dependency in package.json
- fixes a problem in some of the log entries not including method name

Fix doc button, missing composer-common dependency, log entries

---

contrib-notes/coding-guidelines.md
packages/composer-website/jekylldocs/introduction/key-concepts.md

fix coding-guidelines and key concepts

---

packages/composer-common/lib/indexcompiler.js
packages/composer-tests-integration/features/queries.feature
packages/composer-tests-integration/features/rest-apis.feature
packages/composer-tests-integration/resources/sample-networks/queries-network/models/org.acme.biznet.cto
packages/composer-tests-integration/resources/sample-networks/queries-network/queries.qry

The order in which the fields appear in an index has a huge impact on whether that index will get used by a query.  Specifically, indexes can only be used if the query can selects a contiguous range of values from the index.  See comment 3 of this [post](https://stackoverflow.com/questions/47470345/couchdb-mango-queries-and-indexes/47578641#47578641). Since a query that contains a sort (order-by) clause will not work at all if a suitable index cannot be found, I have reordered the fields in the generated index so that 'order-by' fields come before others (e.g. in the 'where' clause).
Resolves #3766 
1.
2.
3.
4.

Reorder index

---

packages/composer-common/lib/log/logger.js
packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/test/composer.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js
packages/composer-tests-integration/features/cli-network.feature

Fix chaincode logging

---

packages/composer-playground/src/app/identity/identity.component.html
packages/composer-playground/src/app/identity/identity.component.scss

Updated to truncate the name
contributes to hyperledger/composer#2246

Fixed long business network name on id page

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

fix AdminConnection list for hlfv1 connections

---

packages/generator-hyperledger-composer/generators/angular/templates/src/app/asset/asset.component.html
packages/generator-hyperledger-composer/generators/angular/templates/src/app/participant/participant.component.html

The page now refreshes when a submission occurs within the generated app (i.e. when you create, update or delete a resource). 
Resolves #3701

Refresh fix for Angular Generator

---

packages/composer-client/lib/businessnetworkconnection.js

Update code example in BusinessNetworkDefinition JSDoc

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-website/jekylldocs/_plugins/link.rb

Updated the regular expressions in the ruby jekyll parsing and corrected some minor tagging issues in the jsdoc comments.

correct api docs with unrendered links

---

packages/composer-common/lib/connection.js
packages/composer-common/lib/connectionmanager.js
packages/composer-common/test/connection.js
packages/composer-common/test/connectionmanager.js

https://github.com/hyperledger/composer/issues/3835
Remove all callback methods, refactor remaining methods and tests with async/await goodness 👍

Remove callback methods from connector API (resolves #3835)

---

packages/composer-runtime/lib/datacollection.js
packages/composer-runtime/lib/dataservice.js
packages/composer-runtime/lib/service.js
packages/composer-runtime/test/datacollection.js
packages/composer-runtime/test/dataservice.js
packages/composer-runtime/test/service.js

Remove redundant callback code from the runtime

---

packages/composer-admin/api.txt
packages/composer-admin/changelog.txt
packages/composer-admin/lib/adminconnection.js
packages/composer-admin/test/adminconnection.js
packages/composer-client/api.txt
packages/composer-client/changelog.txt
packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/connection.js
packages/composer-common/test/connection.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-proxy/lib/proxyconnection.js
packages/composer-connector-proxy/test/proxyconnection.js
packages/composer-connector-web/lib/webconnection.js
packages/composer-connector-web/test/webconnection.js
packages/composer-playground/e2e/scripts/cleanupFabric.sh
packages/composer-playground/e2e/scripts/setupFabric.sh
packages/composer-tests-functional/scripts/run-fv-tests.sh
packages/composer-tests-functional/systest/data/common-network/transactions.cto
packages/composer-tests-functional/systest/data/common-network/transactions.js
packages/composer-tests-functional/systest/native.js
packages/composer-tests-functional/systest/transactions.native.js
packages/composer-tests-integration/scripts/run-integration-tests.sh

https://github.com/hyperledger/composer/issues/3838
Testing build in PR.

Add getNativeAPI() to admin and client APIs (contributes to #3838)

---

packages/composer-tests-functional/systest/native.js

Oops 🐧 
https://github.com/hyperledger/composer/issues/3838

Remove .only from functional tests (contributes to #3838)

---

NOTICES.md
packages/composer-cli/gen/transactiontemplate
packages/composer-cli/package.json
packages/composer-common/lib/filewallet.js
packages/composer-common/package.json
packages/composer-common/test/filewallet.js
packages/composer-playground/package.json
packages/composer-tests-functional/package.json
packages/composer-wallet-filesystem/test/config.js

Remove dependency on homedir package

---

packages/composer-cucumber-steps/lib/composer.js
packages/composer-cucumber-steps/test/composer.js

https://github.com/hyperledger/composer/issues/3878
1.
2.
3.
4.

Cucumber: properly parse and validate input based on type

---

packages/composer-rest-server/lib/util.js
packages/composer-rest-server/test/lib/util.js

Prompt for API key in interactive REST server startup

---

packages/composer-tests-functional/systest/data/common-network/transactions.cto
packages/composer-tests-functional/systest/data/common-network/transactions.js
packages/composer-tests-functional/systest/transactions.native.js

Add failure scenarios to invoking other chaincode

---

packages/composer-runtime/package.json

debug not used

---

packages/generator-hyperledger-composer/generators/businessnetwork/templates/package.json
packages/generator-hyperledger-composer/test/business-network.js

Add engines stanza to generated business network package.json

---

packages/composer-connector-hlfv1/package.json

lock grpc to 1.10.1

---

packages/composer-website/jekylldocs/tutorials/google_oauth2_rest.md

Signed-off-by: Paul O'M <mahoney@uk.ibm.com>
the source connection.json used in the BN cards for this tutorial could be in a different order (eg was 'peer, peer, orderer, ca' now 'orderer, peer, peer, ca' in recent micro releases). This will replace regardless of where in the order the stanza is. Its to allow persistent  REST server container to contact the other dockerized Fabric nodes in the network.
Rob T has tried out the changes.
- [ x]  A link to the issue/user story that the pull request relates to
#3446 #3792 
1.
2.
3.
4.

More robust sed match if order changes

---

packages/composer-tests-integration/features/rest-apikey.feature
packages/composer-tests-integration/lib/reststeps.js

Add integration test for REST server API key security

---

.travis/deploy.sh
packages/composer-website/jekylldocs/_config.yml
packages/composer-website/jekylldocs/_local.yml

Because GDPR worries
Closes #3978

Disable Google Analytics

---

.travis/deploy_docs.sh

https://github.com/hyperledger/composer/issues/3977

Don't try delivering doc changes if there are none (resolves #3977)

---

packages/composer-common/lib/serializer/jsonpopulator.js
packages/composer-common/test/serializer.js
packages/composer-runtime/test/registrymanager.js
packages/composer-tests-integration/features/cli-network.feature
packages/composer-tests-integration/features/generator-busnet.feature

Reject resource JSON with properties not defined by class declararation

---

packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodedatacollection.js
packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.registries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js

Signed-off-by: Nick Lincoln nkl199@yahoo.co.uk
closes #4000
Trace extended to runtime module
Trace modified to be more clear
statement in (ms) within trace
Swap to Date.now() instead of hrtime() to enable logging in now hlfv1 modules

modify perf trace logging

---

packages/composer-admin/package.json
packages/composer-cli/lib/cmds/card/lib/validate.js
packages/composer-cli/test/card/validate.js
packages/composer-client/package.json
packages/composer-common/lib/connectionprofilemanager.js
packages/composer-common/test/connectionprofilemanager.js
packages/composer-connector-embedded/lib/embeddedconnection.js
packages/composer-connector-embedded/lib/embeddedconnectionmanager.js
packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-connector-embedded/test/embeddedconnectionmanager.js
packages/composer-connector-server/lib/connectorserver.js
packages/composer-connector-server/package.json
packages/composer-connector-server/test/connectorserver.js
packages/composer-playground/e2e/verdaccio/npm_serve.js
packages/composer-tests-integration/scripts/npm_serve.js

This addresses various issues found in the embedded connector plus also adds a generic routing mechanism 
closes #3985 
closes #2857

New Improved Embedded Connector Plus proxy routing support

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

Addresses the inability to create a new connection if the first peer in the CCP channel definition is unavailable introduced by a change in the node-sdk to get the channelconfig from the first peer in the channel definition rather than the orderer.
closes #4017 

Fix HA for peers when 1st peer is down, workaround for node-sdk initialize issue

---

packages/composer-connector-hlfv1/package.json

Move to official grpc fix

---

packages/composer-runtime/lib/context.js

bypass full lookup

---

packages/composer-cli/lib/cmds/identity/issueCommand.js
packages/composer-cli/lib/cmds/network/installCommand.js
packages/composer-cli/lib/cmds/network/startCommand.js
packages/composer-cli/lib/cmds/network/upgradeCommand.js
packages/composer-website/jekylldocs/reference/composer.identity.issue.md
packages/composer-website/jekylldocs/reference/composer.network.install.md
packages/composer-website/jekylldocs/reference/composer.network.start.md
packages/composer-website/jekylldocs/reference/composer.network.upgrade.md

updated 8 files

---

packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.html
packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.spec.ts
packages/composer-playground/src/app/basic-modals/connect-confirm/connect-confirm.component.ts
packages/composer-playground/src/app/footer/footer.component.spec.ts
packages/composer-playground/src/app/login/login.component.html
packages/composer-playground/src/app/services/config/configStructure.service.spec.ts
packages/composer-playground/src/app/services/config/configStructure.service.ts

Also updates config service to include documentation URL
Closes #4096

Fix deploy doc links in playground

---

packages/composer-tests-integration/features/generator-angular.feature
packages/composer-tests-integration/lib/composer.js

closes #4110 
required changes:
- increase buffer to prevent stderr output exceeding limit and terminating process
- add the expected pass test
- add internal logging information of task running

incorporate angular gen unit tests to integration tests

---

packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-wallet-filesystem/lib/filesystemwallet.js
packages/composer-wallet-filesystem/test/config.js
packages/composer-wallet-filesystem/test/wallet.js

updates to remove promisification

---

packages/composer-website/jekylldocs/integrating/call-out.md
packages/composer-website/jekylldocs/integrating/customizing-the-rest-server.md
packages/composer-website/jekylldocs/integrating/node-red.md

As a user, I can customise the REST server to meet all of my requirements #4094
- Add some documentation that tells users how to use the thing!

Add documentation for customizing the REST server (contributes to #4094)

---

packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.network.download.md

Add a network download page.

---

contrib-notes/prerequisites-ubuntu.md

fix prereqs in contrib guide

---

.travis/deploy.sh

Convert npm publish items into an array
Build array of existing items
only publish if array sizes differ

skip npm publish if all modules exist

---

.travis/deploy.sh

bash arrays contain quote delimited items. Sigh.

make an actual array

---

packages/composer-common/lib/model/resourceid.js

closes #4203 with a 10% reduction in processing time 🐎

reduce code path in toURI

---

packages/composer-common/lib/introspect/modelfile.js

closes #4205 
Introduce a map to cache the import short names and wildcard namespaces that is populated on instantiate but used in the two 'expensive' methods. This change yields a 28% `toJSON()` benefit 👌

introduce map to cache types on instantiate

---

packages/composer-client/lib/businessnetworkconnection.js
packages/composer-client/test/businessnetworkconnection.js
packages/composer-common/lib/util.js
packages/composer-common/test/util.js
packages/composer-tests-functional/systest/data/transactions.cto
packages/composer-tests-functional/systest/data/transactions.js
packages/composer-tests-functional/systest/testutil.js
packages/composer-tests-functional/systest/transactions.js

#4165 
Handle return data from transaction processor functions in the Node.js client module, parse them into return values, and return those values to the calling application.

Handle return values from client side, add functional tests

---

packages/composer-website/jekylldocs/reference/js_scripts.md

#4165, #4224 
DOCUMENT ALL THE THINGS

Add documentation for transaction return types and commit flag

---

packages/composer-playground-api/scripts/devStart.sh

Cleanly stop npm proxy in Playground API devStart.sh

---

packages/composer-playground-api/routes/npm.js
packages/composer-playground-api/test/npm.js

move the npm search endpoint

---

packages/composer-website/jekylldocs/_data/conrefs.yml
packages/composer-website/jekylldocs/applications/web.md
packages/composer-website/jekylldocs/installing/development-tools.md
packages/composer-website/jekylldocs/installing/uninstall-dev-env.md
packages/composer-website/jekylldocs/installing/update-dev-env.md
packages/composer-website/jekylldocs/integrating/getting-started-rest-api.md
packages/composer-website/jekylldocs/reference/commands.md
packages/composer-website/jekylldocs/reference/composer.report.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-single-org.md
packages/composer-website/jekylldocs/tutorials/invoke-composer-network.md

Change docs to use explicit Composer and Fabric versions in commands

---

contrib-notes/cip-template.md
contrib-notes/coding-guidelines.md
contrib-notes/diagnostic-logging.md
contrib-notes/ide-setup.md
contrib-notes/prerequisites-ubuntu.md
contrib-notes/prerequisites.md
contrib-notes/submitting-pull-request.md

Fixed spelling errors and added sign off.

Fix spelling errors

---

.travis/deploy.sh
packages/composer-website/scripts/run-jekyll.sh

Fix bug in docs build script

---

packages/composer-website/jekylldocs/reference/js_scripts.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md

Point to different fabric-samples repo (for BYFN / EYFN 1.2 support),  and update Transaction Processor section to make known that REST API '@return' is available plus fix code sample.
Signed-off-by: Paul O'M <mahoney@uk.ibm.com>
- [ x]  A link to the issue/user story that the pull request relates to
https://github.com/hyperledger/composer/issues/4245
https://github.com/hyperledger/composer/issues/3148
https://github.com/hyperledger/composer/issues/4245
https://github.com/hyperledger/composer/issues/3148
1.
2.
3.
4.
- [x ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
https://github.com/hyperledger/composer/issues/4245
https://github.com/hyperledger/composer/issues/3148

Multi-Org 1.2 changes, TP docs changes

---

.travis/deploy.sh
packages/composer-website/scripts/run-jekyll.sh

Fix Ubuntu incompatibility in run-jekyll.sh

---

packages/composer-website/scripts/run-jekyll.sh

fix the docs build (on master)

---

.travis/deploy.sh

Contributes to #4326 
Signed-off-by: Mark S. Lewis <mark_lewis@uk.ibm.com>

Change release version bump to handle releases other than latest

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

remove signature verification as it has a performance
impact and provides no benefit.

[Master] remove signature verification

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js

remove signature verification as it is a performance bottleneck
with no benefit.

[0.19.x] Remove signature verification

---

packages/composer-playground/e2e/verdaccio/npm_serve.js

[0.19.x] Fix Build

---

packages/composer-playground/e2e/verdaccio/npm_serve.js

[Master] Fix Build

---

packages/generator-hyperledger-composer/generators/angular/templates/proxy.conf.js
packages/generator-hyperledger-composer/generators/angular/templates/src/app/transaction/transaction.component.html
packages/generator-hyperledger-composer/test/angular-archive.js
packages/generator-hyperledger-composer/test/angular-network.js

Fix the angular generator to support transaction
invocation and also remove the rubbish that was
cut and paste from asset or participant page
which was completely irrelevant

[Master] fix transaction part of generator

---

packages/composer-common/lib/log/logger.js
packages/composer-common/test/log/logger.js

Signed-off-by: nkl199@yahoo.co.uk <nkl199@yahoo.co.uk>
Addresses #4381
Conditional filtering on "Identifiable", "Typed" and "Buffer".
- Identifiable/Typed will log IDs
- Buffer will be checked for length and truncated if in excess

[0.19.x] restrict logging in v19.x branch

---

packages/composer-common/lib/log/logger.js
packages/composer-common/test/log/logger.js

Signed-off-by: nkl199@yahoo.co.uk <nkl199@yahoo.co.uk>
Addresses #4381 
- Conditional filtering on "Identifiable", "Typed" and "Buffer".
- Identifiable/Typed will log IDs
- Buffer will be checked for length and truncated if in excess

[Master] modify logger to restrict what is written to file

---

packages/composer-common/lib/log/logger.js
packages/composer-runtime/test/networkmanager.js

[master] change default log level to warn

---

packages/generator-hyperledger-composer/generators/angular/index.js

Removed the broken code.
It still won’t support concepts, but at least it won’t fail if the model
has a concept.

[Master] stop angular generator from failing on a concept

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

[0.19.x] query should try other peers

---

packages/composer-common/lib/connectionprofilemanager.js
packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodedatacollection.js
packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.registries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js

[0.19.x] Fix logging for runtime, set default to warning

---

packages/composer-website/jekylldocs/business-network/query.md
packages/composer-website/jekylldocs/reference/query-language.md

[0.19.x] remove references to LIMIT and SKIP

---

packages/composer-common/lib/idcard.js
packages/composer-common/lib/log/logger.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/test/log/logger.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/lib/hlfwalletproxy.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-documentation/package.json

Add performance logging to connector

---

packages/composer-website/jekylldocs/_includes/indexfooter.html
packages/composer-website/jekylldocs/support/support-index.md

[0.19.x] Remove Survey

---

packages/composer-common/lib/connectionprofilemanager.js
packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodedatacollection.js
packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.registries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js

[Master] fix runtime logging, default to warn

---

packages/composer-cli/README.md
packages/composer-website/jekylldocs/business-network/query.md
packages/composer-website/jekylldocs/reference/query-language.md

[master] remove LIMIT and SKIP documentation

---

packages/composer-website/jekylldocs/_includes/indexfooter.html
packages/composer-website/jekylldocs/support/support-index.md

[master] Remove survey

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

[Master] Fix HA Query

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js

[Master] event logging and channel closure

---

scripts/fabric-docker-env.sh

[Master] use 1.2.1 fabric

---

contrib-notes/coding-guidelines.md
packages/composer-common/lib/idcard.js
packages/composer-common/lib/log/logger.js
packages/composer-common/lib/modelmanager.js
packages/composer-common/test/log/logger.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/lib/hlfwalletproxy.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-documentation/package.json
packages/composer-playground/src/app/editor/upgrade/upgrade.component.html
packages/composer-rest-server/README.md

closes #4428
closes #4416
closes #4175

[Master] Client side perf logging, logging cleanup

---

CONTRIBUTING.md
contrib-notes/coding-guidelines.md
packages/composer-website/jekylldocs/support/support-index.md

[master] remove info about community calls

---

packages/composer-runtime-hlfv1/package.json

[Master] Upgrade Shim

---

packages/composer-website/jekylldocs/applications/web.md
packages/composer-website/jekylldocs/tutorials/deploy-to-fabric-multi-org.md
packages/composer-website/jekylldocs/tutorials/developer-tutorial.md
packages/generator-hyperledger-composer/README.md

Add caveats about extent/scope of Angular (and CLI) generators, add changes to support 1.2.1 in Multi-org tutorial.
- [x ]  A link to the issue/user story that the pull request relates to
https://github.com/hyperledger/composer/issues/4328
https://github.com/hyperledger/composer/issues/4328
1.
2.
3.
4.

[Master] Add caveats/advisory for scope of generators (Angular/CLI) plus Multi-Org Fabric v1.2.1 update

---

packages/composer-cli/docker/Dockerfile
packages/composer-playground/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile

Contributes to #4455
1.
2.
3.
4.

Add cloud wallet implementations to docker images

---

packages/composer-common/lib/log/logger.js
packages/composer-common/lib/log/winstonInjector.js
packages/composer-common/test/log/logger.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/lib/hlfutil.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlfutil.js
packages/composer-tests-integration/features/cli-identities.feature
packages/composer-website/jekylldocs/managing/connector-information.md

[Master] New event handler for hlfv1 connector

---

packages/composer-rest-server/package.json

[0.19.x] Fix Broken Dependency in Rest Server

---

packages/composer-rest-server/package.json

[Master] Fix broken dependency in Rest Server

---

packages/composer-runtime-hlfv1/package.json

[0.19.x] Upgrade shim to 1.1.4

---

packages/composer-runtime-hlfv1/package.json

[Master] Upgrade shim to 1.2.3

---

packages/composer-admin/lib/adminconnection.js
packages/composer-website/jekylldocs/reference/composer.network.reset.md

[Master] Highlight the danger of network reset

---

packages/composer-common/lib/log/logger.js
packages/composer-common/lib/log/winstonInjector.js
packages/composer-common/test/log/logger.js
packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfconnectionmanager.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/lib/hlftxeventhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

[0.19.x] Backport perf logging improvements

---

packages/composer-website/jekylldocs/prereqs-ubuntu.sh

[Master] fix prereqs script

---

packages/composer-website/jekylldocs/prereqs-ubuntu.sh

[0.19.x] fix prereqs script

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

[0.19.x] Allow txid to be passed to query requests

---

packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

[Master] Allow txid to be passed to query requests

---

packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime/lib/accesscontroller.js

[0.19.x] logging improvements

---

packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime/lib/accesscontroller.js

[Master] Logging improvements

---

packages/composer-common/lib/log/logger.js
packages/composer-common/test/log/logger.js
packages/composer-runtime-hlfv1/lib/composer.js
packages/composer-runtime-hlfv1/lib/nodecontext.js
packages/composer-runtime-hlfv1/lib/nodedatacollection.js
packages/composer-runtime-hlfv1/lib/nodedataservice.js
packages/composer-runtime-hlfv1/lib/nodeloggingservice.js
packages/composer-runtime-hlfv1/lib/nodeutils.js
packages/composer-runtime-hlfv1/test/nodecontext.js
packages/composer-runtime-hlfv1/test/nodeloggingservice.js
packages/composer-runtime-hlfv1/test/nodeutils.js
packages/composer-runtime/lib/accesscontroller.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.queries.js
packages/composer-runtime/lib/engine.registries.js
packages/composer-runtime/lib/engine.resources.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/package.json
packages/composer-runtime/test/context.js

This doesn’t fix it for any other logging as all trace points
in composer-runtime will need to be changed, also somehow
the context would have to be passed to apis in composer-common
as well.

[Master] Fix TxId logging for performance logging

---

packages/composer-rest-server/README.md

fix rest server npm readme

---

packages/composer-website/jekylldocs/business-network/cloud-wallets.md

[Master] Fix cloud wallets documentation

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnectionmanager.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

This is an experimental feature for composer and as such is not documented.

[0.19.x] Experimental Pluggable Query Handler

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlftxeventhandler.js

This is an experimental feature and meant for advanced and knowledgable composer
users who have multiple channels running the same bna and are looking to provide
scaling through multiple chaincode instances due to lack of capability currently in
hyperledger fabric.

[Master] Experimental override chaincode version

---

packages/composer-website/jekylldocs/business-network/cloud-wallets.md

[0.19.x] Fix cloud wallets documentation

---

packages/composer-connector-hlfv1/lib/hlfconnection.js
packages/composer-connector-hlfv1/lib/hlfqueryhandler.js
packages/composer-connector-hlfv1/test/hlfconnection.js
packages/composer-connector-hlfv1/test/hlfqueryhandler.js

This is an experimental feature for composer and as such is not documented.

[Master] Experimental Pluggable Query Handler

---

packages/composer-runtime-hlfv1/package.json

[Master] Upgrade Shim to address #4508

---

packages/composer-common/lib/serializer/resourcevalidator.js
packages/composer-common/test/serializer/resourcevalidator.js

This will resolve the specific problem raised in #4562 

[Master] Improve Resource Validator

---

packages/composer-connector-embedded/test/embeddedconnection.js
packages/composer-runtime-embedded/test/embeddedcontext.js
packages/composer-runtime-web/test/webcontext.js
packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/engine.js
packages/composer-runtime/lib/engine.transactions.js
packages/composer-runtime/test/context.js
packages/composer-runtime/test/engine.transactions.js
packages/composer-tests-functional/systest/nohistorian.js

[0.19.x] Experimental ability to disable historian

---

packages/composer-runtime/lib/context.js
packages/composer-runtime/lib/installedbusinessnetwork.js
packages/composer-runtime/test/context.js
packages/composer-runtime/test/installedbusinessnetwork.js

[0.19.x] Experimental cache enableHistorian flag

---

packages/composer-runtime/lib/engine.js
packages/composer-runtime/package.json
packages/composer-runtime/test/engine.js

[Master] Allow upgrade from 0.19.x

---

packages/composer-runtime-hlfv1/lib/nodecontext.js
packages/composer-runtime-hlfv1/test/nodecontext.js

[Master] expose clientIdentity in getNativeAPI

---

CONTRIBUTING.md
MAINTAINERS.md
README.md

Update markdown files with deprecation notice

---

packages/composer-website/jekylldocs/.gitignore
packages/composer-website/jekylldocs/_includes/header.html
packages/composer-website/jekylldocs/_layouts/default.html
packages/composer-website/jekylldocs/index.html
packages/composer-website/scripts/setup-jekyll.sh

Update website with deprecation notice

---

packages/composer-playground/src/assets/styles/base/_colors.scss
packages/composer-playground/src/assets/styles/composer.scss
packages/composer-playground/src/index.html

Update playground with deprecation notice

---

packages/composer-cli/docker/Dockerfile
packages/composer-playground/docker/Dockerfile
packages/composer-rest-server/docker/Dockerfile

Pin Dockerfiles to last known good version of Node.js

---

.travis/deploy.sh
.travis/deprecate.sh

Mark all npm modules as deprecated

---

.travis/deprecate.sh

Fix license in new deprecate.sh script

---

.travis/deploy.sh

Stop npm deprecate now all modules are deprecated

---

.travis/deploy.sh

Restart npm deprecate as it doesn't apply to new modules
